### ISSUE TITLE
Text Editing Gestures/Intents/Actions

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#101151]
Currently, gestures related to text editing are handled by `TextSelectionGestureDetectorBuilder`, with no way to override these gestures practically without using `IgnorePointer` which blocks all default gestures defined on the text editing widget. The goal here is to build something analogous to the current keyboard shortcuts -> intents -> action system, with defaults that can be practically overwritten by the user. 

☔️ To complete this issue we need:
  - [ ] All pointer-related text editing interactions ported to Intents/Actions, like tapping, long pressing, etc. #75004
  - [x] Support selection all text on triple click #63576
  - [x] Support double tap drag gesture to select a block of text on iOS #64550
  - [x] Single tap on text field to display toolbar #48434
  - [x] Hide selection toolbar when moving caret/handles #62193
  - [ ] Selection toolbar/handle should disappear when clicking outside of it #72029
  - [x] Textfield context menu does not show after focus switch #99707

Other issues of note:
 -  [ ] Textfield should receive callbacks from `TextSelectionGestureDetector` #35187
