### ISSUE TITLE
cleanup "flutter analyze"

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#10721]
Large goal:
Update `flutter analyze` to use the analysis server in the same way and using the same code as `flutter analyze --watch`. Ensure that all the current `flutter analyze` options are still supported.

Related issues to be addressed as part of this cleanup:
- [ ] cleanup `flutter analyze` command line arguments - https://github.com/flutter/flutter/issues/7274
- [x] flutter analyze --watch --flutter-repo check package conflicts - https://github.com/flutter/flutter/pull/10641
- [x] flutter analyze --watch --flutter-repo reports public members missing dartdoc - https://github.com/flutter/flutter/issues/11143
- [x] flutter analyze doesn't work well with nested (and different) .packages files  - https://github.com/flutter/flutter/issues/10015
- ~provide a --machine flag for `flutter analyze`~ (https://github.com/flutter/flutter/issues/10704)
- [ ] unify output of flutter analyze and flutter analyze --watch https://github.com/flutter/flutter/issues/2469

Also see [other "flutter analyze" issues](https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%27flutter%20analyze%27%20in%3Atitle) that might be related

**Comment by danrubel** [comment]
add [analysis server --flutter-repo startup flag](https://github.com/dart-lang/sdk/commit/def1ee6604c4b3385b567cb9832af0dbbaf32e0d)

**Comment by mit-mit** [comment]
@danrubel got an update on this work? What is the highlevel ETA for completing this? #10015 is especially painful; both in itself, and as it blocks other issues like https://github.com/flutter/flutter/issues/10898.

**Comment by danrubel** [comment]
I've been swamped with CFE work. I'll see if I can make some progress next week.

**Comment by Hixie** [comment]
cc @devoncarew Can more boxes be checked?

**Comment by devoncarew** [comment]
Yup, I updated the list above.

**Comment by bkonyi** [comment]
Closing since all relevant subtasks are closed.
