### ISSUE TITLE
Gather metrics around the number of lines of code in flutter/flutter and packages in flutter org that aren't null safe

### ISSUE THREAD

**Issue by nuritzi** [flutter/flutter#110468]
As we continue to work towards Dart null safety, we need to measure how we're doing on the Flutter side. To do this, we need to gather a few key metrics.

**Goal 1**: Track the number of lines of code in the flutter/flutter repo that aren't soundly null safe (@dart=x markers where x <2.12).

**Goal 2:** Track progress on % of packages under the flutter github org which are soundly null safe (meaning a) lower SDK >= 2.12, and b) no @Dart=x markers where x <2.12)

**Frequency**: we'd like to pull these stats on a weekly basis, if possible.

## Todos
 * [ ] **Measure:** Number of lines of code in the flutter/flutter repo that aren't soundly null safe (@dart=x markers where x <2.12)
 * [ ]  **Measure:** % of packages under the flutter github org which are soundly null safe
 * [ ] **Document** how you pulled this information (can be in a doc or in this issue). 
 * [ ] **Automate** a weekly report if possible. 

... this issue is related to the dart-lang/sdk one here: https://github.com/dart-lang/sdk/issues/49850

**Comment by itsjustkevin** [comment]
Tracked in https://github.com/flutter/flutter/issues/110016
