### ISSUE TITLE
☂️ Raise minimum macOS version from 10.13 to 10.14 for Flutter Desktop apps

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#114445]
## What is being proposed?
Raise the minimum supported macOS version to 10.14 (Mojave), dropping support for the current minimum supported version, macOS 10.13 (High Sierra). As Mojave requires Metal support, this will also eliminate the OpenGL backend. Support for the following hardware will be dropped:
* 2009-2010 MacBook
* 2010-2011 MacBook Pro
* 2010-2011 MacBook Air
* 2010-2011 Mac mini
* 2009-2011 iMac
* 2010 Mac Pro (unless GPU been upgraded to a Metal-capable GPU)

RFC: https://flutter.dev/go/flutter-drop-macOS-10.13-2022-q4

## Sub-tasks
* [x] Update app templates. Increase minimum macOS version from 10.13 to 10.14 in app template. Enforce plugins build for minimum macOS 10.14. (https://github.com/flutter/flutter/pull/114713)
* [x] In project migrator, migrate existing app minimum macOS version from 10.13 to 10.14. (Do not modify if >= 10.14) (https://github.com/flutter/flutter/pull/114713)
* [x] Update all code examples/tests to macOS 10.14 (https://github.com/flutter/flutter/pull/114713)
* [x] Set mac_sdk_min to 10.13 and macos_deployment_target to 10.14.0 in flutter/buildroot (https://github.com/flutter/buildroot/pull/648)
* [x] Roll updated buildroot (https://github.com/flutter/engine/pull/37380)
* [x] Update minimum supported macOS version to 10.14 in flutter/website

#### Cleanups
* [x] Locate and clean up any `@available` checks predicated on macOS 10.14
* [x] https://github.com/flutter/flutter/issues/108304

#### Post-stable
At most, packages in the https://github.com/flutter/packages repo support current `stable` release and the two previous stable releases. When Flutter 3.7 becomes the "stable - 2" release:
* [x] Update plugins to 10.14 and enforce minimum macOS version 10.14 (https://github.com/flutter/packages/pull/3987)

This can be done via the following command, followed by whatever changes are necessary to clean up:
```sh
dart script/tool/bin/flutter_plugin_tools.dart update-min-sdk \
    --flutter-min=3.7.0          \
    --run-on-changed-packages    \
    --base-branch=upstream/main
```

**Comment by stuartmorgan** [comment]
> * Update all existing Flutter plugins to macOS 10.14

This one is also post-stable, since our policy is to support `stable` with our packages.

**Comment by cbracken** [comment]
Merged the two items into one.
