### ISSUE TITLE
☂️ Convert plugins to Pigeon

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#117844]
Pigeon improves the ease and safety of plugin development, and we've been having good experiences switching our plugins over to it as Pigeon has continued to mature and stabilize:
- It eliminates bad-cast errors, where we make a mistake in the manual synchronization of expected types across the language boundary, including (in some languages) nullability mistakes in most cases.
  - It avoids the need to try to validate that contract in review, switching between the Dart and host code trying to see if all of the pieces line up as expected; instead the API definition can be easily reviewed, and then the implementations using that API can be reviewed in isolation, which is far easier.
- It avoids the need to manage a bunch of string constants across languages.
- It avoids a lot of tedious boilerplate for dictionary extraction to get individual arguments (and in ObjC, much of the need for annoying special-case handling of `NSNull`).

While it still has some limitations that we may want to address before adopting it in specific cases (e.g., we may want to implement an instance-tracking system before applying it to things like camera or maps, rather than having to build multiplexing in the API itself), in general we should plan to migrate all of our plugins to Pigeon.

This serves as a central tracking point, and explanation for the motivation for these migrations for future repo archeology. Plugin migrations are tracked in individual issues:
- [x] [camera](https://github.com/flutter/flutter/issues/117905)
- [x] [file_selector](https://github.com/flutter/flutter/issues/117906)
- [ ] [google_maps_flutter](https://github.com/flutter/flutter/issues/117907)
- [x] [google_sign_in](https://github.com/flutter/flutter/issues/117908)
- [x] [image_picker](https://github.com/flutter/flutter/issues/117909)
- [ ] [in_app_purchase](https://github.com/flutter/flutter/issues/117910)
- [x] [ios_platform_images](https://github.com/flutter/flutter/issues/117911)
- [x] [local_auth](https://github.com/flutter/flutter/issues/117912)
- [x] [path_provider](https://github.com/flutter/flutter/issues/105735)
- [x] [quick_actions](https://github.com/flutter/flutter/issues/117913)
- [x] [shared_preferences](https://github.com/flutter/flutter/issues/117914)
- [x] [url_launcher](https://github.com/flutter/flutter/issues/117915)

**Comment by stuartmorgan** [comment]
As a general note for conversions: except for cases where we are doing a full rewrite of the plugin for other reasons, or very small interfaces, it's best to convert things to Pigeon using something identical or very close to the existing method call structure (just converted to actual objects/params instead of arg maps), to minimize other changes (e.g., to unit test structure) in the PR. Once the Pigeon conversion has happened, follow-ups can adjust the boundary between native and Dart, or adjust to better match underlying platform APIs.
