### ISSUE TITLE
Resizing the space available for an intrinsic width down to almost nothing causes assertions.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1210]
### TODO:

- [x] make sure `RenderBlock` honours the constraints contract in its get*Intrinsic* methods.
- [x] add the asserts that `RenderIntrinsicWidth` has to as many other proxying get*Intrinsic* methods as we can, so that we catch the problem much closer to the source next time.

-@Hixie

----

### Original comment
```
-- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
The following exception was raised during performLayout():
'packages/flutter/src/rendering/proxy_box.dart': Failed assertion: line 404: 'width == constraints.constrainWidth(width)' is not true.

The following RenderObject was being processed when the exception was fired:

RenderIntrinsicWidth relayoutSubtreeRoot=up1
That RenderObject had the following owner:
IntrinsicWidth ← Center ← Positioned ← Stack ← ⋯
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      RenderIntrinsicWidth._getInnerConstraints (packages/flutter/src/rendering/proxy_box.dart:404)
#2      RenderIntrinsicWidth.performLayout (packages/flutter/src/rendering/proxy_box.dart:439)
#3      RenderObject.layout (packages/flutter/src/rendering/object.dart:725)

#4      RenderPositionedBox.performLayout (packages/flutter/src/rendering/shifted_box.dart:237)
#5      RenderObject.layout (packages/flutter/src/rendering/object.dart:725)
#6      RenderStackBase.performLayout (packages/flutter/src/rendering/stack.dart:345)
#7      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:632)
#8      RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:610)
#9      BindingBase&Scheduler&Gesturer&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:71)
#10     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:92)
#11     BindingBase&Scheduler&Gesturer&Renderer._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:65)
#12     BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:269)

#13     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:246)
#14     _beginFrame (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
```

**Comment by Hixie** [comment]
Oh actually I'm missing one key piece of information here which is: what was the first render object descendant of the IntrinsicWidth?

**Comment by apwilson** [comment]
Block

**Comment by Hixie** [comment]
Can you stick the following in your `void main()` and dump the output?
```dart
debugRenderingExceptionHandler = (RenderObject source, String method, dynamic exception, StackTrace stack) {
  debugPrint('exception: $exception\nsource: $source\nmethod: $method\nchildren:\n${source.toStringDeep()}');
};
```

**Comment by apwilson** [comment]
children:
RenderIntrinsicWidth relayoutSubtreeRoot=up1

 │ owner: IntrinsicWidth ← Center ← Positioned ← Stack ← ⋯
 │ parentData: offset=Offset(0.0, 0.0)
 │ constraints: BoxConstraints(0.0<=w<=16.0, 0.0<=h<=600.0)

 │ size: Size(16.4, 600.0)
 │ stepWidth: null

 │ stepHeight: null
 │
 └─child: RenderPointerListener relayoutSubtreeRoot=up2

   │ owner: Listener ← GestureDetector ← ScrollableViewport ← Block ← ⋯
   │ parentData: offset=Offset(0.0, 0.0)

   │ constraints: BoxConstraints(w=16.4, 0.0<=h<=600.0)
   │ size: Size(16.4, 600.0)
   │ listeners: down

   │ behavior: opaque

   │
   └─child: RenderPointerListener relayoutSubtreeRoot=up3

     │ owner: Listener ← Listener ← GestureDetector ← ScrollableViewport ← ⋯
     │ parentData: offset=Offset(0.0, 0.0)
     │ constraints: BoxConstraints(w=16.4, 0.0<=h<=600.0)
     │ size: Size(16.4, 600.0)
     │ listeners: down
     │ behavior: defer-to-child

     │
     └─child: RenderSizeObserver relayoutSubtreeRoot=up4

       │ owner: SizeObserver ← Listener ← Listener ← GestureDetector ← ⋯
       │ parentData: offset=Offset(0.0, 0.0)
       │ constraints: BoxConstraints(w=16.4, 0.0<=h<=600.0)

       │ size: Size(16.4, 600.0)
       │

       └─child: RenderViewport relayoutSubtreeRoot=up5
         │ owner: Viewport ← SizeObserver ← Listener ← Listener ← ⋯
         │ parentData: offset=Offset(0.0, 0.0)
         │ constraints: BoxConstraints(w=16.4, 0.0<=h<=600.0)
         │ size: Size(16.4, 600.0)

         │
         └─child: RenderSizeObserver relayoutSubtreeRoot=up6
           │ owner: SizeObserver ← Viewport ← SizeObserver ← Listener ← ⋯

           │ parentData: offset=Offset(0.0, 0.0)

           │ constraints: BoxConstraints(w=16.4, 0.0<=h<=Infinity)
           │ size: Size(16.4, 11600.0)
           │
           └─child: RenderBlock relayoutSubtreeRoot=up7

             │ owner: BlockBody ← SizeObserver ← Viewport ← SizeObserver ← ⋯
             │ parentData: offset=Offset(0.0, 0.0)
             │ constraints: BoxConstraints(w=16.4, 0.0<=h<=Infinity)
             │ size: Size(16.4, 11600.0)
             │ direction: ScrollDirection.vertical

             │
             ├─child 1: RenderPadding relayoutSubtreeRoot=up8
             │ │ owner: Padding ← Container ← BlockBody ← SizeObserver ← ⋯

             │ │ parentData: offset=Offset(0.0, 0.0)

             │ │ constraints: BoxConstraints(w=16.4, 0.0<=h<=Infinity)
             │ │ size: Size(16.4, 116.0)
             │ │ padding: EdgeDims(8.0, 8.0, 8.0, 8.0)
             │ │

             │ └─child: RenderConstrainedBox relayoutSubtreeRoot=up9
             │   │ owner: SizedBox ← Padding ← Container ← BlockBody ← ⋯
             │   │ parentData: offset=Offset(8.0, 8.0)
             │   │ constraints: BoxConstraints(w=0.4, 0.0<=h<=Infinity)
             │   │ size: Size(0.4, 100.0)
             │   │ additionalConstraints: BoxConstraints(w=100.0, h=100.0)
             │   │
             │   └─child: RenderPointerListener

             │     │ owner: Listener ← LongPressDraggable ← SizedBox ← Padding ← ⋯
             │     │ parentData: offset=Offset(0.0, 0.0)
             │     │ constraints: BoxConstraints(w=0.4, h=100.0)
             │     │ size: Size(0.4, 100.0)
             │     │ listeners: down
             │     │ behavior: defer-to-child

             │     │

             │     └─child: RenderPointerListener

             │       │ owner: Listener ← GestureDetector ← Listener ← LongPressDraggable ← ⋯
             │       │ parentData: offset=Offset(0.0, 0.0)

             │       │ constraints: BoxConstraints(w=0.4, h=100.0)

             │       │ size: Size(0.4, 100.0)

             │       │ listeners: down
             │       │ behavior: defer-to-child
             │       │
             │       └─child: RenderConstrainedBox

             │         │ owner: SizedBox ← Container ← Listener ← GestureDetector ← ⋯
             │         │ parentData: offset=Offset(0.0, 0.0)
             │         │ constraints: BoxConstraints(w=0.4, h=100.0)

             │         │ size: Size(0.4, 100.0)

             │         │ additionalConstraints: BoxConstraints(w=100.0, h=100.0)

             │         │
             │         └─child: RenderDecoratedBox
             │           │ owner: DecoratedBox ← Container ← SizedBox ← Container ← ⋯
             │           │ parentData: offset=Offset(0.0, 0.0)

             │           │ constraints: BoxConstraints(w=0.4, h=100.0)
             │           │ size: Size(0.4, 100.0)
             │           │ decoration:

             │           │   backgroundColor: Color(0xfff7f2cb)

             │           │
             │           └─child: RenderConstrainedBox

             │               owner: ConstrainedBox ← DecoratedBox ← Container ← SizedBox ← ⋯
             │               parentData: offset=Offset(0.0, 0.0)
             │               constraints: BoxConstraints(w=0.4, h=100.0)

             │               size: Size(0.4, 100.0)
             │               additionalConstraints: BoxConstraints(biggest)
             │
             ├─child 2: RenderPadding relayoutSubtreeRoot=up8

**Comment by apwilson** [comment]
the gaps in the lines make me sad

**Comment by Hixie** [comment]
Looks like the bug is in `RenderBlock`. If I'm reading it right, we don't honour the constraints in its intrinsic sizing methods.

- [ ] make sure `RenderBlock` honours the constraints contract in its get*Intrinsic* methods.
- [ ] add the asserts that `RenderIntrinsicWidth` has to as many other proxying get*Intrinsic* methods as we can, so that we catch the problem much closer to the source next time.
