### ISSUE TITLE
Flutter Dartanalyzer plugin

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1220]
These are ideas for our analyzer plug-in.
## Features for Dart in General
- [ ] Warn when you use a label, to catch errors like: https://github.com/flutter/flutter/commit/f808055756d3b7946be90a4aec74e59eb40eddba#diff-6d433f126d05f45352a40b9bb916ac70R779
- [x] `@mustCallSuper` for methods what when overridden must call super somewhere.
  - [x] annotation in `meta`
  - [x] lint: https://github.com/dart-lang/linter/issues/194
- [x] `@protected` for members that must only be used in instance members of subclasses.
  - [x] annotation: https://github.com/dart-lang/sdk/issues/25841
  - [x] lint: https://github.com/dart-lang/linter/issues/189
- [x] `@immutable` for class hierarchies that must be immutable
  - [x] annotation in `meta`
  - [x] lint
- [x] operator == on all `@immutable` objects
- [x] `@factory` for functions whose overrides must return newly allocated objects
  - [x] annotation in `meta`
  - [x] lint
- [ ] `@literal` on const constructor to require 'const' for any call to that constructor if all the arguments are themselves const expressions (to catch e.g. `new Size(1.0, 1.0)`).
  - [x] annotation in `meta`
  - [ ] lint
- [ ] If a `List` or `Map` literal consists entirely of const expressions, require that the list or map be const also.
- [ ] disallow use of `super` to refer to any member other than the one being overridden.
- [x] implicit dynamic
  - [x] variables, method arguments, type arguments
  - [x] Map and List literals
  - [x] don't ask for types on setters
  - [x] annotation to label a class as having optional type arguments
- [x] `@required` on optional arguments which requires the argument to be present
  - [x] annotation in `meta`
  - [x] warning (https://github.com/dart-lang/sdk/issues/26182)
- [ ] all final fields compared by operator == and listed in hashCode.
- [x] hashCode on anything with an operator == 
  - [x] https://github.com/dart-lang/linter/issues/168
- [x] disallow `==` operator to be used when the types inferred on both sides aren't compatible
- [x] Constructors are first in a class 
  - [x] https://github.com/dart-lang/linter/issues/186.
- [x] Default constructor is first constructor 
  - [x] https://github.com/dart-lang/linter/issues/187
- [ ] operator==, hashCode, toString are last in a class.
- [x] public members have dartdocs
  - [x] https://github.com/dart-lang/linter/issues/188
- [x] `@override` that complains when a method is an override but doesn't say @override and that complains when a method isn't but does 
  - [x] https://github.com/dart-lang/linter/issues/167
- [ ] `@mustOverride`
  - [x] https://github.com/dart-lang/sdk/issues/28250
## Very Flutter-specific
- [ ] Something to note that a class hierarchy requires every public field to be read during `debugFillDescription`
- [ ] verify that you don't write a class that `implements` a class from the Flutter framework unless that Flutter framework class is marked `@interface`. (see https://github.com/dart-lang/sdk/issues/25462)
- [x] Warning about buttons without an `onPressed` argument.
- [ ] Warn when a `StatefulWidget` mutates a member field outside a `setState()` callback.
- [ ] Warn when a `Padding` contains a `Block`, that you may want to use the Block's `padding` member instead
- [x] Warn when a Color's constructor's argument is a literal int that isn't in hex. (`use_full_hex_values_for_flutter_colors`)
- [x] Warn when a Color's constructor's argument is a hex literal that isn't exactly 8 characters long.  (`use_full_hex_values_for_flutter_colors`)
- [x] Suggest putting `child`/`children` arguments last in constructors (`sort_child_properties_last`)
- [ ] Warn when a subclass of `State` defines a constructor (it should use the default constructor and do initialization in `initState()`, accessing any `final` configuration information using the `widget` getter).
- [ ] Warn when the number of constructor parameters in a `RenderObjectWidget.createRenderObject` is not the same as the number of setters called in `updateRenderObject`. 
- [ ] Warn when a GlobalKey is constructed in a build method. See https://github.com/dart-lang/linter/issues/1766.
- [ ] Disallow overloading `operator ==` and `hashCode` in widget classes. See https://github.com/flutter/flutter/pull/41220#discussion_r332737769 and https://github.com/dart-lang/linter/issues/1783

**Comment by abarth** [comment]
- [ ] `@factory` for functions whose overrides must return newly allocated objects

**Comment by Hixie** [comment]
- [ ] `@override` that complains when a method is an override but doesn't say `@override` and that complains when a method isn't but does.

**Comment by devoncarew** [comment]
cc @pq

**Comment by abarth** [comment]
Something to note that a class hierarchy requires every public field to be read during `debugFillDescription`

**Comment by Hixie** [comment]
- [ ] implicit dynamic (if it's not done by the analyzer proper by the time we get to this)

**Comment by Hixie** [comment]
- [ ] verify that you don't write a class that `implements` a class from the Flutter framework unless that Flutter framework class is marked `@interface`. (see https://github.com/dart-lang/sdk/issues/25462)

**Comment by Hixie** [comment]
- [ ] all final fields compared by operator == and listed in hashCode.
- [ ] operator == on all `@immutable` objects
- [ ] hashCode on anything with an operator ==

**Comment by Hixie** [comment]
- [ ] Constructors are first in a class.
- [ ] Default constructor is first constructor.
- [ ] operator==, hashCode, toString are last in a class.
- [ ] Public members have dartdocs.

(I dunno if these are actually possible; the necessary information may be lost once the analyzer's parsed the code.)

**Comment by Hixie** [comment]
- [ ] `@required` on optional arguments which requires the argument to be present

**Comment by Hixie** [comment]
- [ ] `==` operator used when the types inferred on both sides aren't compatible

**Comment by Hixie** [comment]
- [ ] disallow use of `super` to refer to any member other than the one being overridden.

**Comment by abarth** [comment]
- [ ] Warning about buttons without an `onPressed` argument.

**Comment by Hixie** [comment]
https://github.com/flutter/experimental-temporary-dartanalyzer-fork/pull/2

**Comment by Hixie** [comment]
- [ ] `@literal` on const constructor to require 'const' for any call to that constructor if all the arguments are themselves const expressions (to catch e.g. `new Size(1.0, 1.0)`).

**Comment by Hixie** [comment]
- [ ] If a `List` or `Map` literal consists entirely of const expressions, require that the list or map be const also.

**Comment by sethladd** [comment]
I've merged all the individual suggestions into the top of this issue. This helps Github track progress.

**Comment by Hixie** [comment]
- [ ] Warn when a `StatefulComponent` mutates a member field outside a `setState()` callback.

**Comment by jmesserly** [comment]
question on `@factory` ... does it mean "returns any object that was allocated between the start and end of the method call" or does it imply something more specific about the allocation?

I'm wondering about `whose overrides must return newly allocated objects` ... does the override have to return a tighter type?

An example might help. By the way, it seems neat to me, just trying to understand what it means.

**Comment by abarth** [comment]
> returns any object that was allocated between the start and end of the method call

Yes, that.

> does it imply something more specific about the allocation?

I don't think so...

> does the override have to return a tighter type?

Not necessarily.

> An example might help.

http://docs.flutter.io/flutter/widgets/StatefulComponent/createState.html is an example.  Subclasses are supposed to override that function and return a newly allocated object.  Some people try to return an existing object, but that's not permitted by the contract for that function.

**Comment by jmesserly** [comment]
Thanks, that example is great! It's sort of like saying, "this method will return a State that is unique, i.e. not identical, from all other State instances that exist before the call".

Would it be bad if the function cached the value?
```dart
State createState() => _state = new MyState();
```
Reason I ask, it sort of feels like a https://en.wikipedia.org/wiki/Uniqueness_type, but not quite. Anyway, it's not important :), was just trying to wrap my head around how it might relate to other type system features.

**Comment by abarth** [comment]
> Would it be bad if the function cached the value?

That implementation is not allowed by the contract of that method.

> Reason I ask, it sort of feels like a https://en.wikipedia.org/wiki/Uniqueness_type, but not quite

Yes, another way of stating the desired property is that the return value of this function contains the only reference to that instance of the object.

**Comment by Hixie** [comment]
Warn when a `Padding` contains a `Block`, that you may want to use the Block's `padding` member instead.

**Comment by apwilson** [comment]
The constructors being first in class seems like something the formatter should enforce, not the analyzer.

**Comment by apwilson** [comment]
This might be covered by a couple of comments above (ie. Buttons should have impressed argument) but it's be nice to be able to say "these named parameters to the function/ conductor must be supplied and must be non null.  (ie. Even though they appear optional, they are required)

**Comment by pq** [comment]
> The constructors being first in class seems like something the formatter should enforce, not the analyzer.

At the moment, the [formatter](https://github.com/dart-lang/dart_style) is not opinionated about member sorting.  My sense from chats with @munificent are that it never will be...

**Comment by pq** [comment]
> This might be covered by a couple of comments above (ie. Buttons should have impressed argument) but it's be nice to be able to say "these named parameters to the function/ conductor must be supplied and must be non null. (ie. Even though they appear optional, they are required)

We've actually just landed a new `@required` annotation (https://github.com/dart-lang/sdk/commit/33250f8ff5305f3e7de61f8553cd4a42e5b0c0cf) with this use case in mind (doesn't enforce non-nullability though)...

**Comment by apwilson** [comment]
Seems like @required should enforce non-null as the default of not providing something is for it to be null.  Perhaps you don't know if its null at analyzation time, however.

**Comment by pq** [comment]
Right.  CC @bwilkerson for more on that....

**Comment by jmesserly** [comment]
> > The constructors being first in class seems like something the formatter should enforce, not the analyzer.

> At the moment, the formatter is not opinionated about member sorting. My sense from chats with @munificent are that it never will be...

yeah, I feel like we're going to need a new tool to handle automatic code style conventions.

Originally my hope was the formatter, but it got a self-imposed whitespace-only rule.

Then my hope was the linter, but it only displays messages, not offering to fix things that can be fixed in automated fashion. But maybe it could be extended... ?  Or do we need a third thing?

(Just coming from the users perspective here. We should make their lives easy and fix anything we can fix automatically.)

**Comment by jmesserly** [comment]
> Seems like @required should enforce non-null as the default of not providing something is for it to be null. Perhaps you don't know if its null at analyzation time, however.

Yeah, that's exactly right. We don't have non-null in Dart's type system, so Analyzer doesn't understand it.

There is a lovely proposal to fix that: https://github.com/dart-lang/dart_enhancement_proposals/issues/30

As soon as we get some spare time (from finishing up strong mode, generic methods) I think NNBD will be next on the list.

**Comment by pq** [comment]
> Then my hope was the linter, but it only displays messages, not offering to fix things that can be fixed in automated fashion. But maybe it could be extended... ?

:+1: 

Lints are just errors as far as the analyzer and server are concerned which means they're just as easy to hang quick-fixes off.  Adding quick fixes to server would be trivial.  Tooling to automatically apply them wouldn't be hard either.

**Comment by Hixie** [comment]
I'm not worried about people explicitly passing null. That's an explicit action. I'm more worried about people unknowingly omitting key arguments and never finding out because they miss that code path in their testing. (We assert that required arguments are non-null, so if you hit that code path in testing you'll find out already -- this is just about catching things statically.)

**Comment by jmesserly** [comment]
yeah I think the main benefit of `@required` is to give Dart "required named parameters". Named parameters read well at the call site. But if the parameter is actually required, making it optional can open a hole in static verification of the program. Required named parameters solves that. Kind of matches how positional parameters can be required or optional.

**Comment by apwilson** [comment]
I would think the dart language itself should have a construct for required named parameters (maybe a leading ! or some other symbol similar to how a leading _ is supposed to indicate a private variable.)

**Comment by jmesserly** [comment]
@apwilson it's easier to start with annotations, try it out, and decide if the frequency merits dedicated syntax. But in the long run, you may be right about having syntax.

**Comment by munificent** [comment]
> At the moment, the formatter is not opinionated about member sorting. My sense from chats with @munificent are that it never will be...

In general, the formatter does not make any changes that involve reordering. It keeps things simpler because then it doesn't have to worry about all of the weird corner cases around comments between the moved code.

I'm not averse to automated reordering in general. I like tools that sort my imports.

I am not personally a fan of automated member reordering. Alphabetization has zero value for me—I don't find a member by scrolling down the file looking at names, I do a search if I know its name. I prefer members to be logically grouped together.

**Comment by apwilson** [comment]
For stuff flagged as an error can we have some reasoning added to the error message?

For example:
```
[lint] Avoid using braces in interpolation when not needed. 
```

Doesn't really say why.  If it's because of some style guide we should link to the style guide.  If its because it could cause an error we should say what kind of error it could cause imo.  Or link to a description.

**Comment by jmesserly** [comment]
> For stuff flagged as an error can we have some reasoning added to the error message?
> `[lint] Avoid using braces in interpolation when not needed.`

The answer for that one is:
https://www.dartlang.org/effective-dart/usage/#avoid-using-curly-braces-in-interpolation-when-not-needed

Best place to file an issue for it is:
https://github.com/dart-lang/linter/issues

**Comment by apwilson** [comment]
Unfortunately that link doesn't really elaborate anymore than the original string.

If linter is the source of this message, how come we see this in flutter analyze and not dartanalyzer, its from the --strong option or something?

**Comment by munificent** [comment]
Rule number 2 [here](https://www.dartlang.org/effective-dart/) basically justifies the guideline in question. `"Hi $name."` is more terse than `"Hi ${name}."`, so unless the extra verbiage adds value in some other way, the guidelines lean towards the more terse option.

**Comment by bwilkerson** [comment]
It's because lints are disabled by default in `dartanalyzer`, but enabled by default in `flutter analyze`. You can pass the `--lints` option to `dartanalyzer` to enable lints.

**Comment by Hixie** [comment]
Warn when you use a label, to catch errors like: https://github.com/flutter/flutter/commit/f808055756d3b7946be90a4aec74e59eb40eddba#diff-6d433f126d05f45352a40b9bb916ac70R779

**Comment by Hixie** [comment]
- [ ] Warn when a Color's constructor's argument is a literal int that isn't in hex.
- [ ] Warn when a Color's constructor's argument is a hex literal that isn't exactly 8 characters long.

**Comment by Hixie** [comment]
I've rearranged the list of lints in the first section. I tried prioritising the things there but honestly there's nothing I would say is a particularly low priority compared to the rest.

**Comment by sethladd** [comment]
Could we give this issue an update, checking off lints we've added? I see various ideas spread across many comments. Getting a single list, prioritized, would be helpful. Thanks!

**Comment by Hixie** [comment]
The top comment has been kept up to date with the list of ideas and with checking off those that are done.

**Comment by sethladd** [comment]
Opened https://github.com/dart-lang/sdk/issues/27750 for the request for `@immutable`

**Comment by Hixie** [comment]
`@mustOverride` would be useful in some places, see also https://github.com/dart-lang/sdk/issues/28250

**Comment by collinjackson** [comment]
I added to the top comment that we should warn when a subclass of `State` defines a constructor (it should use the default constructor and access its configuration with the `widget` getter).

**Comment by brianegan** [comment]
I'm not sure how good the accessibility story is for Flutter yet (looks like there's work being done), but I'd love a set of lint warnings for accessibility violations as a developer so I can keep my app in good shape wrt Accessibility.

Example:

  - [ ] `Error: IconButton does not have a tooltip`
  - [ ] `Error: Image does not have description` (although I actually don't right now see a way to apply accessible text to images)

etc...

**Comment by sethladd** [comment]
Thanks for the ideas!

**Comment by a14n** [comment]
dart-lang/linter#1388 solves:
- [x]  Warn when a Color's constructor's argument is a literal int that isn't in hex.
- [x] Warn when a Color's constructor's argument is a hex literal that isn't exactly 8 characters long.

**Comment by pq** [comment]
> Warn when a Padding contains a Block, that you may want to use the Block's padding member instead

@Hixie: I think this one is stale (no more `Block`)...  but are there modern equivalents to the advice?

**Comment by Hixie** [comment]
Block is called ListBody now but I'm not sure it's be useful to talk about that one specifically. What we really should do is review some applications and see if there are patterns of mistakes.

**Comment by pq** [comment]
In conversation about idioms we might enforce to make code easier to review (and less prone to error), @HansMuller suggested:

> Another idiomatic invariant that probably makes sense is to insist that the same class bear responsibility for creating and disposing classes like AnimationController, TextEditingController.

**Comment by Levi-Lesches** [comment]
Yeah this is just like `StreamController`, right?

**Comment by Levi-Lesches** [comment]
> Warn when a `StatefulWidget` mutates a member field outside a `setState()` callback.

Actually, I was thinking, why can't you just have the mutating code, and _then_ call `setState`? 

Like, instead of (assuming there is a field called `value`: 
```dart
void increment() => setState(() => value++);
```
Just do 
```dart
void increment() {
  value++;
  setState()  // rewrite setState to not need the callback parameter
}
```
The fact that this will need its own line isn't so bad since most production code will anyway have functions more than one line long. In such functions, it can be annoying, if not redundant, to separate the "calculating the value" from "assigning that value to the field", and it often trips up beginners who have to separate the two in their heads.

**Comment by Levi-Lesches** [comment]
Was this meant to be closed? https://github.com/dart-lang/linter/issues/2070 still refers to it and it might make it look that that issue can be closed as well.

**Comment by Hixie** [comment]
Ah yeah we can close that one too. I closed this one because we've added the majority of the suggestions listed above and at this point new suggestions just get filed directly on the linter repo, which is more appropriate.
