### ISSUE TITLE
rasterizer regression from flutter engine roll

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#122897]
## description
The following benchmarks have experienced a regression as a result of a engine roll into the framework of about 16%:

- 90th_percentile_frame_rasterizer_time_millis
- 99th_percentile_frame_rasterizer_time_millis
- average_frame_build_time_millis
- average_frame_rasterizer_time_millis
- worst_frame_rasterizer_time_millis

## engine roll

https://github.com/flutter/flutter/pull/122851

## potential culprits

- [x] 2023-03-16 dnfield@google.com Update documentation on `AccessibilityFeatures.boldText` (flutter/engine#40364)
- [x] 2023-03-16 jacksongardner@google.com Output web test artifacts to out directory. (flutter/engine#40355)
- [x] 2023-03-16 bdero@google.com [Impeller] Update scene importer tests (flutter/engine#40363)
- [x] 2023-03-16 gspencergoog@users.noreply.github.com Handle error more gracefully, add test for same (flutter/engine#40361)
- [x] 2023-03-16 goderbauer@google.com Remove work around for dart 3 compiler bug (flutter/engine#40350)
- [ ] 2023-03-16 jonahwilliams@google.com [Impeller] mark decoded images as optimized for GPU access (flutter/engine#40356)
- [x] 2023-03-16 robert.ancell@canonical.com Fix incorrect usage of fl_method_error_response_new in documentation example (flutter/engine#40288)
- [x] 2023-03-16 jonahwilliams@google.com [Impeller] fix opacity inheritance test (flutter/engine#40360)

## skiaperf
https://flutter-flutter-perf.skia.org/e/?begin=1678999929&end=1679066557&keys=X8a7bf9165ee1430b7d0824948f07499a&selected=commit%3D33850%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_impeller_ios__timeline_summary%252C&xbaroffset=33850

**Comment by gaaclarke** [comment]
After reviewing all the possible PR's I believe the regression happened in https://github.com/flutter/engine/pull/40356

**Comment by jonahwilliams** [comment]
This likely regressed because I added another command to the command buffer used for the blit pass, and we currently block on command completition:

https://github.com/flutter/flutter/issues/120399

**Comment by jason-simmons** [comment]
I tried reproducing the `platform_views_scroll_perf_non_intersecting_impeller_ios__timeline_summary` regression locally on an iPhone 11 but so far have been unable to.

The graph linked above shows that the regression started at another (seemingly unrelated) commit earlier on 3/16/2023.  It then disappeared for a few commits and reappeared at the https://github.com/flutter/flutter/pull/122851 engine roll.

Were there any changes  to infrastructure around that time?

**Comment by chinmaygarde** [comment]
The culprit was reverted in https://github.com/flutter/engine/pull/40387 and won't reland since it is no longer necessary (we were using host-visible textures earlier but are now using device-private instead with the intermediate copy being elided by making Skia decompress into a device buffer).
