### ISSUE TITLE
Flutter TextField focus state is not correct when keyboard closed from platform side.

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#123523]
Now our unfocus signal always sends from framework side. But when platform side close the keyboard, we should sync this state to framework side and unfoucs the `FocusNode` to let UI state correct.

Now on flutter `master` channel:

<details>

<summary>Demo code</summary>

```dart
void main() {
  runApp(const MyApp());
}

class KeyboardPage extends StatefulWidget {
  const KeyboardPage({Key? key}) : super(key: key);

  @override
  State<KeyboardPage> createState() => _KeyboardPageState();
}

class _KeyboardPageState extends State<KeyboardPage> {
  FocusNode node = FocusNode();

  @override
  void initState() {
    super.initState();
    node.addListener(() {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Text(
            node.hasFocus ? 'focus' : 'unfocus',
            style: const TextStyle(fontSize: 26, color: Colors.black),
          ),
          CupertinoTextField(
            focusNode: node,
            decoration: const BoxDecoration(color: Colors.red),
          )
        ],
      ),
    );
  }
}
```

</details>

iPhone |iPad|Android|
---|---|-------|
<img src="https://user-images.githubusercontent.com/49340347/227866417-e94db2c3-557a-404e-a1a1-83ee99a6f779.gif" width=200 /> | <img src="https://user-images.githubusercontent.com/49340347/227866797-a27e5116-97cc-4db2-92d5-fc2244eb5156.gif" width=300 /> | <video src="https://user-images.githubusercontent.com/49340347/227869250-fee0660d-30b4-47bf-b1b1-ae29e599e7b5.mp4" width=400 /> |

### TODO PRs:

Flutter framework PR:
- [x] https://github.com/flutter/flutter/pull/123929

iOS engine PR:
- [x] https://github.com/flutter/engine/pull/41022

Android engine PR
- [x] https://github.com/flutter/engine/pull/40746

**Comment by luckysmg** [comment]
cc @LongCatIsLooong @justinmc who maybe more familiar with text input implementation.

After landed iOS engine first PR. I found when close keyboard from platform side invoke `onConnectionClosed` method call, will invoke `submit` if `onSubmitted` callback passed in.  **Which will cause unexpected behavior, so have revert that PR and will have futher investigation.**

### To reland

See the comment in `text_input.dart` on method `connectionClosed()`

```dart
  /// Platform notified framework of closed connection.
  ///
  /// [TextInputClient] should cleanup its connection and finalize editing.
```

I think when user close from platform, **like the third party keyboard close button, and iPad close button, we just want to close the keyboard and unfocus without submiting the content.**

### Solution (In Triage)

#### Framework side 

1. In `void _finalizeEditing(TextInputAction action, {required bool shouldUnfocus}) {}`
https://github.com/flutter/flutter/blob/9dc4f839652f7270a53a57c409eadb8e006796d2/packages/flutter/lib/src/widgets/editable_text.dart#L2972


3. Add a optional param `shouldSubmit`, so the method will become:
```dart
void _finalizeEditing(TextInputAction action, {required bool shouldUnfocus, bool shouldSubmit = true})
```

4. Call 
```dart
 _finalizeEditing(TextInputAction.done, shouldUnfocus: true, shouldSubmit: false);
```
 in `connectionClosed()` method.
Seems that `connectionClosed` has no other caller and only be called in `TextInput`, so I think this will not be a break change?


#### Engine side
Just reland that PR.

**Comment by luckysmg** [comment]
All PRs done. Closed. ^_^

**Comment by justinmc** [comment]
Thanks for your work on this! :tada:

**Comment by luckysmg** [comment]
Also Thanks @ksballetba. ^_^
