### ISSUE TITLE
☂️ Make Flutter work for iOS App Extensions

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#124287]
#### Parent issue:  https://github.com/flutter/flutter/issues/16092

iOS application extensions are extra functionality that run outside an app, when the app is not running. 

This umbrella issue is to track the individual tasks to enable the support of app extension on iOS and macOS with approach 2 in the below design doc.

#### Task
- [x] https://github.com/flutter/flutter/issues/124286
- [x] https://github.com/flutter/flutter/issues/124289
- [ ] https://github.com/flutter/flutter/issues/124290 (macOS)
- [x] https://github.com/flutter/flutter/issues/124755 (macOS)
- [x] https://github.com/flutter/flutter/issues/124292
- [x] https://github.com/flutter/flutter/issues/124291
- [x] https://github.com/flutter/flutter/issues/124293
- [x] Add new artifacts to codesigning script and any recipe changes (coordinate with @XilaiZhang and @christopherfujino) https://github.com/christopherfujino/codesign.py/blob/master/codesign.py 
- [x] Update conductor to validate codesigning  the new artifacts, this may require a manual engine roll (coordinate with @XilaiZhang) https://github.com/flutter/flutter/blob/73bd97852978a4778f51dae0c48bc0c08d674edb/dev/conductor/core/lib/src/codesign.dart#L194-L199
- [ ]  Update g3 scripts to roll new artifact into g3 and update build rules so 1p apps can use for app extensions (coordinate with @chingjun) 
- [ ] https://github.com/flutter/flutter/issues/130445
- [ ] https://github.com/flutter/flutter/issues/135056

**Comment by jmagman** [comment]
@cyanglaz I took the liberty of adding a few tasks 🙂

**Comment by xster** [comment]
Is the current progress in the checklist up to date?

**Comment by cyanglaz** [comment]
> Is the current progress in the checklist up to date?

Yes

**Comment by cyanglaz** [comment]
App extension Flutter.framework is ready to be tested on main branch. They should be the respective folder under `path/to/flutter/bin/cache/artifacts/engine/ios-<runtime-mode>`

**Comment by karabanovbs** [comment]
@cyanglaz Hello! I'm very interested in this feature. Can I already try it on flutter master channel? 
App extension should use the same App.framework as main app, or can use own?

**Comment by cyanglaz** [comment]
@karabanovbs Yes this is available on master, a temporary usage guide can be found here: https://docs.google.com/document/d/1mWpg1qmCGWG1RreFrOI8-Y3p9usV50MHsECbeoQzDHk/edit'
This guide will be moved to a https://docs.flutter.dev page soon.

Due to Apple setting memory limits for extensions, it is only recommended to use flutter for extensions that have larger memory limits, for example, Share Extension.

**Comment by karabanovbs** [comment]
> @karabanovbs Yes this is available on master, a temporary usage guide can be found here: https://docs.google.com/document/d/1mWpg1qmCGWG1RreFrOI8-Y3p9usV50MHsECbeoQzDHk/edit' This guide will be moved to a https://docs.flutter.dev page soon.
> 
> Due to Apple setting memory limits for extensions, it is only recommended to use flutter for extensions that have larger memory limits, for example, Share Extension.

Great! Thanks a lot!

**Comment by cyanglaz** [comment]
Aslo un-assigning myself as I won't be working on this for the next 4 month or so because I will be on leave.

**Comment by gobright12** [comment]
Do I need an extra setup to establish a method channel? 
I keep getting the following error
[Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)]

and firebase initializeApp seems to fail as well complaining it cannot establish the method channels it requires.

**Comment by karabanovbs** [comment]
@cyanglaz Hi, after update on 3.16, my app didn't wort. Is it result of changes of this issue?
Can you see my issue?
https://github.com/flutter/flutter/issues/141319

**Comment by jmagman** [comment]
I'm going to close the umbrella issue, we'll track the individual issue left.
