### ISSUE TITLE
☂️ Tracking issue for macOS/Xcode/iOS upgrades

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#133207]
With looming updates on the horizon, we will need to perform various upgrades to our devicelab machines. This issue is meant to track the overall process of performing the necessary updates.

- [x] https://github.com/flutter/flutter/issues/134558 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/134559 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/134742 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/134735 (@vashworth)
- [x] https://github.com/flutter/flutter/issues/136256 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/136396 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/136257 (@yusuf-goog)
- [x] Test Xcode 14.3.1 on macOS 13.5+ (@vashworth)
- [x] https://github.com/flutter/flutter/issues/134736  (@vashworth)
- [x] Upgrade Phase 1 of https://github.com/flutter/flutter/issues/134737 (@yusuf-goog)
  * Blocking Issues discovered:
    - [x] https://github.com/flutter/flutter/issues/138238 (workaround added)
    - [x] https://github.com/flutter/flutter/issues/139152
    - [x] https://github.com/flutter/flutter/issues/138043
    - [x] https://github.com/flutter/flutter/issues/137634
    - [x] https://github.com/flutter/flutter/issues/138193 (temporarily fixed in https://github.com/flutter/engine/pull/47883)
  * Other Issues discovered:
    - [ ] https://github.com/flutter/flutter/issues/138246
    - [ ] https://github.com/flutter/flutter/issues/138224
    - [x] https://github.com/flutter/flutter/issues/138194
    - [x] https://github.com/flutter/flutter/issues/138109
- [x] Test Xcode 15 / iOS 17 simulator / macOS 13 via PR and led (@vashworth)
- [x] Upgrade Phase 2 of https://github.com/flutter/flutter/issues/134737 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/140975
  * Devicelab is done
  * Updating chromium tests is blocked by:
    - [x] https://github.com/flutter/flutter/issues/140835
- [x] Upgrade Phase 3 of https://github.com/flutter/flutter/issues/134737 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/140908 (@yusuf-goog)
- [x] https://github.com/flutter/flutter/issues/141177 (@vashworth)
- [x] Test Xcode 15 / iOS 17 device / macOS 13 on devicelab tests via led (@vashworth)
- [x] Update all tests to use Xcode 15 / iOS 17 simulator / macOS 13: https://github.com/flutter/flutter/issues/132237
  * Blocking Issues:
    - [x] https://github.com/flutter/flutter/issues/140835
- [x] https://github.com/flutter/flutter/issues/132252
  * Blocking Issues:
    - [x] https://github.com/flutter/flutter/issues/141383 - workaround added
    - [x] https://github.com/flutter/flutter/issues/141624 - was specific to one bot and has not reoccured since
- [x] https://github.com/flutter/flutter/issues/142326
- [x] Upgrade Phase 4 of https://github.com/flutter/flutter/issues/134737 (@yusuf-goog)
  * Blocking Issues:
    - [x] https://github.com/flutter/flutter/issues/140895
    - [x] https://github.com/flutter/flutter/issues/140835
    - [x] https://github.com/flutter/flutter/issues/139924
    - [x] https://github.com/flutter/flutter/issues/136972
    - [x] https://github.com/flutter/flutter/issues/136274
    - [x] https://github.com/flutter/flutter/issues/136279
    - [x] https://github.com/flutter/flutter/issues/132237 (@vashworth)
- [x] https://github.com/flutter/flutter/issues/142314
- [x] https://github.com/flutter/flutter/issues/144020
- [x] https://github.com/flutter/flutter/issues/143003
- [x] https://github.com/flutter/flutter/issues/144021
- [x] https://github.com/flutter/flutter/issues/136377 (@godofredoc)
  - [x] https://github.com/flutter/flutter/issues/122057 (@godofredoc)
    - [x] https://github.com/flutter/flutter/issues/133096 (@godofredoc)

**Comment by yusuf-goog** [comment]
Request for iOS updates:

https://github.com/flutter/flutter/issues/132251 and https://github.com/flutter/flutter/issues/132252

**Comment by yusuf-goog** [comment]
We upgraded a macos devicelab machine to 13.5 for testing: https://github.com/flutter/flutter/issues/132410

**Comment by yusuf-goog** [comment]
FYI, additional development's tracking bugs for these upgrades: https://github.com/flutter/flutter/issues/132128 & https://github.com/flutter/flutter/issues/132237

**Comment by yusuf-goog** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1475502 to upgrade VM to 13.5

**Comment by ricardoamador** [comment]
cc @godofredoc @ricardoamador. Adding Godofredo for visibility on tracking move to mac OS13.

**Comment by vashworth** [comment]
All macOS and iOS bots have been upgraded. Closing.
