### ISSUE TITLE
Rename MemoryAllocations to FlutterMemoryAllocations.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#140622]
**Why?**

Disposables in Dart cannot use MemoryAllocations in Flutter. So, to be leak trackable they need a dart-only class.
See detains in [the document](https://docs.google.com/document/d/1ireWmX4J5Jc6oDO1PmAXPlLdiAlCHvTz8SVC_Sg9KM8/edit?resourcekey=0-yODb_SAStMgMefYpQeX8uQ#bookmark=id.e3vlg7f7t1l).

**Why now?**

1. We want early adopters of leak tracker (for example, package owners) to use the class with the right name, so that they do not deal with renaming later.
2. It will take time for the renaming to land to flutter stable.

**Steps:**

- [x] Add FlutterMemoryAllocations and deprecate MemoryAllocations in Flutter
- [x] Document breaking change in Flutter: https://github.com/flutter/website/pull/10021
- [x] Update leak tracker to use FlutterMemoryAllocations
- [x] Roll leak tracker to G3
- [x] Upgrade flutter to new leak tracker
- [ ] Remove MemoryAllocations from Flutter

**Comment by AlvaroVasconcelos** [comment]
fixed?
https://docs.flutter.dev/release/breaking-changes/flutter-memory-allocations

**Comment by polina-c** [comment]
yes!
