### ISSUE TITLE
[Windows] Compositor rendering regresses apps with faded backgrounds

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#140828]
### Background

https://github.com/flutter/engine/pull/49262 updated Flutter Windows to render to an offscreen framebuffer instead of directly onto the window's surface. This will allow us to support platform views and multiple views.

Unfortunately, this change regresses [`package:material_floating_search_bar_2`'s animation](https://pub.dev/packages/material_floating_search_bar_2/versions/0.5.0) and causes weird artifacts.

<details>
<summary>`package:material_floating_search_bar_2` example...</summary>

(FYI there's a more minimal repro below)

```dart
import 'package:flutter/material.dart';
import 'package:material_floating_search_bar_2/material_floating_search_bar_2.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // This seems to be necessary to repro:
      debugShowCheckedModeBanner: false, 
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: FloatingSearchBar(
          // This seems to be necessary to repro:
          transition: CircularFloatingSearchBarTransition(spacing: 16),
          // This isn't necessary but it makes the artifacts more obvious: 
          transitionDuration: const Duration(seconds: 5),
          builder: (BuildContext context, _) {
            return Material(
             // This seems to be necessary to repro:
              borderRadius: BorderRadius.circular(8), 
              child: const Text('Hello world'),
            );
          },
          body: Container(),
        ),
      ),
    );
  }
}
```

</details>

### Minimal repro

[Download Windows app.zip](https://github.com/flutter/flutter/files/13893850/app.zip)

Commit | Scenario | Works?
-- | -- | --
https://github.com/flutter/flutter/commit/9c2a7560096223090d38bbd5b4c46760be396bc1 | Windows OpenGL | ✅
https://github.com/flutter/flutter/commit/b417fb828b332b0a4b0c80b742d86aa922de2649 | Windows OpenGL | ❌ 
https://github.com/flutter/flutter/commit/b417fb828b332b0a4b0c80b742d86aa922de2649 | Windows software rendering | ✅ 
https://github.com/flutter/flutter/commit/b417fb828b332b0a4b0c80b742d86aa922de2649 | Linux OpenGL | ✅ 
https://github.com/flutter/flutter/commit/b417fb828b332b0a4b0c80b742d86aa922de2649 | Web | ✅ 

<details>
<summary>Source code...</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Pump frames non-stop. This isn't necessary to repro.
  WidgetsBinding.instance.addPersistentFrameCallback((_) {
    WidgetsBinding.instance.scheduleFrame();
  });

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // This is necessary to reproduce:
    return Container(
      color: Colors.white,
      child: const Directionality(
        textDirection: TextDirection.ltr,
        child: BlueCircle(),
      ),
    );
  }
}

class BlueCircle extends StatelessWidget {
  const BlueCircle({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        const Opacity(
          opacity: 0.3,
          child: SizedBox.expand(
            child: DecoratedBox(
              decoration: BoxDecoration(color: Colors.black),
            ),
          ),
        ),

        SizedBox.expand(
          child: ClipOval(
            clipper: const _CircularRevealClipper(),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Colors.blue,
                // Removing this line fixes the app.
                borderRadius: BorderRadius.circular(16.0),
              ),
              child: const SizedBox(height: 256.0),
            ),
          ),
        ),
      ],
    );
  }
}

class _CircularRevealClipper extends CustomClipper<Rect> {
  const _CircularRevealClipper();

  @override
  Rect getClip(Size size) {
    return Rect.fromCircle(
      center: Offset.zero,
      radius: 500,
    );
  }

  @override
  bool shouldReclip(CustomClipper<Rect> oldClipper) => true;
}

```

</details>

<details>
<summary>Screenshot of the expected output...</summary>

![image](https://github.com/flutter/flutter/assets/737941/cb1feb39-3214-47a4-95f1-6af42e5f1760)

</details>

<details>
<summary>Screenshot of the actual output...</summary>

![image](https://github.com/flutter/flutter/assets/737941/e0ddfbaf-a317-418c-b803-395d4678b291)

</details>

### TODO

* [ ] ~~The engine has a dirty region feature that can be disabled. Check if disabling this fixes the issue.~~ RenderDoc showed that the framebuffer contains the expected texture. It appears that the compositor's `glFramebufferBlit` is the issue.
* [x] Enable Skia canvas trace commands to verify "good" and "bad" commits are drawing the same things
* [x] Use a GPU frame debugger (like RenderDoc) to look at GL calls

**Comment by loic-sharma** [comment]
# Skia tracing

Here are timeline traces with Skia enabled:

1. [Windows open animation on "good" commit](https://github.com/flutter/flutter/files/13834958/good_open_2.json)
1. [Windows open animation on "bad" commit](https://github.com/flutter/flutter/files/13834959/bad_open_2.json)
1. [Linux open animation on "bad" commit](https://github.com/flutter/flutter/files/13834960/linux_open_1.json)

You can open these by opening `chrome://tracing` in your browser and dragging and dropping these files.

Both Linux and Windows while on the "bad" commit render to an OpenGL framebuffer (see [`FlutterCompositor`](https://github.com/flutter/engine/blob/b2a9ce88a19e46ba1725c83165ed972b1c4fa8a3/shell/platform/embedder/embedder.h#L2161-L2175) and [`EmbedderExternalView`](https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder_external_view.h)). Windows on the "good" commit renders to a single root surface.

The "bad" and "good" Windows commits are difficult to compare as their implementations are very different. However, the Linux and "bad" Windows implementations are quite similar and are comparable.

## Comparison of Linux and "bad" Windows traces

Traces under `OpsTask::onPrepare`:

Linux | Windows
-- | --
FillRectOp<br>FillRectOp<br>CircularRRectOp | FillRectOp<br>FillRectOp<br>CircularRRectOp 

Traces between `OpsTask::onPrepare` and `OpsTask::onExecute`

<table>
  <tbody>
    <tr>
      <th>Linux</th>
      <th>Windows</th>
    </tr>
    <tr>
      <td>
        <ol>
          <li>Disable(0x0B71)</li>
          <li>DepthMask(0)</li>
          <li>FrontFace(0x0901)</li>
          <li>Disable(0x8037)</li>
          <li>Enable(0x8642)</li>
          <li>LineWidth(1)</li>
          <li>Enable(0x809D)</li>
          <li>PixelStorei(0x0CF2, 0)</li>
          <li>BindBuffer(bufferState->fGLTarget, glBuffer->bufferID())</li>
          <li>InvalidateBufferData(bufferID)</li>
          <li>BufferSubData(target, offset, size, src)</li>
          <li>BindVertexArray(arrayID)</li>
          <li>InvalidateBufferData(bufferID)</li>
          <li>BufferSubData(target, offset, size, src)</li>
        </ol>
      </td>
      <td>
        <ol>
          <li>Disable(0x0B71)</li>
          <li>DepthMask(0)</li>
          <li>Disable(0x0B44)</li>
          <li>FrontFace(0x0901)</li>
          <li>LineWidth(1)</li>
          <li>Disable(0x0BD0)</li>
          <li>PixelStorei(0x0CF2, 0)</li>
          <li>PixelStorei(0x0D02, 0)</li>
          <li>PixelStorei(0x93A4, 0)</li>
          <li>BindBuffer(bufferState->fGLTarget, glBuffer->bufferID())</li>
          <li>BufferData(target, bufferSize, nullptr, usage)</li>
          <li>BufferSubData(target, offset, size, src)</li>
          <li>BindVertexArray(arrayID)</li>
          <li>BindBuffer(bufferState->fGLTarget, glBuffer->bufferID())</li>
          <li>BufferData(target, bufferSize, nullptr, usage)</li>
          <li>BufferSubData(target, offset, size, src)</li>
        </ol>
      </td>
    </tr>
  </tbody>
</table>

**Comment by loic-sharma** [comment]
I have a smaller minimal repro: a clipped circle stacked on top of a faded background:

<details>
<summary>Minimal source code...</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // This is necessary to reproduce:
    return Container(
      color: Colors.white,
      child: const Directionality(
        textDirection: TextDirection.ltr,
        child: BlueCircle(),
      ),
    );

    // Switching to this fixes the issue:
    // return const MaterialApp(
    //   home: Scaffold(
    //     body: BlueCircle(),
    //   ),
    // );
  }
}

class BlueCircle extends StatelessWidget {
  const BlueCircle({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        const Opacity(
          opacity: 0.3,
          child: SizedBox.expand(
            child: DecoratedBox(
              decoration: BoxDecoration(color: Colors.black),
            ),
          ),
        ),

        SizedBox.expand(
          child: ClipOval(
            clipper: const _CircularRevealClipper(),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Colors.blue,
                // Removing this line fixes the app.
                borderRadius: BorderRadius.circular(16.0),
              ),
              child: const SizedBox(height: 256.0),
            ),
          ),
        ),
      ],
    );
  }
}

class _CircularRevealClipper extends CustomClipper<Rect> {
  const _CircularRevealClipper();

  @override
  Rect getClip(Size size) {
    return Rect.fromCircle(
      center: Offset.zero,
      radius: 500,
    );
  }

  @override
  bool shouldReclip(CustomClipper<Rect> oldClipper) => true;
}
```

</details>

I updated the Windows compositor to clear the window surface to red before blitting the backing store's framebuffer. If blitting works as expected, the red should not be visible as the entire surface should have been blitted over. However, red color remains:

![image](https://github.com/flutter/flutter/assets/737941/4395155a-b7a5-43af-bcc7-93b26ac8392c)

This indicates the blitting is not actually replacing the entirety of the window surface.

<details>
<summary>Patch to clear the window surface to red before blitting...</summary>

Apply this patch on https://github.com/flutter/engine/commit/00d7d23fb5b97fd71f28a53ab4dcc9493ec585a7:

```diff
diff --git a/shell/platform/windows/compositor_opengl.cc b/shell/platform/windows/compositor_opengl.cc
index 6da274b993..c19cab4af1 100644
--- a/shell/platform/windows/compositor_opengl.cc
+++ b/shell/platform/windows/compositor_opengl.cc
@@ -132,6 +132,10 @@ bool CompositorOpenGL::Present(const FlutterLayer** layers,
     return false;
   }

+  gl_->BindFramebuffer(GL_DRAW_FRAMEBUFFER, kWindowFrameBufferId);
+  gl_->ClearColor(1.0f, 0.0f, 0.0f, 0.0f);
+  gl_->Clear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
+
   auto source_id = layers[0]->backing_store->open_gl.framebuffer.name;
   gl_->BindFramebuffer(GL_READ_FRAMEBUFFER, source_id);
   gl_->BindFramebuffer(GL_DRAW_FRAMEBUFFER, kWindowFrameBufferId);
```

</details>


If I clear the window surface with red before blitting the framebuffer to the window

**Comment by loic-sharma** [comment]
# ANGLE bug report

I believe Flutter Windows is affected by what appears to be a bug in ANGLE's `glBlitFramebuffer` implementation.

### Example app
Here is a Flutter app that draws a rounded rectangle with a circular clip on top of a faded background:

<details>
<summary>Source code...</summary>

This is broken on Flutter commit [`b417fb828b332b0a4b0c80b742d86aa922de2649`](https://github.com/flutter/flutter/commit/b417fb828b332b0a4b0c80b742d86aa922de2649).
This works on Flutter commit [`9c2a7560096223090d38bbd5b4c46760be396bc1`](https://github.com/flutter/flutter/commit/9c2a7560096223090d38bbd5b4c46760be396bc1).

```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Pump frames non-stop. This isn't necessary to repro.
  WidgetsBinding.instance.addPersistentFrameCallback((_) {
    WidgetsBinding.instance.scheduleFrame();
  });

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // This is necessary to reproduce:
    return Container(
      color: Colors.white,
      child: const Directionality(
        textDirection: TextDirection.ltr,
        child: BlueCircle(),
      ),
    );
  }
}

class BlueCircle extends StatelessWidget {
  const BlueCircle({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        const Opacity(
          opacity: 0.3,
          child: SizedBox.expand(
            child: DecoratedBox(
              decoration: BoxDecoration(color: Colors.black),
            ),
          ),
        ),

        SizedBox.expand(
          child: ClipOval(
            clipper: const _CircularRevealClipper(),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Colors.blue,
                // Removing this line fixes the app.
                borderRadius: BorderRadius.circular(16.0),
              ),
              child: const SizedBox(height: 256.0),
            ),
          ),
        ),
      ],
    );
  }
}

class _CircularRevealClipper extends CustomClipper<Rect> {
  const _CircularRevealClipper();

  @override
  Rect getClip(Size size) {
    return Rect.fromCircle(
      center: Offset.zero,
      radius: 500,
    );
  }

  @override
  bool shouldReclip(CustomClipper<Rect> oldClipper) => true;
}

```

</details>


TODO: EXECUTABLE ZIP HERE

Here is the expected output:

![image](https://github.com/flutter/flutter/assets/737941/cb1feb39-3214-47a4-95f1-6af42e5f1760)

Here is the actual output of Flutter Windows:

![image](https://github.com/flutter/flutter/assets/737941/e0ddfbaf-a317-418c-b803-395d4678b291)

TODO
### Analysis
Flutter Windows uses Skia to render to an OpenGL framebuffer. Flutter Windows then blits this framebuffer to the window's surface. The blit updates the entire window surface (the framebuffer and window surface have the same size).

Using RenderDoc, we see that the blit's input texture is expected but the output texture is unexpected.

TODO: RenderDoc frame capture.
TODO: Skia trace that can be viewed using `chrome://tracing`. This does not include the `glBlitOperation`.
### Clear test
It appears that the blit is *not* updating the entire window surface. To test this hypothesis, I added a step to clear the window's surface to a red color immediately before blitting the framebuffer. Since the blit should update the entire window surface, no red color should be visible. However, the red color is visible:

TODO: Screen shot.
TODO: RenderDoc frame capture.
### Debugging information
Affected Flutter version: TODO
ANGLE version for affected Flutter version: TODO

**Comment by loic-sharma** [comment]
Fixed by https://github.com/flutter/engine/pull/49726
