### ISSUE TITLE
Repurpose `dev/integration_tests/external_ui`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#142006]
/cc @jonahwilliams @johnmccutchan @bdero 

## Background

Unbeknown to me, we have an e2e test in the framework covering `surface_texture` external textures:

1. `.ci.yaml`: https://github.com/flutter/flutter/blob/e593cdfb80975fb6a41dff21e3f4f774f7e68723/.ci.yaml#L2171
2. `.dart` runner: https://github.com/flutter/flutter/blob/e593cdfb80975fb6a41dff21e3f4f774f7e68723/dev/devicelab/lib/tasks/integration_tests.dart#L43
3. (actual test) https://github.com/flutter/flutter/blob/e593cdfb80975fb6a41dff21e3f4f774f7e68723/dev/integration_tests/external_ui/test_driver/main_test.dart

If working properly, it produces a picture like this:

![image](https://github.com/flutter/flutter/assets/168174/3a1b7b06-cd22-4c27-a521-fabd83dcaa28)

... however, it doesn't do any pixel validation, and only runs on the Skia backend.

---

## Tasks

- [ ] Add a pixel-validation test, likely with two filled rectangles one-inside another
- [ ] Add a resizing platform view test (https://github.com/flutter/engine/pull/50144)
- [ ] Run Android in both Skia (current) and Impeller+OpenGLES (perhaps later in Vulkan)
- [ ] Rename `external_ui` to `external_texture_integration_test` to disambiguate
- [ ] Link to this test in the `shell/embedder/android/README.md`

**Comment by matanlurey** [comment]
I've decided to just not touch this for the time being.
