### ISSUE TITLE
[Impeller] ☂️ Path drawing performance needs significant improvement.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#143077]
Some members of the Impeller team have done some performance benchmarking comparing Impeller vs Skia (@jonahwilliams and @dnfield ?) and overall feel that path handling performance in Impeller is not acceptable for release on Android.

Phrases like "needs significant improvement" and "acceptable performance" are intentionally vague. The purpose of this umbrella bug is to disambiguate by collecting evidence together and linking to other specific tasks which are theorized to solve trouble cases.
So the first order of business is to collect this evidence together (which may expand or contract over time). And once we identify a collection of trouble cases, we can hammer down these trouble cases and at least track overall progress.

Trouble cases may or may not involve tessellation performance. For example, if we remove generic tessellation altogether by employing stencil-then-cover and our trouble cases aren't improved enough to release on Android, we may need to come up with non-tessellation solutions to get us over the line.

----

Impeller having "acceptable" performance means that the overall perceived experience of switching from Skia to Impeller should be good for **common usage**. Unrealistic/esoteric performance comparisons are **not** useful blockers for release on Android (unless we have a reason to believe they inform realistic usage -- and are esoteric for the purpose of isolating the problem and reducing noise, like in the benchmarks, for example).

## Documented trouble cases
To make judgements about how Impeller's path rendering shapes up, it's important to:
1. Compare the overall experience of using Impeller with Skia (ideally by collecting side-by-side videos from actual target devices).
2. Collect artifacts that inform us as to _why_ things are slow. Especially cases where the experience of using Impeller is visibly worse on devices with decent hardware. However, if Impeller spends significantly more energy churning frames than Skia, then that's going to adversely affect battery life on high end phones and result in us dropping frames on low end phones.

Unchecked box = untriaged/missing investigation.

- [x] https://github.com/flutter/flutter/issues/141961
    - [x] Impeller<->Skia comparison videos: https://github.com/flutter/flutter/issues/143077#issuecomment-1942978286
    - [x] Analysis / Impeller CPU flamegraph: https://github.com/flutter/flutter/issues/143077#issuecomment-1942978286
- [x] static_path_tessellation_perf__timeline_summary / dynamic_path_tessellation_perf__timeline_summary
    - [x] Impeller<->Skia comparison videos: https://github.com/flutter/flutter/issues/143077#issuecomment-1935345500
    - [x] Analysis / Impeller CPU flamegraph: https://github.com/flutter/flutter/issues/143077#issuecomment-1935345500
- [ ] Painting app: https://github.com/Mairramer/impeller_example/tree/master
    - [ ] Impeller<->Skia comparison videos: `None`
    - [ ] Analysis / Impeller CPU flamegraph: `None`
- [ ] customer:money -- General sense is that Impeller is slower (?).
    - [ ] Impeller<->Skia comparison videos: `None`
    - [ ] Analysis: We have [a document](https://docs.google.com/document/d/1n7im-6EaeRYlerbuBtJayg2zWEDjgVMXuJx7elpT0JU/edit?tab=t.0#heading=h.ybl0gfg8pr0r) which links to a trace that is no longer available and does not document how much time is being spent on tessellation.
- [ ] https://github.com/flutter/flutter/issues/134432
    - [ ] Impeller<->Skia comparison videos: Videos of Impeller, but no comparison to Skia.
    - [x] Analysis / Impeller CPU flamegraph: 67% `FillPathGeometry::GetPositionBuffer` -> 45% `Tessellator::Tessellate` + 20% `Path::CreatePolyline` https://github.com/flutter/flutter/issues/134432#issuecomment-1721850172

**Comment by jonahwilliams** [comment]
Its not just convex and complex paths. If you have multiple contours we will need to use libtess as we need to account for the winding order + fill mode.

**Comment by bdero** [comment]
Thanks, I'll keep the problem statement more generic and list these things.

**Comment by jonahwilliams** [comment]
* https://github.com/Mairramer/impeller_example/tree/master 

- This app is doing the drawing, adding a larger and larger contours.

* https://github.com/flutter/flutter/issues/141961

- Big complex lottie, might benefit from caching?

**Comment by jonahwilliams** [comment]
Disable raster cache:

https://github.com/flutter/engine/blob/6807342305e48826293d9152ba25d18cb09ee1a3/shell/common/rasterizer.cc#L726-L730

**Comment by zanderso** [comment]
https://github.com/zanderso/spendy_rasters

**Comment by bdero** [comment]
@jonahwilliams I recall you mentioned a painting application issue earlier where things start to slow down much faster than with Skia. It sounded like it was user reported/a bug filed for that already?

**Comment by bdero** [comment]
I recall seeing something like that too but I can't seem to dig it up.

**Comment by jonahwilliams** [comment]
That one is in the first link I posted.

**Comment by bdero** [comment]
@jonahwilliams Gotcha. Was there some analysis already done on it to determine Impeller seemed worse than Skia? If not I'll take a look at this one too.

**Comment by bdero** [comment]
## Macrobenchmarks `Path Tessellation`, Pixel 7 pro

Overall feel:
* Impeller is always significantly better than Skia in the animated/redraw case.
* With the raster cache turned off, Skia is significantly better than Impeller for the static case.
* With the raster cache turned on, Skia's performance is significantly degraded to the point of being _worse_ than Impeller in all cases for the first N frames. After 30 or so frames, Skia recovers performance for the static case.
* As expected, Impeller performs the same performance regardless of the case.

From this, the only thing I see that gives me pause here is the non-animated case _after_ the raster cache for Skia has warmed up, so I'm going to profile this specifically (although again I'd expect the behavior to basically be the same in both cases for Impeller). 

Skia (no raster cache):

https://github.com/flutter/flutter/assets/919017/3be25ff0-3e65-4275-8868-c436916ebee9

Skia (with raster cache):

https://github.com/flutter/flutter/assets/919017/7eb6f8cf-2b21-4595-9734-e1caf89fa06a

Impeller Vulkan:

https://github.com/flutter/flutter/assets/919017/ce409e6e-33fd-441c-8102-af87ad9a923d

**Comment by jonahwilliams** [comment]
Another one: https://github.com/flutter/flutter/issues/134432

**Comment by bdero** [comment]
Thanks, added that to the list. It has a useful profile capture: 67% `FillPathGeometry::GetPositionBuffer` -> 45% `Tessellator::Tessellate` + 20% `Path::CreatePolyline`.

I went through the rest of the items and pulled out Skia/Impeller comparisons and analysis. For the customer:money doc, there are Impeller/Skia comparisons for perfgate benchmarks (I believe of previously identified trouble scenarios, like screen transitions?), but I'm having trouble interpreting these in terms of the impact on the user experience. The analysis mentions a high level CPU trace that is no longer available, but I suspect there was useful timing information there that could allow us to infer how much time was being taken by tessellation at some point.
Ideally we can run the app and compare them side-by-side to show the obvious trouble spots, and then profile those trouble spots (I realize that may be easier said than done though, and we have plenty of other things to collect details about in the meantime).

**Comment by bdero** [comment]
## Macrobenchmarks `Path Tessellation`, Pixel 7 pro (PROFILE)

I accidentally took [the previous videos](https://github.com/flutter/flutter/issues/143077#issuecomment-1932814093) in debug mode. Here's a retake of the videos in profile mode along with the frame graph. We stay under budget with Impeller here, so it looks smooth all around. Skia falls over for the dynamic/animated case (possibly because we're holding Skia wrong, of course), but has less expensive frames on average in the static/non animating case.

### Impeller Vulkan:

https://github.com/flutter/flutter/assets/919017/c6d39398-d31d-4be3-934e-49c6ad3744a0

### Skia (with raster cache):

Average out of budget.

https://github.com/flutter/flutter/assets/919017/b8cdf958-f63a-4c90-bee4-b7fcb7606add

## Flame graphs during animation

With Impeller enabled, -- around 20% being spent generating polylines. Skia is spending >90% of all raster time

### Impeller Vulkan:

Average within budget.
* ~80% of the raster time is spent on path-related activity
    * ~50% of the raster time is spent churning in libtess
    * ~15% of the raster time is spent generating polylines

![image](https://github.com/flutter/flutter/assets/919017/e7e4dda0-d62f-4bc1-8216-babfa5fdf067)

### Skia (with raster cache):
* 90+% of the raster time is spent turning paths into rasterized distance fields on the CPU (which may very well be caused by us holding Skia wrong in one way or another).

![image](https://github.com/flutter/flutter/assets/919017/8d115b41-9bbd-4cf6-bac3-5d6b8bc6897d)

## Flame graphs while scrolling (but not animating)

### Impeller Vulkan:

Average within budget.

![image](https://github.com/flutter/flutter/assets/919017/6c3dfd7e-8b77-42b4-a14c-01a6dd6261ad)

### Skia (with raster cache):

Average within budget, much more so than Impeller.

![image](https://github.com/flutter/flutter/assets/919017/7b086ea4-ee0c-4e6f-a9c0-68b6a49bd2ca)

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/50496 <- I couldn't get this to show anything, but I think this is how @dnfield tried to get Skia to use the stencil buffer some time back. We reverted it due to it regressing performance on an internal customer's benchmarks.

**Comment by dnfield** [comment]
It also didn't show improvements in any benchmarks we tracked. It's quite possible it needs some further attention.

Skia has several path rasterization/rendering strategies. We seem to end up in the software one frequently. It has many carveouts for particular GPU models, and many configuration points where it might decide not to use one method over another.

**Comment by jonahwilliams** [comment]
Any number of ways that we use Skia could be conflictng, whether its the lack of MSAA, stencil buffer, raster cache, et cetera. "Fixing Skia" is not a trivial undertaking and if we were attempting to do it I'd want at least a month of time set aside.

**Comment by zanderso** [comment]
Yeah, "fixing Skia" is not a goal. Sorry for the noise!

**Comment by gaaclarke** [comment]
I pulled on the thread of changing the memory allocation methods of libTess to squeeze out a bit more performance.  That flopped though.  My notes are in https://discord.com/channels/608014603317936148/1173336353187041380/1205675882925129789

The results where I didn't see a big opportunity in tweaking the memory allocation strategy.  I was also measuring on iOS where the memory is really fast too though.

**Comment by bdero** [comment]
Impeller's rendering behavior for novel paths with libtess is already much faster than Skia's SDF approach in the `Path Tessellation` macrobenchmark (again, not to say Skia is bad -- rasterizing SDFs may be a smart solution given environmental constraints).

The main reason we seem to be doing worse than Skia for the static benchmark is that Skia caches artifacts derived from the path (the SDF) whereas Impeller doesn't. In my captures, allocation within libtess only accounts for ~3% of overall raster time, but in order to at least match Skia's CPU expense in its cached state, Impeller would need to hack off ~20-30%, which is not going to be possible unless we stop using libtess in those frames anyway.

So my unspoken analysis surrounding the [above captures](https://github.com/flutter/flutter/issues/143077#issuecomment-1935345500) is:

This is actually good news: The captured behavior of the `Path Tessellation` macrobenchmark would suggest the situation with path drawing performance may not actually be so dire, since we have an obvious and easy solution on the table to not regress performance for users switching from Skia to Impeller. However, we obviously can't make that determination without analyzing more trouble cases, which may shake out differently.

**Comment by knopp** [comment]
I'm wondering if Skia use different GPU tessellation on Metal? On iOS the macro benchmark tessellation was always faster on Skia, with the animated version performing same as static version.

Also, just a heads-up, I do remember the macrobenchmark being run with different CPU clock on impeller and skia (likely due to impeller requiring more work), which did make the comparison bit problematic.

**Comment by bdero** [comment]
> I'm wondering if Skia use different GPU tessellation on Metal?

Without having looked, my guess would be yes. With Metal we have less opportunities to set Skia off on the wrong foot. For example, no need to rely on us to set up a transient stencil for the root framebuffer.

> On iOS the macro benchmark tessellation was always faster on Skia, with the animated version performing same as static version.

Good to know! Right now I'm working on landing StC support, so comparing first frame tessellation on iOS with Skia will be a must for that.

> Also, just a heads-up, I do remember the macrobenchmark being run with different CPU clock on impeller and skia (likely due to impeller requiring more work), which did make the comparison bit problematic.

Know any good tricks for getting a clock readouts for the core churning on the raster thread? This would be nice to incorporate.

**Comment by bdero** [comment]
## [Lottie animation](https://github.com/flutter/flutter/issues/141961), Pixel 7 pro (PROFILE)

Skia is clearly the winner here, although both backends are dropping frames due to the raster workload.

### Impeller Vulkan

https://github.com/flutter/flutter/assets/919017/789f1c57-a267-48f6-93d5-5441c6d4ff64

### Skia (with raster cache)

https://github.com/flutter/flutter/assets/919017/bb4e5f3c-bfd7-45dc-ad95-40232f00b289

## Flame graphs

Skia is spending most of its time generating and uploading antialiased masks on the CPU. It's unclear how much caching is going on here.

### Impeller Vulkan

<img width="1004" alt="impeller-lottie" src="https://github.com/flutter/flutter/assets/919017/3c65028d-02b4-4746-be8f-a01c80d54a3b">

### Skia (with raster cache)

<img width="1445" alt="skia-lottie" src="https://github.com/flutter/flutter/assets/919017/2c3def67-14f6-4505-a2d0-15032354db49">

**Comment by jonahwilliams** [comment]
Another issue to track closing : https://github.com/flutter/flutter/issues/135458

**Comment by bdero** [comment]
## [Rive animation](https://github.com/flutter/flutter/issues/134432), iPhone 12 mini (PROFILE)

76% reduction in raster time with StC.

### Skia (with raster cache)
5.1 ms/frame

https://github.com/flutter/flutter/assets/919017/e9be30bf-d86d-49b8-8cc2-56b1a49d2fb9

### Impeller (before StC)
43.7 ms/frame

https://github.com/flutter/flutter/assets/919017/10a01a5e-c456-4ca0-b951-2b38187ae815

### Impeller (after StC)
10.6 ms/frame

https://github.com/flutter/flutter/assets/919017/68e417ed-f12e-40a7-ba05-2ef6c6f9dd21

**Comment by chinmaygarde** [comment]
Improvement to both tessellation (via StC) and polyline generation have landed.

**Comment by jonahwilliams** [comment]
This should all be available in 3.22 which is the current beta and very soon to be stable.
