### ISSUE TITLE
_DefaultTabControllerState should dispose TabContoller instances.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#144910]
Re-land the revert https://github.com/flutter/flutter/pull/144579

- [x] Test cover functionality that was broken by dispose: https://github.com/flutter/flutter/pull/144627
- [x] Instrument TabController: https://github.com/flutter/flutter/pull/144912
- [ ] Re-land leak cleanup: https://github.com/flutter/flutter/pull/146745
