### ISSUE TITLE
Device lab Flight School move (try pool)

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#145416]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Move `try` pool bots to new Flight School lab:

**Phase 1**:

- [x] flutter-devicelab-linux-26
- [x] flutter-devicelab-linux-53
- [x] flutter-devicelab-mac-1
- [x] flutter-devicelab-mac-12
- [x] flutter-devicelab-mac-14

For each above machines:

Connect to network `switch-1`
Verify swarming bot is up and running
Verify that builds have run successfully after move
Create ticket to update hostadmin entry to point to new VLAN config (flightschool_1) (Similar to ticket t/225374063)
Verify DNS is correct and host is ssh'able
Verify salt states can be applied correctly

**Phase 2**:

Once phase 1 is completed successfully, move the remaining following machines:

- [ ] flutter-devicelab-mac-17
- [ ] flutter-devicelab-mac-19
- [ ] flutter-devicelab-mac-38
- [ ] flutter-devicelab-mac-45
- [ ] flutter-devicelab-mac-46

For each above machines:

Connect to network `switch-1`
Verify swarming bot is up and running
Verify that builds have run successfully after move
Create ticket to update hostadmin entry to point to new VLAN config (flightschool_1) (Similar to ticket t/225374063)
Verify DNS is correct and host is ssh'able
Verify salt states can be applied correctly

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
ticket for VLAN config for Phase 1 has been opened: t/225588176

**Comment by kentnguyen99** [comment]
Waiting for AC in the new lab going online and DNS entries update then will move Phase 1 Bots to new lab.

**Comment by yusuf-goog** [comment]
@kentnguyen99 DNS entry flutter-devicelab-linux-53.mtv.corp.google.com should be complete.

Note: it is expected the remote ssh to the updated machines will not work till they are physically moved to flight school.

Please perform the following tasks to see the effect of the change before they are physically moved:

- [ ] reboot the machine
- [ ] perform salt state apply
- [ ] verify that the swarming server is still up and running

**Comment by yusuf-goog** [comment]
As expected, remote ssh to flutter-devicelab-linux-53.mtv.corp.google.com  is now down due to the DNS change.

**Comment by kentnguyen99** [comment]
All check and ready to go.

**Comment by kentnguyen99** [comment]
linux-53 has been moved to Flight School lab. Machine is up and running, I can login remotely from my end; However, it failed command "salt-call state.apply" due could not resolved DNS lookup.
flutter@flutter-devicelab-linux-53:~$ sudo salt-call state.apply
[sudo] password for flutter: 
[ERROR   ] DNS lookup or connection check of 'salt-flutter.endpoints.fuchsia-infra.cloud.goog' failed.
[ERROR   ] Master hostname: 'salt-flutter.endpoints.fuchsia-infra.cloud.goog' not found or not responsive. Retrying in 30 seconds

**Comment by yusuf-goog** [comment]
Opened t/225700129 to track the DNS entry issues. Potentially missing DNS server entries in the new VLANs.

**Comment by yusuf-goog** [comment]
linux-53 is working, states applied fine, and build ran and succeeded.

**Comment by yusuf-goog** [comment]
lab temperature has been fixed and is cooling currently. Please resume with Phase 1 move of machines.

**Comment by kentnguyen99** [comment]
Phase 1 machines have been moved to Flight School, all machines online and ready for service.

**Comment by yusuf-goog** [comment]
opened t/225882455 for phase 2 dns changes.

**Comment by yusuf-goog** [comment]
Purchased some network cables, and phone cables (usb and lightning) for the new lab.

**Comment by yusuf-goog** [comment]
VLAN changes have been completed (t/225882455)

**Comment by yusuf-goog** [comment]
Phase 2 machines have been moved and the bots are up, but remote ssh is not working. Ticket for the VLAN changes has been re-opened to look at the issue.

**Comment by yusuf-goog** [comment]
hostadmin entries have been updated.
