### ISSUE TITLE
Final Devicelab Move tracker from Greenhouse to Flight School

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#145852]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Tracking issue for the lab move:

- [x] Door access to the lab
- [x] Run smoke test https://github.com/flutter/flutter/issues/144720
- [x] Fixes to VLAN dns nameserver t/225700129
- [x] Fix for Lab cooling issue t/225746150
- [x] Emergency battery disposal kit delivered to lab (t/225592237)
- [x] Get move blackout dates : APR 29 to MAY 10 (https://github.com/flutter/flutter/issues/145852#issuecomment-2024053749)
- [x] Migrate try pool bots https://github.com/flutter/flutter/issues/145416
- [x] Migrate wave 0 of staging and prod devices (#146242)
- [x] Migrate wave 1 of staging and prod devices (#146770)
- [x] Migrate wave 2 of staging and prod devices (#146924)
- [x] Migrate wave 3 of staging and prod devices (#147074)
- [x] Move inventory and supplies from Greenhouse and desk locations to Flight school

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
Try pool move tracker: https://github.com/flutter/flutter/issues/145416

**Comment by yusuf-goog** [comment]
VLAN DNS issue tracker: t/225700129 (update: resolved)

**Comment by yusuf-goog** [comment]
@itsjustkevin Please add the black out dates for moving the machines here.

**Comment by yusuf-goog** [comment]
ticket for cooling issue: t/225746150

**Comment by itsjustkevin** [comment]
Please avoid 29 April - 10 May.

**Comment by yusuf-goog** [comment]
Requested priority bump for cooling ticket.
