### ISSUE TITLE
Greenhouse to Flight School device move staging and prod Phase 1

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#146770]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Move staging and prod pool bots to new Flight School lab:

**Phase 1**:

_staging_

flutter-devicelab-mac-34
flutter-win-5
flutter-devicelab-mac-11
flutter-devicelab-mac-5
flutter-win-7
flutter-win-8
flutter-win-17
flutter-devicelab-linux-54
flutter-devicelab-linux-55
flutter-devicelab-linux-56
flutter-devicelab-linux-57
flutter-devicelab-linux-18
flutter-devicelab-linux-27

_prod_

flutter-devicelab-linux-4
flutter-devicelab-linux-5
flutter-devicelab-mac-21
flutter-devicelab-mac-22
flutter-win-1
flutter-devicelab-mac-6
flutter-devicelab-mac-7
flutter-devicelab-mac-8
flutter-devicelab-mac-9
flutter-win-10
flutter-win-11
flutter-devicelab-linux-12
flutter-devicelab-linux-19
flutter-devicelab-linux-20
flutter-devicelab-linux-37
flutter-devicelab-linux-22
flutter-devicelab-linux-16
flutter-devicelab-linux-31

For each above machines:

- [x] Create ticket to update hostadmin entry to point to new VLAN config (flightschool_2) (Similar to ticket t/225373886)
- [x] Connect to any network switches 2-5
- [x] Verify swarming bot is up and running
- [x] Verify that builds have run successfully after move
- [x] Verify DNS is correct and host is ssh'able
- [x] Verify salt states can be applied correctly

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
Created ticket to update VLAN entries: t/226075785

**Comment by yusuf-goog** [comment]
all bots are up and processing builds.
spot checks show remote ssh access is working.
spot checks of salt states are working fine.
