### ISSUE TITLE
☂️ Tracking issue for any infra or test failures with Xcode 16 and iOS 18 Simulators

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148898]
### flutter/flutter

- [x] https://github.com/flutter/flutter/issues/151553
  - [x] https://github.com/flutter/flutter/pull/153116
- [x] https://github.com/flutter/flutter/issues/152983 
  - This will not require a cherry-pick since the PR that caused it is only in master https://github.com/flutter/flutter/pull/152347
- [x] https://github.com/flutter/flutter/issues/164902

### flutter/packages

- [x] https://github.com/flutter/flutter/issues/150391
- [x] https://github.com/flutter/flutter/issues/150448
- [x] https://github.com/flutter/flutter/issues/150943
- [x] https://github.com/flutter/flutter/issues/151467
- [x] https://github.com/flutter/flutter/issues/150220
- [x] https://github.com/flutter/flutter/issues/152970
- [x] ~~https://github.com/flutter/flutter/issues/153578~~
  - Issue also exists on macOS 13 and Xcode 15, so not specific to Xcode 16, and therefore not a blocker.
- [ ] https://github.com/flutter/flutter/issues/164632

### flutter/engine

- [x] https://github.com/flutter/flutter/issues/152990
  - This will not require a cherry-pick since the failing test only exists on main https://github.com/flutter/engine/pull/54119

## Infra Issues:

- [ ]

**Comment by vashworth** [comment]
Xcode 16 and iOS 18 have been merged.
