### ISSUE TITLE
Update .ci.yaml in flutter/flutter to use Xcode 16 and macOS 14

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148907]
Prerequisites

- [x] https://github.com/flutter/flutter/issues/148899
- [x] https://github.com/flutter/flutter/issues/148888 (assuming Xcode 16 requires macOS 14.5)
  - If Xcode 16 requires a higher macOS version, bots will need to be upgraded to new required version before doing 
- [x] https://github.com/flutter/flutter/issues/148892 (assuming Xcode 16 requires macOS 14.5)
  - If Xcode 16 requires a higher macOS version, bots will need to be upgraded to new required version before doing 
- [x] Ensure no open issues in https://github.com/flutter/flutter/issues/148898 under flutter/flutter

--- 

https://github.com/flutter/flutter/blob/master/.ci.yaml
```diff
$flutter/osx_sdk : >-
        {
-          "sdk_version": "15a240d"
+          "sdk_version": "[insert new CIPD case-sensitive Xcode build version]"
        }
        
- os: Mac-13|Mac-14
+ os: Mac-14

- ["device_os=iOS-17","os=Mac-13|Mac-14", "cpu=x86"]
+ ["device_os=iOS-17","os=Mac-14", "cpu=x86"]
```
