### ISSUE TITLE
Update flutter/engine to use Xcode 16, iOS 18 Simulator, and macOS 14

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148957]
Prerequisites

- [x] https://github.com/flutter/flutter/issues/148906
- [x] https://github.com/flutter/flutter/issues/148893 (assuming Xcode 16 requires macOS 14.5)
  - If Xcode 16 requires a higher macOS version, bots will need to be upgraded to new required version before doing 
- [x] https://github.com/flutter/flutter/issues/148892 (assuming Xcode 16 requires macOS 14.5)
  - If Xcode 16 requires a higher macOS version, bots will need to be upgraded to new required version before doing 
- [x] Ensure no open issues in https://github.com/flutter/flutter/issues/148898 under flutter/flutter

--- 

https://github.com/flutter/engine/blob/main/.ci.yaml

```diff
$flutter/osx_sdk : >-
        {
-          "sdk_version": "15a240d"
+          "sdk_version": "[insert new CIPD case-sensitive Xcode build version]"
        }
        
- os: Mac-13|Mac-14
+ os: Mac-14
```

https://github.com/flutter/engine/blob/main/ci/builders/local_engine.json
https://github.com/flutter/engine/blob/main/ci/builders/mac_android_aot_engine.json
https://github.com/flutter/engine/blob/main/ci/builders/mac_host_engine.json
https://github.com/flutter/engine/blob/main/ci/builders/mac_ios_engine.json
https://github.com/flutter/engine/blob/main/ci/builders/mac_unopt_debug_no_rbe.json
```diff
$flutter/osx_sdk : >-
        {
-          "sdk_version": "15a240d"
+          "sdk_version": "[insert new CIPD case-sensitive Xcode build version]"
        }
        
- os=Mac-13|Mac-14
+ os=Mac-14
```

https://github.com/flutter/engine/blob/main/ci/builders/mac_unopt.json
```diff
$flutter/osx_sdk : >-
        {
          "runtime_versions": [
-               "ios-17-0_15a240d"
+               "ios-18-0_[insert new CIPD case-sensitive Xcode build version]"
          ],
-          "sdk_version": "15a240d"
+          "sdk_version": "[insert new CIPD case-sensitive Xcode build version]"
        }
        
- os=Mac-13|Mac-14
+ os=Mac-14
```

https://github.com/flutter/engine/blob/main/testing/scenario_app/run_ios_tests.sh
```diff
- readonly OS_RUNTIME=com.apple.CoreSimulator.SimRuntime.iOS-17-0
- readonly OS="17.0"
+ readonly OS_RUNTIME=com.apple.CoreSimulator.SimRuntime.iOS-18-0
+ readonly OS="18.0"
```

In addition, golden files will need to be updated. See https://github.com/flutter/engine/pull/49833 as example

**Comment by vashworth** [comment]
Engine has been moved in flutter/flutter. Closing.
