### ISSUE TITLE
CP Xcode 16 and iOS 18 Simulator fixes for beta and stable

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148959]
## Prerequisites 

- [ ] https://github.com/flutter/flutter/issues/148907 has landed for a week or 2
- [ ] https://github.com/flutter/flutter/issues/148956 has landed for a week or 2
- [ ] https://github.com/flutter/flutter/issues/148957 has landed for a week or 2
- [ ] Ensure all issues are fixed in https://github.com/flutter/flutter/issues/148898

## Instructions

CP any fixes made to resolve issues in https://github.com/flutter/flutter/issues/148898. This may include recipe fixes.

**Comment by vashworth** [comment]
None required.
