### ISSUE TITLE
☂️ Support Android 15 changes to edge-to-edge mode

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#150374]
This is an umbrella issue for all of the ordered steps we need to take to support [the changes coming to edge-to-edge mode](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge) with Android 35.

- [x] **When we can:** Determine how Flutter apps behave targeting API 35 (meaning we just need to verify none of our plans in the other issues are impacted unexpectedly when we test a Flutter app targeting API 35)
- [x] **When we can:** Build the engine against API 35 (https://github.com/flutter/flutter/issues/150215)
- [x] **Step 1:** Maintain the behavior of current Flutter system UI modes (https://github.com/flutter/flutter/issues/150216)
- [ ] **Step 2:** Develop migration documentation and migrate Flutter sample (https://github.com/flutter/website/issues/10755)
- [x] **Step 3:** Set edge-to-edge as the default mode (https://github.com/flutter/flutter/issues/86248)
- [x] **Step 4:** Update Flutter’s SystemUiMode documentation (https://github.com/flutter/flutter/issues/150367)

**Comment by camsim99** [comment]
We are pivoting to prioritizing adding golden tests (part of step 1), then moving on to steps 2 and 3 as disabling edge-to-edge by default in the Flutter engine has turned into a much more difficult task than expected.

**Comment by camsim99** [comment]
Marking this as P2 as all of the P1 items have been addressed.

All that's left is a nice to have--creating a guide for migrating for app from a different `SystemUiMode` to edge-to-edge.

**Comment by camsim99** [comment]
Going to close this as complete because there is nothing actionable here and https://github.com/flutter/website/issues/10755 can track the nice-to-have work.
