### ISSUE TITLE
💥 ☂️ Solution to fleet-wide Android emulator crashes on CI

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#153445]
Forked from https://github.com/flutter/flutter/issues/152769 as it's unrelated to my specific test.

As of 2024-08-14, we have systemic fleet-wide Android emulator crashes that appear unrelated with any _specific_ test:

- https://github.com/flutter/flutter/issues/153431
- https://github.com/flutter/flutter/issues/153424
- https://github.com/flutter/flutter/issues/152769
- https://github.com/flutter/flutter/issues/98417

In nearly every case, the following occurs (note that every test uses a slightly different setup, the logs are _not_ uniform):

1. The emulator [successfully starts][1] (as part of a CI task job)
2. The test, typically using `flutter drive ...` installs the test APK, and starts executing
3. An ambient print message appears in the console: `getIsolate: (-32000) Service connection disposed`
4. The test (driver script) ends (usually you'll see `adb: device offline` in the logs by this point) with a failure

Confusingly, these tests work run fine roughly 95% - 99% of the time.

[1]: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739758796938791985/+/u/start_avd/Start_Android_emulator__android_35_google_apis_x64.textpb_/raw_io.output_text

---

My plan this week is roughly the following:
- Try LED builds of the Android emulator try-jobs, trying to extract crash logs, twiddle scripts
- See what the memory usage of the emulator is locally (we have a max of 2gb right now)
- Meet with the maintainer of the Chromium Android emulator tools (we use) on GVC

/cc @reidbaker @zanderso @johnmccutchan @christopherfujino @chunhtai 

---

## TODOs

- [x] Consider removing [`--writable-system`](https://flutter.googlesource.com/recipes/+/63f9f99e249697beadecb298aa175ad60024951b/recipe_modules/android_virtual_device/api.py#153):

  ✅ https://flutter-review.googlesource.com/c/recipes/+/59180/1

   ```txt
   W 15:30:04.302    0.034s Main  Emulator will be slow to start, as "writable_system=True" but system snapshot not found.
    ```

- [x] Try meeting with the Chromium Android emulator team on any obvious next steps.

   ✅  Upgrading to the latest `avd_cipd_version`:
   https://github.com/flutter/flutter/pull/153520

- [x] Try getting a copy of the `emu-crash.db` log entries, if any.
  
  ❌ **Did not result in anything**.

  During [emulator startup](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739596108227442705/+/u/start_avd/Start_Android_emulator__android_35_google_apis_x64.textpb_/raw_io.output_text), the console reads:

  ```txt
  INFO    | Storing crashdata in: /tmp/android-unknown/emu-crash-34.2.14.db, detection is enabled for process: 124450
  ```

  I wrote a [small script](https://gist.github.com/matanlurey/a8fef8e910417c6347197e998b8c89b2) to try and scrape this directory when a test crashes, but it resulted in nothing:

  ```txt
  Could not read file: /tmp/android-unknown/emu-crash-34.2.14.db/settings.dat
  ```

  It's possible that nothing is being logged, the logs are actually elsewhere, but seems like a dead end for now.

- [x] Try running the same tests on Github Actions VM and see if I observe similar flakes:

    ✅  Ran overnight on a 15m cron, API v35 seems too unstable to use as non-bringup task:
    
    https://github.com/matanlurey/flutter-renegade-gha

- ~[ ] Try running a demo Android app (or even just the emulator itself) without any Flutter~
- ~[ ] Try SSHing into a bot and running steps manually to try and detect the crash~

**Comment by zanderso** [comment]
Also FYI @camsim99

**Comment by matanlurey** [comment]
One interesting note so far is this log message at the top of every Android emulator run:

```txt
W 15:30:04.302    0.034s Main  Emulator will be slow to start, as "writable_system=True" but system snapshot not found.
```

**Comment by reidbaker** [comment]
Related internal bugs https://b.corp.google.com/issues/326109113 https://b.corp.google.com/issues/344730009

**Comment by reidbaker** [comment]
Do we know the size of the vms that are hosting the emulators? 
According to android they can crash if there is less than 5gb of disk space. https://developer.android.com/studio/run/emulator-troubleshooting#disk-space

**Comment by zanderso** [comment]
These are running on `n1-standard-8` instances. https://cloud.google.com/compute/docs/general-purpose-machines#n1_machine_types. I'll try to find the config file for our pool and share the link internally to double check.

**Comment by matanlurey** [comment]
Didn't solve the flakiness issue, but got rid of an error message and sped up startup time a bit:

https://flutter-review.googlesource.com/c/recipes/+/59180/1

**Comment by reidbaker** [comment]
> These are running on `n1-standard-8` instances. https://cloud.google.com/compute/docs/general-purpose-machines#n1_machine_types. I'll try to find the config file for our pool and share the link internally to double check.

Based on what I read about those instances the space is measured in Terabytes so we are probably ok on disk space.

**Comment by johnmccutchan** [comment]
- Can we get the Android emulator configuration and create a local version for testing?

**Comment by zanderso** [comment]
> > These are running on `n1-standard-8` instances. https://cloud.google.com/compute/docs/general-purpose-machines#n1_machine_types. I'll try to find the config file for our pool and share the link internally to double check.
> 
> Based on what I read about those instances the space is measured in Terabytes so we are probably ok on disk space.

Found the config. Disks are 300 GB on the Linux VMs: https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/starlark/bots/flutter.star#161

**Comment by matanlurey** [comment]
Unfortunately the solution here is, at the moment, "don't use Android 35 on emulators".

We will revisit adding them about 1 quarter after the public release, and keep the tasks `bringup: true` for now.

**Comment by matanlurey** [comment]
This issue is now tracking adding `crashreport` access to our CI, and is no longer a high priority.
