### ISSUE TITLE
[iOS 18] Verify Flutter works with the new Eye Tracking feature

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#153567]
### Background

https://www.apple.com/newsroom/2024/05/apple-announces-new-accessibility-features-including-eye-tracking/

To enable, navigate to the **Settings** app > **Accessibility** > **Eye Tracking**.

### Work

Verify:

* [x] Tapping
    * [x] Counter app  
    * [x] `examples/api/lib/cupertino/checkbox/cupertino_checkbox.0.dart` 
    * [x] `examples/api/lib/cupertino/radio/cupertino_radio.0.dart` 
* [x] Gestures
    * [x] Pull to refresh: `examples/api/lib/cupertino/refresh/cupertino_sliver_refresh_control.0.dart` 
* [x] Scrolling
    * [x] `examples/api/lib/cupertino/scrollbar/cupertino_scrollbar.0.dart`
* [x] Text input
    * [x] `examples/api/lib/cupertino/text_field/cupertino_text_field.0.dart`

Problems:
* https://github.com/flutter/flutter/issues/153573

**Comment by sethladd** [comment]
Thank you for testing all these features!
