### ISSUE TITLE
Create a CupertinoTableRow and CupertinoTable

### ISSUE THREAD

**Issue by xster** [flutter/flutter#19228]
The table should offer a grouping function with group label.
The row should offer a basic and a subtitled mode.

Checklist:

- [ ] From https://github.com/flutter/flutter/issues/24604, tables with more content than the page scrolls. Tables with less content than the page creates fake rows with the size of the last item and fills the table with it. That table still overscrolls with more of the fake rows.
- [ ] From https://github.com/flutter/flutter/issues/24605, make sure table can take rows of different height.
- [ ] From https://github.com/flutter/flutter/issues/24760, make sure grouped rows with division gaps, section header/footer labels
- [ ] From https://github.com/flutter/flutter/issues/28052, create a standard tile layout for each row

**Comment by xster** [comment]
Instead of specifically a CupertinoTable, that could just be a normal ListView. The additional convenience widgets would be a CupertinoTableGroup for grouping, header, footer and a CupertinoTableTile for UITableViewCell styling

**Comment by matthew-carroll** [comment]
@xster going with a CupertinoTable sounds better to me than using a ListView.  I think it fits more symmetrically with other Cupertino widgets.  Is there any significant reason to avoid that?

**Comment by xster** [comment]
Chatted a bit offline yesterday. I was initially concerned that there wouldn't be enough features at the list level to warrant a new class but it seems like there would be. Ideally, create more composable Cupertino-agnostic layers in between while achieving those features like a DividerSeparatedListView etc.

**Comment by xster** [comment]
A good point from https://github.com/xster/flutter-test/issues/1, the touch down should start highlighting the cell

**Comment by xster** [comment]
One note: the highlight color for the cell should be tied with the page transition animation which could be a bit tricky.

**Comment by fralways** [comment]
Just pointing out some expectations, maybe this is already covered. Not sure how much alignment is planned with native.
1) Table should support sections
1) Section headers should be sticky unless grouped
2) Option to add left and right actions
3) Support animations right away without any need of additional code (like in animated_list) for adding and deleting rows
4) Option to add custom widget in CupertinoTable if rows count == 0

**Comment by bierbaumtim** [comment]
There is a package that tries to fill the gap. It was developed by matthinc, but wasn't updated to latest SwiftUI changes so I forked it and added some more features and tries to update the widgets to look like the nativ ones. Everything is eyeballed so it is not perfect but maybe it helps or gives an idea how a solution can look like or can be an inspiration.

Original: https://github.com/matthinc/flutter_cupertino_settings
Fork: https://github.com/bierbaumtim/flutter_cupertino_settings

And here an example on how it looks in an app:

![image](https://user-images.githubusercontent.com/40519580/98467040-7d5d1380-21d3-11eb-882f-eae35a9122dc.png)
![image](https://user-images.githubusercontent.com/40519580/98467050-8817a880-21d3-11eb-8a2f-84f083c0cebb.png)

**Comment by SAGARSURI** [comment]
A `CupertinoListTile` is a must instead of wrapping `CuppertinoPageScaffold` with `Material` widget. Consistent platform aware widgets are a must because not everyone wants to use Material styled widgets.

**Comment by TrGiLong** [comment]
Hi everyone,

I want to help flutter team to create ``CupertinoTable``. Is anyone working on this now? Is #24603 related to here?

**Comment by xster** [comment]
@TrGiLong no one is working on it currently. We'd love to take PRs if you're willing. 

My general impression is that CupertinoRows will be boxes, CupertinoTableSections will be slivers and CupertinoTable will be the Viewport/Scrollable.

**Comment by ksilz** [comment]
> @TrGiLong no one is working on it currently. We'd love to take PRs if you're willing.

@TrGiLong: Isn't this issue solved by PR #70676?

**Comment by TrGiLong** [comment]
@ksilz I think not because the table view in iOS has more features like delete, insert button or drag. This PR contains only Form.

**Comment by ksilz** [comment]
> @ksilz I think not because the table view in iOS has more features like delete, insert button or drag. This PR contains only Form.

@TrGiLong Ah, I see. Thank you!

**Comment by xster** [comment]
Forms are also primarily short contents so it doesn't use the sliver mechanism (i.e. the entire content is pre-emptively built). It doesn't lazy build rows or have sticky headers etc which need slivers.

**Comment by dehypnosis** [comment]
check it: https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65 for iOS style form sections. here is flutter 2

**Comment by ksilz** [comment]
> check it: https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65 for iOS style form sections. here is flutter 2

@dehypnosis I think that's great that more than two years after 1.0, we finally got something that Android had from the start - proper form fields. But I think we're still missing the CupertinoTableRow and CupertinoTable, aren't we?

**Comment by campovski** [comment]
I am in the process of completing implementation of  `CupertinoListTile` and `CupertinoListView` for my personal project. After I am done, I will dedup code between my widgets and `CupertinoFormRow` `CupertinoFormSection` because the code is very much similar yet totally different usecase. You can expect a PR by the end of the week. This will include support for ordinary list tile like the ones in iOS Settings and new notched ones like in Notes or Reminders. I just have to eyeball properly some constants before I call it production ready.

**Comment by erf** [comment]
@campovski any news on the `CupertinoListTile`? 

I found the package [cupertino_list_tile](https://pub.dev/packages/cupertino_list_tile), but it is "not a pixel perfect interpretation".

**Comment by ksilz** [comment]
Even Google's own app team now thinks that Material UI on iOS is a mistake. If I read this article correctly, then they [recently decided](https://www.trustedreviews.com/news/google-ditching-material-design-for-ios-apps-4172847) to use native iOS components instead of Material Design to "really make products feel great on Apple platforms".

So in that spirit: Any updates on filling this iOS UI gap in Flutter?

**Comment by sedwo** [comment]
@xster I second @ksilz comment.  What's the plan for Flutter to better support iOS UI?
In this specific case, a Cupertino based table view.
