### ISSUE TITLE
Make flutter_tools tests work concurrently (without -j1)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#21113]
One thing that should speed up the bots (#20036) a little is running tests concurrently. We currently use `-j1` because many tests have race conditions when run concurrently (for example many set the currentDirectory on the filesystem).

This issue is to track discussions/fixes for this.

Tests that seem to be setting `fs.currentDirectory` that may need fixing:

- [x] `flutter_tester_test` (#21119)
- [x] `asset_bundle_package_font_test` (#21114)
- [x] `asset_bundle_package_test` (#21427)
- [x] `asset_bundle_variant_test` (#21426)
- [x] `asset_bundle_test` (#21425)

I've also opened #22037 with a change to make tests throw if they try setting `fs.currentDirectory`.
