### ISSUE TITLE
FlutterViewController needs to be able to communicate about navigation

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#22054]
For iOS Add2App, FlutterViewController's need to expose a way to tell the embedded Flutter view what route should be loaded.  They also need to be able to communicate back to the host app that they're done, so the HostApp can perform appropriate logic to hide/dismiss the view.

This issue is tracking three different problems:

- [x] CupertinoApp did not properly handle `setInitialRoute` logic (whereas MaterialApp and WidgetsApp did).  Fixed in #22269 
- [x] SystemNavigator.pop did not work in some valid cases on iOS; PR in flight at flutter/engine#6341
- [x] Expose push/popRoute on `FlutterViewController`; PR is in flight at flutter/engine#6347

/cc @matthew-carroll

**Comment by dnfield** [comment]
I believe this will satisfy the similar needs of #16490 on the Android side, although not as generically.

**Comment by matthew-carroll** [comment]
If we're talking about some kind of generic navigation after the initial route, I think this should be handled via platform channel in a way that any part of the system could utilize.  Same as text input, accessibility, etc.

The Android side of #16490 should already be handled in the refactor.  If we want to institute a public API for navigation then that's a whole new issue that will need to be filed.  But this also crosses over into API territory to a degree that we should consult some others, too.

**Comment by dnfield** [comment]
Discussed this a bit more with @matthew-carroll - some more clarification here:

1. By the time you can call `setInitialRoute` on `FlutterViewController` in an Add2App scenario, it seems to be too late and the default route is loaded up anyway.  This isn't an issue on Android (especially since the recent refactor Matt's doing), where you can have more fine-grained control over when the Engine is instantiated and when you call `setInitialRoute`.  It'd be good to get some feedback on whether there's a path for iOS being missed here that would already work.
2. It seems reasonable to think that a user would want to specify which route is being used.  The most natural seeming way to do this would be to use the `flutter/navigation` system channel that's set up already, and that the `FlutterViewController` already knows about.  My idea here is to expose access to that channel so that the host app could direct a `FlutterViewController` to navigate to a specific route.
3. Either way, there doesn't currently appear to be a way for a host app to be notified that a `FlutterViewController` is done and can be dismissed.  This is currently by design (a full Flutter app can't exit itself on iOS, consistent with Apple HID guidelines), but doesn't work so well in the Add2App context where a Flutter view might take over the full screen and need to eventually go back to some other ViewController.

/cc @Hixie @cbracken @chinmaygarde

**Comment by dnfield** [comment]
Discussed this offline a bit more with Chinmay.  1 and 2 can be resolved with a refactor to not use platform channels on that setInitialRoute - it introduces several issues.

I'll open a PR for that soon.

**Comment by dnfield** [comment]
This is starting to look like the same issue as #11607
