### ISSUE TITLE
Improve text input and editable text fields. [Tracking issue]

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#23433]
This is a tracking issue to organize the various bugs I have recently filed that have to do with text input, highlighting, selection, cursors, jank, jitters, gaps, and whatnot.

Issues:

- [x] - https://github.com/flutter/flutter/issues/21997 Text selection vertical extent should be defined per line (not per glyph) 
- [x] - https://github.com/flutter/flutter/issues/23432 Cannot move selection start handle when handle moved to beginning of text in Flutter Gallery
- [x] - https://github.com/flutter/flutter/issues/23319 Cursor shifts after a short delay when selecting a location in the middle of some text.
- [x] - https://github.com/flutter/flutter/issues/22627 RTL indicator back to start after clicking space
- [x] - https://github.com/flutter/flutter/issues/22241 Antialiasing/gap between text selection rects
- [x] - https://github.com/flutter/flutter/issues/20692 When a text input is at the top of the screen, the copy/paste bar is placed on top of it 
- [x] - https://github.com/flutter/flutter/issues/22288 Text edit displays outside of box when erasing quickly.
- [x] - https://github.com/flutter/flutter/issues/24182 Cursor too high/short for non-alphabetic scripts such as Chinese, emojis, and others.
- [x] - https://github.com/flutter/flutter/issues/24266 Cursor always at the front when typing emojis
- [x] - https://github.com/flutter/flutter/issues/24214 Text selection handles display outside visible text region
- [x] - https://github.com/flutter/flutter/issues/24361 GetRectsForRange becomes misaligned when selecting alphabetic-ideographic script mixed paragraphs.
- [x] https://github.com/flutter/flutter/issues/24317 Fix vertical alignment of LibTxt layout of non-alphabetic scripts.
- [x] https://github.com/flutter/flutter/issues/20183 TextField, Enter Chinese in android device ,The bottom is cut
- [x] https://github.com/flutter/flutter/issues/24203 Can't remove khmer unicode from textform field
- [x] https://github.com/flutter/flutter/issues/24456 Center aligned `TextField` shows caret in the middle when text end with space.
- [x] https://github.com/flutter/flutter/issues/24796 Lag when typing long text blocks with a lot of complex emojis.
- [x] https://github.com/flutter/flutter/issues/24802 Caret is able to select within emoji characters on the second line of text with emojis
- [x] https://github.com/flutter/flutter/issues/27948 Can't select text after scrolling
- [x] https://github.com/flutter/flutter/issues/38417 Typing in different language other than English in multilines textfield makes letters shake.
- [x] https://github.com/flutter/flutter/issues/37377 textfield will bounce when I drag into selected in bottom

Will add more as necessary.

**Comment by zoechi** [comment]
#24214

**Comment by yohom** [comment]
#24456

**Comment by sinsarath** [comment]
https://github.com/flutter/flutter/issues/24203

**Comment by zoechi** [comment]
#22496 is quite similar to #24456

**Comment by p30arena** [comment]
https://github.com/flutter/flutter/issues/21679#issuecomment-441585623

**Comment by satjawat** [comment]
#21745

**Comment by yy1300326388** [comment]
#28306 TextField long press menu interaction error on an Android device

**Comment by chopikus** [comment]
#30662 Cant input cyrillic, unicode symbols.

**Comment by GaryQian** [comment]
Almost all of the issues in this tracker have been resolved. I will close this now!

**Comment by mono0926** [comment]
> - #21997 Text selection vertical extent should be defined per line (not per glyph)

Not fixed yet.
