### ISSUE TITLE
Split develop, deploy and profile builds for both iOS and Android in flutter tool

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2366]
- [x] android flutter build/run --debug (JIT)
- [x] android flutter build/run --profile (AOT)
- [x] android flutter build/run --release (AOT)
- [x] android, ensure that --profile and --release are not available for emulators (#4197)
- [x] ios flutter build/run --debug (interpreter) (#2042)
- [x] ios flutter build/run --profile (AOT)
- [x] ios flutter build/run --release (AOT)
- [x] ios, ensure that --profile and --release are not available for simulators (#4200)
- [x] modes accessible from atom (can choose which mode to run in) (#4042)
- [ ] it's possible to take a screenshot from a simulator/emulator w/o the slow mode banner

more docs on the modes are here: https://github.com/flutter/flutter/wiki/Flutter's-modes

---

develop:
- very fast edit/refresh
- Checked mode is possible
- Interpreted or JITed (device vs. simulator, possible we'll want to use interpreter in both places when possible)
- Observatory enabled.

profile:
- Checked mode code removed
- Ahead of time compiled (AOTC) when possible
- Observatory enabled.

deploy:
- checked mode removed
- ATOC
- Observatory removed.

We don't have to actually make the configs different to begin with, but we do need to expose this difference in the `flutter` tool in order to make space for the backend work (like wiring in the Interpreter mode on iOS `develop` on devices).

@chinmaygarde @devoncarew

**Comment by sethladd** [comment]
This may be implied but develop mode enables fast edit/refresh cycles.

**Comment by devoncarew** [comment]
Is the profile build configuration necessary? `deploy` would work for profiling modulo the removal of the observatory.

This would mean we don't pass things like `--checked` into `run` (or `build`), we pass `--deploy` or `--dev`.

I'm going to assume that dev mode and deploy mode would likely load their assets (images and code) in different ways. Dev mode may be a shell we build with any native code, but where the dart code is sideloaded (and re-loaded). The deploy mode would AOT it all into one binary, deployable artifact.

**Comment by abarth** [comment]
> Is the profile build configuration necessary?

The difference is whether to include observatory (binary size) and whether to have the sampling profiler running (battery).  If you don't have a profiling build, you either need to pay the costs of the devtools/profiler in production or not be able to profile the production configuration.

**Comment by eseidelGoogle** [comment]
flutter/flutter#2042 tracks the iOS build support necessary for this tooling.

**Comment by devoncarew** [comment]
The current names are `develop`, `profile`, and `deploy`. Do people have preferences re: renaming the modes, to either:

- `debug`, `profile`, `deploy`
- `debug`, `profile`, `release`

**Comment by devoncarew** [comment]
I'm working on a PR which would rename to `debug`, `profile`, `deploy`.

**Comment by Hixie** [comment]
Searching google for [debug release] and [debug deploy] suggests the first pair is more widely used.

**Comment by sethladd** [comment]
How close are we to closing this? Do we have a checklist of remaining items?

**Comment by devoncarew** [comment]
@chinmaygarde, @tvolkert, I re-purposed this bug as a burndown of the remaining items. Can you update the ios related ones (listed in the very first entry in the bug)? Thanks!

**Comment by chinmaygarde** [comment]
I updated the entries. Thanks.

**Comment by devoncarew** [comment]
@chinmaygarde, I updated based on some testing, and filed #4200 (re: --profile and --release against simulators).

**Comment by abarth** [comment]
Done.
