### ISSUE TITLE
IAP: Create an example app with getting started documentation

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#25987]
This should be able to demo a basic use of the plugin.

- [X] ~Getting started~ flutter/plugins#1024
- [x] ~Check if the payment processor is available (flutter/flutter#26321)~ flutter/plugins#1057
- [x] ~List available products (flutter/flutter#26325)~ flutter/plugins#1169
- [x] Load previous purchases (flutter/flutter#26326)
- [x] Purchase an unlock (flutter/flutter#26327)
- [x] Purchase a consumable (flutter/flutter#26328)
- [ ] Purchase an auto-renewing subscription (#26329)
- [ ] Purchase a non-renewing subscription (#26331)
