### ISSUE TITLE
Tracking Issue for landing code generation support in flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#27141]
Code generation support via direct integration of build_runner.

- [x] flutter_build package containing build.yaml and package:build dependency (https://github.com/flutter/flutter/pull/26978)
- [x] dependency verification in the builders https://github.com/flutter/flutter/pull/27122
- [x] verify dependencies can be corrected synced to google3 and fuchsia-source
    - Blocked on figuring out how to inject deps for google3
~~- [ ] flutter analyze, run, and build benchmarks with codegen~~
- [x] flutter integration test which runs a build and then executes generated code
- [x] Enable incremental builds with updated build_runner_core
- [x] example in flutter repo or elsewhere containing codegen (may reuse example from integration test)
- [x] Remove experimental flag

-- Out of developer preview ---

- [ ] documentation/best practices
- [ ] samples on either website or flutter repo
- [ ] example generators working well, like dart.inject
- [x] versioning issues between builders resolved,

There may be additional follow up work required if we can identify performance bottlenecks or dependency issues that must be resolved.

**Comment by jonahwilliams** [comment]
Addresses https://github.com/flutter/flutter/issues/21980 via full support for dart:inject, https://github.com/flutter/flutter/issues/16603 via support for generated code, part of https://github.com/flutter/flutter/issues/25377 via allowing code generation

**Comment by jonahwilliams** [comment]
Required: https://github.com/dart-lang/build/issues/2028

**Comment by jonahwilliams** [comment]
Blocked by https://github.com/flutter/flutter/issues/27809

**Comment by cbazza** [comment]
@jonahwilliams 

Will code generation support something like source maps? Basically looking for a way that the generated code can be mapped back to the source code for when using the debugger. It's nice to debug with the code that you wrote instead of the generated code. My particular interest is with transforming DSX into Flutter:
https://spark-heroku-dsx.herokuapp.com/index.html

**Comment by jonahwilliams** [comment]
Technically yes, a given builder can output multiple files for a given input file. So you could define a builder which takes a `.dsx` and produces a  `.dart` and `.source_map`. However, I suspect that won't be enough for what you'd like, and I don't know if there is support for source maps from other languages to dart built into any of the existing tooling.

In theory it should be possible, the kernel files used in development already contain the source code they refer to.

**Comment by jonahwilliams** [comment]
Support for code generation has landed in the master channel, though at this point this feature is a developer preview. I expect that there will be follow up fixes and bugs required, and their may need to be changes to configuration or versions accepted. 

Note that currently the minimum version of build_runner supported is 1.2.8. Any builders which require older version of build or build runner may not work. This should be expected to increase in the future so that we can support more features, including building for the web. 

Example: to use json_serializable in a project:

pubspec.yaml
```
name: example_project

dependencies:
  json_annotation:  ^2.0.0

builders:
  json_serializable: ^2.0.3
```

After `flutter run` or `flutter generate`, the generated code will appear in the build cache or source directory. The editor may need to be restarted if this is the first run of code generation and the generator builds to cache.

----

Note that if you are currently running build runner manually you can absolutely keep doing so. builders are only used if specified.

**Comment by rrousselGit** [comment]
> Example: to use json_serializable in a project:

Is the absence of a `dev_dependencies` deliberate?

**Comment by jonahwilliams** [comment]
Yes (though the exact mechanism for doing so is under discussion)

Currently pub requires that all dependencies and `dev_dependencies` use the same dart SDK. This doesn't work naturally when the SDK is Flutter and a dependency uses mirrors. Furthermore, `dev_dependency` is really overloaded. It should just mean "dependencies needed by tests", but it currently also includes "dependencies required by tooling" too. 

We've intentionally not included the flutter_tool as a source dependency on flutter applications, it wouldn't make sense to sense they run in different SDKs/VMs. This is unlike the normal build_runner workflow, but due to the issues above and concerns about over constraining applications I added the builder logic. This generates a sub project for tooling only that does not share dependencies with any flutter code, allowing mirrors or any other SDK functionality not present in flutter.

**Comment by humblerookie** [comment]
@jonahwilliams  
I'm unable to generate package:inject with `flutter generate` if I specify a relative or shorthand path

i.e

```
builders:
  inject_generator:
    path:./inject.dart/package/inject_generator
```
Does not work and gives me a  `Because flutter_tool depends on inject_generator from path which doesn't exist (could not find package inject_generator at "inject.dart/package/inject_generator"), version solving failed.
`
However providing the entire path like
```
builders:
  inject_generator:
    path: /Users/Anvith/Development/Flutter Projects/goodreads_client/inject.dart/package/inject_generator

Seems to work fine. Am I doing something wrong or is this not supported?

**Comment by jonahwilliams** [comment]
@humblerookie I have a fix for this at https://github.com/flutter/flutter/pull/33283

**Comment by jonahwilliams** [comment]
Update: I spent some time in the last week making sure this is forward-compatible with flutter web. Doing so will require some small tweaks outlined in https://github.com/flutter/flutter/pull/33944, but those shouldn't require changes from users, though any builders that previously built to cache will instead be overriden to build from source.

**Comment by jonahwilliams** [comment]
Actually, I've found a way to make it work, disregard!

**Comment by phamnhuvu-dev** [comment]
I have a sample use inject.dart for the flutter. Can I show it in your repo?
https://github.com/phamnhuvu-dev/Mobile-Architecture/tree/master/flutter/flutter_bloc_pattern/base_flutter_bloc_pattern

And I have a flowing question:
With a constructor have the optional parameter, injector_generator always return null for the function DemoScreen provide.
```dart
class DemoScreen extends StatefulWidget {
  final DemoBloc _demoBloc;

  @provide
  const DemoScreen(this._demoBloc, {Key key}) : super(key: key);

  @override
  _DemoScreenState createState() => _DemoScreenState();
}
```

I have to remove it and all is ok.
```dart
class DemoScreen extends StatefulWidget {
  final DemoBloc _demoBloc;

  @provide
  const DemoScreen(this._demoBloc) : super();

  @override
  _DemoScreenState createState() => _DemoScreenState();
}
```
The Key parameter will is necessary for some situation

**Comment by jonahwilliams** [comment]
I've started on some initial documentation for the feature here:

https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter

There is certainly more to do, but I believe the original goals as stated have long since been achieved, some I'm calling it done for now. Anyone running into issues or missing specific examples should file follow up bugs.

**Comment by amadeu01** [comment]
@jonahwilliams I tried to follow your instructions from the wiki.
I created a library to generate dart code from `.env` files 
http://github.com/amadeu01/dotenv2dart

But, I couldn't reference the generated dart file from `.dart_tools` (cache) in the code.
I don't know what I'm missing here. I tried the same `build.yaml` that you used in your json to widget project.

**Comment by jonahwilliams** [comment]
@amadeu01 please file a new bug with a minimal reproducible example and the output of `flutter doctor -v`.

**Comment by amadeu01** [comment]
@jonahwilliams I found what I missed, 

I had to add my builder inside `builders` section.
