### ISSUE TITLE
We should be linting the Android embedding

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28847]
- [x] Add a `project.xml` file that the Android linter can use (done in flutter/engine#8023)
- [x] Add scripts to check the embedding code (flutter/engine#8036)
- [x] Make it part of a presubmit (flutter/engine#8036)
- [x] Make it run on postsubmits

**Comment by dnfield** [comment]
flutter/engine#8036 will start checking for new violations.  We can track the fixes in #28848 and rebaseline as we go.  We should eventually get to a point where we don't need the baseline anymore because we've either customized our lint rules or fixed all the issues.
