### ISSUE TITLE
Rename GPU thread to raster thread

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#29443]
GPU thread seems to be a confusing name as it sounds like everything happens on the GPU but it's actually not. Maybe it's better to fix it sooner (when we're still relatively small) than later.

Specifically,
1. Even if we're using GPU, a lot of work on the "GPU" thread currently happens on the CPU. For example, shader compilations.
2. Sometimes this thread involves no GPU at all (e.g., when `--enable-software-rendering` is given, or when Flutter is running on the iOS simulator)

One rename suggestion is to follow Android's naming of RenderThread so Android developers will immediately feel familiar.

**Comment by liyuqian** [comment]
CC @chinmaygarde @cbracken @kenzieschmoll @Hixie

**Comment by kenzieschmoll** [comment]
Looping in @Sfshaza and @InMatrix as this naming will affect our docs and tooling. We use "UI" and "GPU" to describe the threads in current documentation - https://flutter.dev/docs/testing/ui-performance.

CC @jacob314

**Comment by chinmaygarde** [comment]
Sounds good to me. I have been referring to it as the render thread in presentations for similar reasons.

**Comment by InMatrix** [comment]
I'm supportive of finding a more accurate name for the GPU thread. I have a couple of questions:

> One rename suggestion is to follow Android's naming of RenderThread so Android developers will immediately feel familiar.

Will this analogy bring incorrect assumption about how Flutter's "render" thread works? 

Related, I found Chrome shows a "GPU" thread in its profiler:
![image](https://user-images.githubusercontent.com/348942/54658427-a377f200-4a8a-11e9-81d6-8f7495df2238.png)

Is this "GPU" thread in the same nature as Flutter's "GPU" thread?

**Comment by liyuqian** [comment]
I see that "render thread" could also be a little misleading since Flutter also has both a Dart rendering layer, and an engine rendering layer. Maybe let's call it "rasterize thread" since it's mainly about `Rasterizer::Draw` and we haven't used "rasterize" anywhere else yet.

I'm not very familiar with the Chrome GPU thread. I'm asking someone who's working on Chrome and I'll let you know once I heard back.

**Comment by liyuqian** [comment]
Just heard back:

So far, Chrome's GPU thread only deals with GL commands so it's different from our "GPU thread".
https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome
https://www.chromium.org/developers/design-documents/gpu-command-buffer

**Comment by jacob314** [comment]
I think we'll need to verify that whatever name we pick is familiar enough
to flutter users.
It would be nice if the name we pick is accurate but a slightly misleading
name could be alright if it points users in the right general direction.
Our users don't need to land changes to the flutter engine, just get an
approximate idea of where the slowdown their app is experiencing may be
coming from.

**Comment by dnfield** [comment]
While we're at it, should we rename the UI thread to the Dart thread?  Or something indicating that it's the thread used for Dart code?  It gets confusing for Android, where @UiThread means what we call the Platform thread.

**Comment by liyuqian** [comment]
Dart thread sounds like a good idea to me. But I didn't touch that thread often so maybe it's more important to know what the framework team thinks about this name.

**Comment by timsneath** [comment]
I agree that any change should be holistic. Adding @csells to brainstorm ideas here since he can both canvass others and has priors here from previous projects.

**Comment by csells** [comment]
I agree that we should use a more precise name. Adding @Hixie for his thoughts.

**Comment by filiph** [comment]
My thoughts on this:

* As an alternative name for "GPU thread", I like **"rasterization thread"**. It's almost completely accurate, has no naming conflicts (that I know of), and is still short enough. For people who haven't heard the term rasterization, it's [easily searchable](https://www.google.com/search?q=rasterization). It can be abbreviated to "raster thread", for example when we need to fit it in a devtools UI.
* As an alternative name for "CPU thread", I like **"main thread"**. It's what people are using, and it's also quite accurate (it's where the `main()` function gets called, and it's also the "main" thread of the app).
  * I like "main thread" more than "Dart thread", because the existence of "Dart thread" seems to suggest that _there is only one_ Dart thread, which is not true (and kind of a dangerous idea to proliferate).

However, I don't have _strong_ opinion about this. I do want to get to a decision quite soon, though, since I have some video recording scheduled, and would like to have the terminology right.

What's the next step to get this terminology change approved (or rejected)?

**Comment by timsneath** [comment]
I have no issues with either of these (a slight preference for "raster"
over "rasterization", but I'm speaking as a pundit rather than in any
capacity worth paying attention to!). Your explanations are clear to me and
preferable to "GPU thread" and "Dart thread".

**Comment by liyuqian** [comment]
"raster/rasterization thread" and "main thread" sound good to me. Please feel free to organize a meeting to see if most people feel good about those names, and drive the effort of making the renaming happen. I feel that the majority of work would be on documentation and tools. In the engine, @chinmaygarde and I should be able to modify the performance overlay, and GPUTaskRunner/UITaskRunner without too much overhead.

As mentioned earlier, this will have a long lasting and wide impact that's harder to make as time goes by, so doing it early is definitely preferable.

**Comment by cbracken** [comment]
One big concern I have with renaming what we currently call our 'UI thread' to the 'main thread' is the iOS also calls something the 'main thread' and that thread is the thread we call our 'platform thread'.

**Comment by dnfield** [comment]
Raster thread is good.

I don't like "main thread".  Main thread should normally mean the thread that was used for invoking the `main` method of your native application - e.g. the `Platform` task runner in our current lingo, and the `UiThread` in Android lingo.  The current `UI` thread is very different from that.

**Comment by liyuqian** [comment]
Let me also propose "Build thread" for the current UI thread. To summarize, 
- For the current UI thread we have proposed
  - Dart thread
  - Main thread
  - Build thread
- For the current GPU thread we have proposed
  - Render thread
  - Rasterization thread
  - Raster thread

So far, "raster thread" seem to be preferable by many, while "Dart thread" vs "Main thread" is a little bit unclear?

**Comment by filiph** [comment]
Thanks for the quick response, everyone! 

Unless someone tells me otherwise, I'll consider "raster thread" a winner for the future name of "GPU thread".

For "CPU thread", here are some alternatives:

* main thread
* build thread
* app thread
* widgets thread
* prime thread
* master thread

Can you all please reply with their favorite and with their "no go" lists?

**Comment by jacob314** [comment]
My preferences in order:
1. main thread
2. event loop thread <-- extra alternative
2. widgets thread
3. app thread

No gos:
prime thread 
master thread  <-- seems like a more confusing version of main. There isn't something overly special about the initial isolate.
build thread.     <-- fine if users understand it is widget build but confusing if they think of a different type of build

**Comment by cbracken** [comment]
My preferences for the UI thread:
1. App thread (Flutter App Thread?)
2. UI thread (are we renaming it because of confusion with the Android UI thread which is our platform thread?)

No go:
1. main thread (This has a very different meaning on iOS -- specifically it's what we call our platform thread)
2. prime thread
3. master thread
4. build/widgets thread: these are both specific to the widgets layer of the framework -- I think most people would get it... but it's a bit misleading since you could write an app that only uses `dart:ui` or just the render layer etc.

**Comment by chinmaygarde** [comment]
GPU Thread Preferences:
1. Render Thread: Engine components already use this terminology but it clashes with Androids thread names.
2. Raster Thread: Not completely accurate but close enough.

CPU Thread Preferences:
1. Application/App Thread.
2. Root Isolate Thread.
3. UI Thread: Engine components use this terminology but it clashes with platform thread naming conventions.
4. Dart Thread.

None of the current suggestions are completely accurate as the workloads on these threads are quite disparate (and will likely change as the engine evolves). So, let's just pick one that is the least confusing.

**Comment by dnfield** [comment]
I think that whatever name we come up with, it should have these properties:

- The name is not easily confused with the _actual main thread running the application_, which is different from the thread running Dart.  This means we should not call it "main", "UI" (since Android calls it the `UiThread` already), "master", "prime".  IMO this means we should also not call it the "App" thread.
- The name makes it clear that this is the thread the engine uses to interact with the Dart VM
- The name is not specific to a Framework-only concept like Widget, RenderObject, or Build.

These all point me back to "Dart" thread, or perhaps "Root Isolate Thread".

**Comment by chinmaygarde** [comment]
> These all point me back to "Dart" thread, or perhaps "Root Isolate Thread".

I think of all suggestions, "Root Isolate Thread" is the most accurate but I am not sure how obvious that is to the user. That term is mostly used in the engine.

**Comment by cbracken** [comment]
Root isolate thread is wordy but agreed -- it's the most accurate by far. I prefer it to "Dart thread" mostly because you _can_ legitimately have multiple isolates and they're all Dart threads. 

I suspect the sort of people who are likely to care about what's running on which thread are likely to be fine with that name.

**Comment by chinmaygarde** [comment]
We should open this up to the community for a vote. I'd be delighted to call it "Thready McThreadface".

> On the fence about "App thread" -- of all the names so far it's my favourite of the short ones...

Agreed.

**Comment by liyuqian** [comment]
BTW, I've also added "Dart thread" and the original "UI thread" to the list. (I guess we might end up not renaming UI thread at all if we disagree too much on the new name.) If you haven't considered them, please feel free to modify your vote.

For "build thread", it could also be referenced to layer tree build, or scene build. I think that's something necessary even if one just uses `dart:ui` instead of widgets. I picked "build thread" because "frame build time" and "frame raster time" are already frequently used in performance testing to differentiate the current "UI thread" and "GPU thread".

@InMatrix @jayoung-lee : the votes here are so diverse that we might need some rigorous treatment of data collection and decision making. (BTW, if we're really serious about voting, there are 11 voting rules in [this book's page 17-22][1] to consider.)

[1]: https://www2.cs.duke.edu/courses/fall18/compsci590.2/comsocchapter.pdf

**Comment by johnpryan** [comment]
As a user, I would call it the "main thread" if I am building/debugging a Flutter app. If you need something more precise, you could call it the "Dart main thread" to contrast it with the "platform thread" "iOS main thread" or "Android UI thread".

**Comment by timsneath** [comment]
"root thread" feels plausible as an alternative to main thread, following
on from Chinmay's comments. Distinguishes from the platform "main thread",
but also has the same connotations.

**Comment by jayoung-lee** [comment]
Adding @cobblest, who is working on the tooling side UX.

**Comment by InMatrix** [comment]
Thinking about the context where users will run into those names, I feel the term we pick needs to suggest potential actions to take. One of such contexts is examining the timeline graphs and seeing some red bars. We should help users establish simple associations between red bars on the [insert name] thread and a set of performance diagnosis heuristics they can try. And for the vast majority of our users, the actions they can take are within the limits of their own project rather than in Flutter engine/framework. So I'd favor a name that has concrete meaning to them over a name more accurate to an engine hacker. 

As far as voting on the names, I don't think having users vote on those names will work, since that would be quite out of context. We should at least try plugging in those names in some snippets of our existing performance docs and then ask users to rate how well they feel they understand what's being described.

**Comment by cobblest** [comment]
+1 to what @InMatrix said. This could be a good research question for our next performance profiler study, where we ask users to use devtools to solve a real performance problem. @liyuqian @jacob314 maybe we could work with you to generate a list for the study.

**Comment by filiph** [comment]
I'm a little sad that this seems less and less likely to be resolved quickly. But that's my problem to deal with. (I will use CPU / GPU thread in the video. We can hopefully add subtitles / annotations later.) I'm genuinely glad we're taking this seriously.

I echo @InMatrix and @cobblest: I'm less concerned about accuracy from the perspective of a Flutter SDK engineer, or even a plugin author, and more concerned about readability and actionability from the perspective of a regular Flutter app developer. For that reason, "main thread" (as in `main()`) and "raster thread" are still my favorites.

**Comment by cbracken** [comment]
As noted above I think "main" thread is likely to cause a tonne of confusion -- whenever we use that term we're going to have to clarify if we mean "the thing all iOS developers refer to as the main thread" or "the thing Flutter developers are calling the main thread which is not at all the same as the thread that all iOS developers call the main thread".

**Comment by liyuqian** [comment]
@filiph : it's currently "UI thread + GPU thread" instead of "CPU thread + GPU thread". So if nothing changes, please use "UI thread" instead of "CPU thread" in your video.

**Comment by liyuqian** [comment]
I believe that changing "GPU thread" to "raster thread" sounds good to most of us. Since that's the main confusion, I suggest we change "GPU thread" to "raster thread" first (probably before @filiph 's performance video), and then figure out how to name "UI thread" later. Please upvote or downvote this suggestion. @cbracken @chinmaygarde @timsneath @InMatrix @jayoung-lee @cobblest @johnpryan @dnfield @jacob314 @kenzieschmoll

**Comment by filiph** [comment]
This is a multi-step deal. Here's what we currently think needs to be done:

## TODO list

* [ ] Engine repo changes (owner @liyuqian)
  * [ ] PerformanceOverlayLayer code changes
  * [ ] TaskRunners code changes
  * [ ] Code documentations 
  * [ ] Popular design docs
* [ ] Framework repo (owner @liyuqian)
  * [ ] Code and API documentations
  * [ ] Popular design docs
* [ ] flutter.dev website (owner @filiph)
  * [ ] Anything that mentions the GPU thread
* [ ] Popular Medium articles (owner @filiph)
* [ ] Popular published videos (owner @filiph)
* [ ] Twitter announcement (owner @filiph)

Any others? Any volunteers to help Yuqian with the PRs?

## Transition period

For one stable version of Flutter, we will need to say

> raster thread (previously known as the "GPU thread")

in most documentation. Once "raster thread" has been adopted everywhere in the stable branch, we can start removing the parentheses and therefore all mentions of "raster thread".

**Comment by kf6gpe** [comment]
@liyuqian, where we with landing the engine changes for this? Looks like thats's blocking the rest of @filiph's work. Thanks!

**Comment by liyuqian** [comment]
@kf6gpe : all engine commits have landed and I just updated https://github.com/flutter/flutter/issues/29443#issuecomment-602791835 . @filiph : did I miss any work that's blocking you?

**Comment by filiph** [comment]
@liyuqian Not at all. The framework changes have landed. Unfortunately, I don't think I made it to the dev channel in time.

I'll keep this issue open for now, at least until we see the change in the performance overlay, and are able to actively socialize the renaming (e.g. by a tweet).

**Comment by liyuqian** [comment]
@filiph : by "until we see the change in the performance overlay", do you mean until https://github.com/flutter/engine/pull/17148 makes into either dev, beta, or stable channel?

**Comment by filiph** [comment]
Yes, `stable`.

**Comment by liyuqian** [comment]
@filiph : I wonder if this is now fully completed?

**Comment by filiph** [comment]
Ah! Thanks for the nudge.

I can have a look at the outstanding checkboxes (https://github.com/flutter/flutter/issues/29443#issuecomment-602791835) this week. Then I'll close.

**Comment by filiph** [comment]
Today:

* Updated top 2 SERPs of results of internal search for "GPU thread" to use "raster thread". It seems that more or less _all_ the popular internal docs are migrated now (for some of them I didn't have edit access, so I suggested).
* Went through the 109 current flutter.dev/go design docs and updated the ones that used "GPU thread".
* Asking for a tweet to be published this or next week.

Closing.
