### ISSUE TITLE
Improve Flutter's memory consumption

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#32156]
This is a tracking bug for the collection of sub-issues around improving Flutter's memory consumption, and offering developers more flexibility in choosing where to set the dial on the time performance vs memory consumption spectrum.

Related issues:
  * [x] #13493: Flutter should provide more control over image caching
  * [ ]  #26187: Flutter should be smarter about memory limits for images
  * [x] #16995: Free resources after a Flutter view is disposed
  * [ ] #19358: Unmount everything and dispose states when host activity dies
  * [x] #23231: Memory leaks on iOS
  * [ ] #20690: More deterministic measurement of memory consumption.
  * [x] #26081: Disable in-memory decoded frame cache by default
  * [x] #26443: Consider mipmapping ui.Images generated by the engine
  * [ ] #15479: OnMemoryPressure is unreliable on Android
  * [ ] #25155: Raster cache images may be much bigger than the visible/clipped area
  * [x] #19558: IO thread GrContext memory needs to be cleaned up
  * [x] #44013: Persist the memory profile timeline

**Comment by rsaf** [comment]
This is a really worrying issue for many developers. I created a similar issue.

#32820

**Comment by deverlion** [comment]
We also have completely similar problems.We are now in v1.5.4-hotfix.2, the video plays normally, and iOS does not crash. But when I upgrade to v1.7.8+hotfix.3, iOS video playback is easy to crash because of iOS memory issues. (Only iOS has problems, Android is OK)

**Comment by DyaryRaoof** [comment]
any solution guys ?

**Comment by alectogeek** [comment]
Is there any news? It really prevents us from releasing an app because it becomes too memory consuming because of a huge count of images in the app :(

**Comment by DyaryRaoof** [comment]
@alectogeek 
Try changing to master channel and use the cacheWidth and cacheHeight parameters with your image widgets like so Image.Network(cacheWidth:100, cacheHeight : 100) or use it with Cached_Network_Image(cacheWidth:100, cacheHeight : 100).

This is supposed prevent too much memory consumption. 

I haven't yet tested it because I have problem with changing to the master channel and there are errors preventing me from testing this. It may not be the same in your case. I use a lot of plugins wich maybe causing the issue that I haven't had time to find a solution for.

Please let me know if the solution worked for you.

**Comment by alectogeek** [comment]
@DyaryRaoof Thank you for answer! But looks like cached_network_image 2.0.0-rc.1 package doesn't have cacheHeight/cacheWidth properties

**Comment by DyaryRaoof** [comment]
> @DyaryRaoof Thank you for answer! But looks like cached_network_image 2.0.0-rc.1 package doesn't have cacheHeight/cacheWidth properties

It think it 's present if I am not mistaken. But did you try it in the Image.Network and see if it's present or not. because the last time I checked I couldn't find it either I had to install the flutter SDK again then switch to the master channel but I am not sure if it was present in the Cached_Network_image. 

And as a side note. why not try Image.Network with the cacheWidth and cacheHeight constructors if it is present . It may make your app a lot more stable.

**Comment by alectogeek** [comment]
@DyaryRaoof Unfortunately, I can't try this. I need to cache images in local storage so I use cached_network_image absolutely everywhere in my app. Moreover, I show almost the whole picture, so, I guess, it will not help in my case. :(

**Comment by AAverin1994** [comment]
Any news? I am also having problems with memory leak. #45391

**Comment by EngDjango** [comment]
> 
> 
> @DyaryRaoof Unfortunately, I can't try this. I need to cache images in local storage so I use cached_network_image absolutely everywhere in my app. Moreover, I show almost the whole picture, so, I guess, it will not help in my case. :(

`FutureBuilder<File>(
            initialData: File.fromRawPath(kTransparentImage),
            builder: (cx, file) {
              return Image.file(
                file.data,
                cacheWidth: 250,
                cacheHeight: 250,
                fit: BoxFit.contain,
              );
            },
            future: DefaultCacheManager()
                .downloadFile(widget.post.postImages[index])
                .then((fileInfo) => fileInfo.file),
          );`

i'm facing this problem, and i'm using this code to use cacheWidth and cacheHeight with cache managing, using package:`flutter_cache_manager: ^1.1.3`

**Comment by davewise** [comment]
cacheHeight/cacheWidth properties did the trick for me!

**Comment by danielgchap** [comment]
> cacheHeight/cacheWidth properties fixed the massive memory usage in my case. I actually only use cacheWidth to maintain aspect. Even when I set the cacheWidth to 1200 the memory usage is 5 times smaller than without that property set. Seems like the cacheWidth should default to some reasonable number that doesn't cause memory hogging and can be overridden with a larger or smaller number if the developer wishes.

Hi davewise! Are you using cachednetworkimage or the out of the box Image.network approach? (I'm currently using cachednetworkimage, I'm just trying to find the best approach)

**Comment by pacifio** [comment]
It happens mostly when showing images ..

**Comment by liyuqian** [comment]
@dnfield : would you also prefer to close this meta issue and just track memory issues from label "perf: memory"? (Similar to what you've done with https://github.com/flutter/flutter/issues/13493)

**Comment by dnfield** [comment]
I'm not a huge fan of meta issues like this - they tend to get outdated.  And at least one of the linked issues in the top of this bug would actually increase memory consumption.

I think before closing this one we should make sure the linked bugs are closed/addressed though.  With the image cache one the bugs it referred to were all either out of date or closed.

**Comment by davewise** [comment]
> > cacheHeight/cacheWidth properties fixed the massive memory usage in my case. I actually only use cacheWidth to maintain aspect. Even when I set the cacheWidth to 1200 the memory usage is 5 times smaller than without that property set. Seems like the cacheWidth should default to some reasonable number that doesn't cause memory hogging and can be overridden with a larger or smaller number if the developer wishes.
> 
> Hi davewise! Are you using cachednetworkimage or the out of the box Image.network approach? (I'm currently using cachednetworkimage, I'm just trying to find the best approach)

I'm using the Image.network approach. Not sure which is the best approach though...

**Comment by ShekarMudaliyar** [comment]
Any updates on this? my app is in production and want to send an update but cannot coz its crashing on ios

**Comment by dnfield** [comment]
I've closed out a few of the bugs linked here that I believe are resolved. Some of them are still not, so I've made sure to label with with `perf: memory`. There are a number of other bugs related to memory under that tag, which should be the most up to date way of finding and tracking memory related issues.

I'm going to close this issue since it is not really up to date and will quickly get out of date again if we add more bugs to it. Instead, follow https://github.com/flutter/flutter/labels/perf%3A%20memory
