### ISSUE TITLE
Add project setup page for Android add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32862]
Add a setup section under https://flutter.dev/docs/development/platform-integration that is analogous to https://flutter.dev/docs/get-started/install but for add-to-app project configuration. 

Include https://github.com/flutter/flutter/issues/21851 and https://github.com/flutter/flutter/issues/21850. 

Additions:

- [ ] the . host projects allow both building of modules and of apps. Explain it.
- [ ] ~~split paths for people wanting to build with the outer projects and people who want to build separately~~
- [ ] ~~explain what io.flutter.facade are and why do we need a Flutter gradle submodule~~
- [ ] define and consistently use the same terminology when referring to different pieces of an add-to-app multi-part project
- [ ] once we convert to androidx, offer some instructions for people still using android support
- [ ] Show a possible folder organization of the platform and flutter projects for visualization
- [ ] Talk about make-host-app-editable and when it should be used
- [ ] You must run flutter pub get in the Flutter module when changing pubspec
- [ ] ~~How to use local engines~~
- [ ] ~~If we're still integrating via cocoapods, we need to document that users need to run pod init if the outer project didn't use cocoapods~~
- [ ] Document how to run the flutter module in debug/profile/release (see https://github.com/flutter/flutter/issues/34371)
- [ ] Make it clear that we don't build x86/64 AOT/.so/.frameworks
- [ ] There are tons of link unsatisfied bug reports. Make sure to document that when people have an arm64 phone connected when they build with include_flutter.groovy, they must have a arm64 engine available 
- [ ] @blasten: only AndroidX host apps should be supported.
- [ ] ~~bring in the instructions at https://github.com/flutter/flutter/issues/36968#issuecomment-533357802 into the website~~
- [ ] ~~Document when `flutter packages get` + `pod install` in the host iOS project need to be run again.~~
- [ ] Describe how to handle transitive dependency conflicts if the existing app already depends on a version of Android support/AndroidX https://github.com/flutter/flutter/issues/19688
- [ ] Specify minimum SDK version

**Comment by blasten** [comment]
Related PR (for iOS) in progress: https://github.com/flutter/website/pull/3084

**Comment by jmagman** [comment]
> * [ ]  Talk about make-host-app-editable and when it should be used

Should we advertise this feature by documenting it, in case we get rid of it later?

**Comment by blasten** [comment]
+1. I've seen folks running into issues that can be fixed by `make-host-app-editable`. I think it might be worth documenting it and if we replace it for a different mechanism, then we can update the docs and release notes.

**Comment by xster** [comment]
The test staging site is at https://add-to-app-2019.firebaseapp.com/. I pushed it again with Aaron's new iOS PR (https://add-to-app-2019.firebaseapp.com/docs/development/add-to-app/ios/add-flutter-screen). 

@gaaclarke: note, you have to edit https://github.com/flutter/website/blob/staging-add-to-app-do-not-delete-until-2020/src/_data/sidenav.yml too. Otherwise, the page is not navigable to :D

**Comment by xster** [comment]
You all also have editor access to https://console.firebase.google.com/project/add-to-app-2019 so you can all push to it too via `npx`. See https://github.com/flutter/website/blob/master/README.md for adding new firebase projects.

**Comment by xster** [comment]
The staging urls for this is now at https://add-to-app-2019.firebaseapp.com/docs/development/add-to-app/android/project-setup and https://add-to-app-2019.firebaseapp.com/docs/development/add-to-app/ios/project-setup

**Comment by xster** [comment]
Splitting iOS out to https://github.com/flutter/flutter/issues/45224

**Comment by xster** [comment]
Emmanuel's out this week. I'll start a stub for this page.

**Comment by blasten** [comment]
A few items changed since this issue was filed:

> Once we convert to androidx, offer some instructions for people still using android support

This is on https://flutter.dev/docs/development/androidx-migration

>  Make it clear that we don't build x86/64 AOT/.so/.frameworks

We build x64 AOT.  Is `.frameworks` the same as iOS frameworks?


>  There are tons of link unsatisfied bug reports. Make sure to document that when people have an arm64 phone connected when they build with include_flutter.groovy, they must have a arm64 engine available

Is this the same bug reported on https://github.com/flutter/flutter/issues/45987?


> Describe how to handle transitive dependency conflicts if the existing app already depends on a version of Android support/AndroidX #19688

This might need more granularity.   One conflict we encountered is version mismatch in the compile/runtime classpaths.

**Comment by xster** [comment]
> We build x64 AOT. Is .frameworks the same as iOS frameworks?

right, let's tweak the caveat for supported arch to say we don't support x86 and support the rest.

> This might need more granularity. One conflict we encountered is version mismatch in the compile/runtime classpaths.

ya, I think we covered this one since. 

> Is this the same bug reported on #45987?

I think this was a local engine build issue. Less priority for describing.

**Comment by xster** [comment]
> Is this the same bug reported on #45987?

Actually perhaps https://github.com/flutter/flutter/issues/45882 is representative

**Comment by xster** [comment]
@blasten can you look through the list and see if there's anything else worth adding to the setup page? Otherwise we can close this. 

At a glance, I think there's still a few things we can point out, like how to run release mode via include_flutter.groovy, can I use Flutter in an AndroidX project via include_flutter.groovy etc.

**Comment by blasten** [comment]
@xster can I reassign this issue to you to figure out new priority and milestone?

**Comment by xster** [comment]
Yes

**Comment by xster** [comment]
I'm closing this one since we haven't had much complaints since launch. We can track remaining issues individually.

**Comment by kurtiev** [comment]
Sorry I didn't catch : ) 
@xster how do we suppose to change minSdkVersion in `.android/app/build.gradle` ? 
Thanks.
