### ISSUE TITLE
Switch to the Metal rendering backend on iOS.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#33079]
Based on guidance from the Skia team, the Metal backend is ready for integration into Flutter. This is a meta-bug listing the various tasks that need to be undertaken for the switch to be completed.

The Skia Metal backend is currently only available on iOS versions 11.0 and above. It is unlikely that the minimum supported version will be lowered all the way down to 8.0 (the current minimum supported by Flutter). The recommended approach is to compile both the OpenGL and Metal backends in the iOS engine and use runtime checks to only use the Metal backend on versions 11.0 and above. OpenGL will still be used on older iOS versions till support for the same persists.

### Tasks
- [ ] Add the `enable-metal` GN flag to existing builds of the iOS engine and re-baseline benchmarks that measure binary size. Binary sizes are expected to regress by around [220 Kbytes uncompressed](https://gist.github.com/chinmaygarde/f0b6cc4924c4c09ac9dfe5dcf6e5d083).
- [ ] Enable the Metal backend on iOS versions 11.0 and above.
- [ ] Add an `enable-metal` shell flag that allows overriding the rendering backend to use without needing version checks. Duplicate all existing benchmarks to run the same with the Metal backend in addition to the OpenGL backend.
- [ ] Ensure plugins that that provide pixel buffers to to the engine for inline composition have the [appropriate compatibility flags set](https://developer.apple.com/documentation/metal/mixing_metal_and_opengl_rendering_in_a_view). 
- [ ] Ensure platform views are wired up.

References:
* Notice of OpenGL deprecation on iOS: https://developer.apple.com/ios/whats-new/
* Notice of OpenGL deprecation on Mac: https://developer.apple.com/macos/whats-new/
* Related Flutter issues: https://github.com/flutter/flutter/issues/32569, https://github.com/flutter/flutter/issues/18208

**Comment by BaiKunlun** [comment]
Is it a time to release?

**Comment by Hixie** [comment]
Next step here is an opt-in preview. @chinmaygarde estimates at least 2 weeks to get this finished.

**Comment by dnfield** [comment]
It's entirely possible today to build the engine with the metal backend for testing... Although a bit challenging.  Are you looking for something where we provide a binary that works without locally building the engine?

**Comment by dnfield** [comment]
I split platform views into its own bug, and an implemenation is at flutter/engine#11070

I've also opened #38754 to track getting screen rotation wired up properly.

**Comment by fkorotkov** [comment]
FYI I just got told that there is an issue running applications using Metal in an emulator. Xcode 11 will enable it but there will be still an extra problem of running such apps in an emulator inside of a VM (e.g. in Cirrus). Anka folks are adding support for Metal inside of VMs and I'll keep you posted.

**Comment by chinmaygarde** [comment]
We use the software backend on simulators already (with OpenGL on devices). We don't expect to change this behavior with the migration to Metal.

**Comment by Hixie** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/18208.
