### ISSUE TITLE
Implement and enable canvas-based text measurement

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#33523]
### Description
Today, we do text measurement using the DOM. That's too slow and we are stuck with whatever CSS supports. For example, we can't do multi-line text overflow correctly because CSS doesn't support it.

Early results are very promising in terms of correctness and performance.

This new implementation will also open the door to more improvements like rendering multi-line text in canvas (instead of using a `<p>` element).

### How to enable
To enable the new experimental implementation, you could add the `--dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true` flag to your `flutter run` command (it only works in release mode). Example:

```
flutter run -d web-server --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true
```

### Tasks

* [x] Handle basic measurements.
* [x] Full support of text overflow and clipping (`maxLines`, `textOverflow`).
* [x] Render multi-line text on canvas.
* [x] Support `letterSpacing` and `backgroundColor`.
* [ ] Correct algorithm for line break opportunities (https://github.com/flutter/flutter/issues/45932).
* [ ] Correct measurement of emojis (https://github.com/flutter/flutter/issues/40221).

**Comment by goodmansasha** [comment]
VS Code has been using canvas for a few years now, and it allows cutting and pasting.

https://github.com/xtermjs/xterm.js/pull/938

**Comment by mdebbar** [comment]
@goodmansasha thanks for sharing. I'll check it out.

**Comment by goodmansasha** [comment]
As a bonus, the xterm.js performance is much, much faster than the DOM, thanks to using a sprite sheet that [maps each character to a cached, pixelated rendition](https://weihanglo.tw/posts/2017/how-is-new-terminal-in-vs-code-so-fast/). 

Unfortunately, using canvas breaks existing DOM features, such as links just working, contextual menus working on highlighted text, screen reader access, high resolution printing, and HTMLELement.innerText().

The most important feature this breaks for me is that the browser’s own “Find” command would not not work. 

Thankfully, wiser people than I are working on Flutter, like Ian Hickson ( @Hixie ). He could have an invaluable opinion on breaking DOM text features, and I hope he chimes in. Ian once said (and I’m paraphrasing) that many of the best parts of the HTML living standard are the result of hacks, that came to become standard because two browsers implemented a breakout feature. In other words, they are somewhat arbitrary and messy. This is wisdom.

If it’s not already planned, one thought for dealing with this complexity is that text contents could remain in the DOM and be available in an accessibility layer, such as as the innerHTML of some element not printed on the screen (eg. Using CSS `.no-print`). I don’t think that would allow them to be searched, but they would be there.

**Comment by photon3108** [comment]
@mdebbar I just find a bug in `ParagraphRuler.hitTest` photon3108/engine@c53c07c7f, but it belongs to the `DOM-based` and you are implementing the `Canvas-based`. Is it a good time to open a pull request for it?

**Comment by mdebbar** [comment]
@photon3108 yes, please open a PR and I'll be happy to review it. Were you able to setup the engine repo and try the changes locally?

**Comment by photon3108** [comment]
@mdebbar Thank you for your reply. I had tested it locally but I can't pass `felt test` with or without this patch. The without cast is at flutter/engine@2994f7e1e6 and it's shipped with current stable version. I would like to write a test-case with this patch. Is [measurement_test.dart](https://github.com/flutter/engine/blob/master/lib/web_ui/test/text/measurement_test.dart) a good place? Or should I move it to more upper level to make it be general for each platform?

**Comment by mdebbar** [comment]
@photon3108 thanks for your contribution! I'll review the PR today.

**Comment by photon3108** [comment]
@mdebbar Does this issue have any plans about [SEO for content inside canvas element](https://stackoverflow.com/a/28460903)?

**Comment by stuz5000** [comment]
Any progress here? It breaks cursor-based interaction of text on web. Is a severe bug in basic functionality.

**Comment by rpk98c** [comment]
Progress update would be appreciated. Any form with a multiline text field is currently broken for us.

**Comment by stuz5000** [comment]
In the latest dev branch, finding the text position is still very broken for web.

  * text positions are only reported correctly for multi-line text
  * when the canvases are place in a list, even the first line doesn't get correct results.

```
Flutter 1.14.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision c88320458e (5 days ago) • 2020-01-15 11:38:02 -0500
Engine • revision bc41ab5139
Tools • Dart 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)
```

Demo for both bugs:

```
import 'package:flutter/material.dart';

final loremIpsum = "012345678\n"
    "012345678\n"
    "012345678\n"
    "012345678\n"
    "012345678\n";

void main() => runApp(MyApp());

// Display boxes containing a grid of numbers.
// You should be able to tap 0..9 in the first row and get positiions 0..9 printed.
// You should be able to tap 0..9 in the first row and get positiions 10..19 printed.
// ...
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Welcome to Flutter',
        home: Material(
            child: Center(
          child: Container(
            width: 350,
            color: Color.fromARGB(100, 0, 0, 0),

            /// Second line of text - position is not identified.
//           child: SelectText()),

            /// First line of text in list views - position is not identified.
            /// All I get if 5 and 50
            child: ListView.separated(
                itemCount: 3,
                padding: const EdgeInsets.all(20.0),
                separatorBuilder: (_, __) => Divider(),
                itemBuilder: (_, __) => SelectText()),
          ),
        )));
  }
}

class SelectText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //    return redbox();
    // Set width to max allowed by parent
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      final textPainter = TextPainter(
        text: TextSpan(
          text: loremIpsum,
          style: TextStyle(height: 2.5),
        ),
        textDirection: TextDirection.ltr,
      );

      final width = constraints.maxWidth;
      textPainter.layout(
        minWidth: 20,
        maxWidth: width,
      );
      final height = textPainter.height;

      return Container(
          width: width,
          height: height,
          color: Colors.grey,
          child: GestureDetector(
            onTapDown: (details) {
              // BUG. On web- position is only correct for first line.
              print(
                  "pos -> ${textPainter.getPositionForOffset(details.localPosition).offset}");
            },
            child: CustomPaint(
              size: Size(width, height), // Parent width, text height
              painter: TextCustomPainter(textPainter),
            ),
          ));
    });
  }
}

class TextCustomPainter extends CustomPainter {
  TextPainter textPainter;

  TextCustomPainter(this.textPainter, {Listenable repaint})
      : super(repaint: repaint);

  @override
  void paint(Canvas canvas, Size size) {
    textPainter.paint(canvas, Offset(0, 0));
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return false;
  }
}
```

**Comment by mdebbar** [comment]
Thanks everyone for your patience.

I made some progress on this few weeks ago, then got distracted by other work. I'll come back to this soon, and the next step in my TODO list here is to fix text positions in multi-line paragraphs. I already have a WIP (work-in-progress) solution but it's not complete yet.

**Comment by pabloa** [comment]
Thank you @mdebbar 
My project is affected for this bug too. I hope it could be solved soon.

**Comment by stuz5000** [comment]
Thank you @mdebbar for work on this. I guess, since its been open since May of 2019 and its a major bug blocking flutter use in the web, fixing this is harder than expected. 

Do people have effective workarounds? I need to be able to:

 - determine which character a cursor has hit in text
 - identify the bounding boxes for text character ranges
... in multi-line text

Or do these functions always terminate in the canvas text painter?

**Comment by mdebbar** [comment]
> * determine which character a cursor has hit in text
> * identify the bounding boxes for text character ranges ... in multi-line text

You can take a look at how `RenderEditable` uses `TextPainter` to perform these calculations [here](https://github.com/flutter/flutter/blob/1f3d423f9222290861d699d79024425e0be6166c/packages/flutter/lib/src/rendering/editable.dart#L1406), [here](https://github.com/flutter/flutter/blob/1f3d423f9222290861d699d79024425e0be6166c/packages/flutter/lib/src/rendering/editable.dart#L1593-L1596) and [here](https://github.com/flutter/flutter/blob/1f3d423f9222290861d699d79024425e0be6166c/packages/flutter/lib/src/rendering/editable.dart#L1976).

`TextPainter` internally calls `dart:ui` (which is the low-level API provided by the flutter engine and web engine). This github issue is about changing the implementation inside the web engine.

**Comment by stuz5000** [comment]
I understand how to ask for that information -- that's what I do in the bug I reported ( https://github.com/flutter/flutter/issues/44121 Paragraph/TextPainter.getPositionForOffset reports incorrect multiline positions for web  ). The information just wrong for web when there is multiline text:

 * https://github.com/flutter/flutter/issues/44121 Is definitely still broken (incorrect characters reported for hittests), but you closed it a duplicate of:
 * https://github.com/flutter/flutter/issues/39826 ... where the last comment is that "the solution depends on
 * https://github.com/flutter/flutter/issues/33523 (this).

So.. my understanding is that, to get hit-tests working correctly for web, this is the bug to fix?

**Comment by mdebbar** [comment]
@stuz5000 yes, you are in the right issue.

Have you tried enabling the canvas-based implementation as explained in the description of this issue? The `getPositionForOffset()` issue should be fixed in master now if you enable the flag.

**Comment by stuz5000** [comment]
Like this one (from #44121)?
For the mobile emulator, it is fine.
For web offsets are incorrectly reported.

Am using the master channel (updated today)
```
[✓] Flutter (Channel master, v1.15.4-pre.60, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.4-pre.60 at /home/sir/development/flutter
    • Framework revision e2554a9202 (6 hours ago), 2020-02-13 11:56:45 -0800
    • Engine revision 0e8ed2715a
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 5244d99a5d)
```

```
import 'package:flutter/material.dart';

final loremIpsum =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Container(
            width: 350,
            color: Color.fromARGB(100, 0, 0, 0),
            child: SelectText(),
          ),
        ),
      ),
    );
  }
}

class SelectText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //    return redbox();
    // Set width to max allowed by parent
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      final textPainter = TextPainter(
        text: TextSpan(text: loremIpsum),
        textDirection: TextDirection.ltr,
      );

      final width = constraints.maxWidth;
      textPainter.layout(
        minWidth: 20,
        maxWidth: width,
      );
      final height = textPainter.height;
      GlobalKey key = GlobalKey();

      return Container(
          key: key,
          width: width,
          height: height,
          color: Colors.yellow,
          child: GestureDetector(
            onTapDown: (details) {
              print(
                  "Selection: ${textPainter.getPositionForOffset(details.localPosition)}");
            },
            child: CustomPaint(
              size: Size(width, height), // Parent width, text height
              painter: TextCustomPainter(textPainter),
            ),
          ));
    });
  }
}

class TextCustomPainter extends CustomPainter {
  TextPainter textPainter;

  TextCustomPainter(this.textPainter, {Listenable repaint})
      : super(repaint: repaint);

  @override
  void paint(Canvas canvas, Size size) {
    textPainter.paint(canvas, Offset(0, 0));
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return false;
  }
}
```

**Comment by mdebbar** [comment]
@stuz5000 please use the `--dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true` as explained in the description of this issue.

**Comment by stuz5000** [comment]
I had tried the same within Android Studio...

![image](https://user-images.githubusercontent.com/7799980/74499138-a85e4500-4e97-11ea-9524-250420aa6dc9.png)

... (using the Run configuration) and still get the bug. However, when run from the command line as you say, it does indeed fix the problem. Though this sadly this leaves me unable to debug. Looking forward to it moving out of experimental mode. Thanks!

**Comment by mdebbar** [comment]
The flag only works in release mode. I noticed in the screenshot of Android Studio, you aren't using the `--release` flag. That might be the issue.

> Though this sadly this leaves me unable to debug

Could you elaborate a little more on why you aren't able to debug? Is it because the JS is minified? If so, try using `--profile` instead of `--release`, and that will prevent minification.

**Comment by stuz5000** [comment]
Running from the commandline prevents breakpoints form being set from Android Studio IDE, and it doesn't send out/err back.  (Adding --release in Studio works, I assumed it was already added for Run configs.). I think if its working this way, though we might go ahead and try to ignore it while we're developing and keep it as a matter of faith that it will work when we do our release build.

Anyhow, thanks for the help - looking forward to be able to interact with multi-line text in browsers in the near future.

**Comment by cgestes** [comment]
I am very much looking forward to fixing this issue, it is preventing https://github.com/memspace/zefyr (the only rich text editor I know of) from working correctly on the web. Rich text measurement always returns 0 on the web :(

I am willing to help fixing this issue, if you provide some guidance.
(I tried the experimental flags and it doesn't change my issue, rich text measurement seems totally un-implemented).

I can start by writing a test case if it helps.

Also how are we supposed to set flags in debug and profile? (I do set them directly in the engine code but its a bit annoying when I am not working on the engine).

Thanks, keep the great work :)

**Comment by stuz5000** [comment]
Is anyone working on this? Would it make sense to have a community Canvas TextPainter that works while we're waiting for a fix?

**Comment by michaelchiowong** [comment]
When I enable this experimental mode as execute(flutter build web --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true), I figure out some other text gets shown in strange way if there are some icon-style characters. Please see below screenshot. If  I simply execute flutter build web, then the textfield would show correctly, but the multiline selection textfield would broken. Can you suggest solution on this?

![Screen Shot 2020-04-08 at 12 05 04 PM](https://user-images.githubusercontent.com/49760147/78743457-43076b80-7991-11ea-96c7-503b8d7f4f0c.png)

**Comment by mdebbar** [comment]
@michaelchiowong I think what you are referring to is captured by this issue: https://github.com/flutter/flutter/issues/40221.

**Comment by kunit1** [comment]
I tried enabling this flag and observed the following issue:
The cursor does not move forward when pressing the space bar. The cursor will only jump forward after typing the next non-space character.

**Comment by michaelchiowong** [comment]
> I tried enabling this flag and observed the following issue:
> The cursor does not move forward when pressing the space bar. The cursor will only jump forward after typing the next non-space character.

yes. i also have this problem. Space key has issue during editing the last line.

**Comment by michaelchiowong** [comment]
> #40221

ok. thanks. will follow up with that issue number.

**Comment by michaelchiowong** [comment]
I found one more bug regarding this fix:
if the multi-line textfield has over-flow content, the scrollbar does not work. in the screenshot, we have 4 point, but we can only see point 1, 2, and 3.

![Screen Shot 2020-04-10 at 5 22 56 PM](https://user-images.githubusercontent.com/49760147/78980168-edc58880-7b4f-11ea-8c34-194ab395e20b.png)

**Comment by mdebbar** [comment]
Scrolling is tracked in this issue: https://github.com/flutter/flutter/issues/41630

**Comment by Levi-Lesches** [comment]
Thanks so much, this fixes my problem! Can we have an update when this makes it out of experimental?

**Comment by kunit1** [comment]
@Levi-Lesches That's cause you're now using Release mode instead of debug when enabling this flag. Hence, reloading is basically rebuilding the entire application again.

**Comment by Levi-Lesches** [comment]
Is that due to the logic in the code or simply enabling the flag? In other words, will this persist after it is no longer experimental?

**Comment by Levi-Lesches** [comment]
I know this is much less than ideal, but I made my own workaround instead, since this doesn't allow natively copying the selected text. Similar to #55419, I noticed that the only thing blocking native HTML from doing its thing is `user-select: "none"` and `pointer-events: "none"` being set in `<body> tag.

So I created a simple `enable_selection.dart` file that removes those lines from the generated `main.dart.js` file. I'm sure there is probably a reason for it being there, but this works just fine for my use case. Hopefully this helps someone until it can be officially fixed (PR #55419 seems to do the trick).  

```dart
/* 
* Natively highlighting text is broken on Flutter Web. 
* Possible fix at https://github.com/flutter/flutter/pull/55419
* 
* This code is a temporary workaround
*/

import "dart:io";

final File jsFile = File("build/web/main.dart.js");
final List<String> lines = jsFile.readAsStringSync().split("\n");

void main() {
  int finished = 0;
  for (int index = 0; index < lines.length; index++) {
    final String line = lines [index];
    if (line.startsWith(r'k.bm(p,"user-select"')) {  // allowing user to select text
      lines [index] = 'k.bm(p,"user-select","auto")';
      finished++;
    } else if (line.startsWith(r'k.bm(p,"-webkit-user-select"')) {  // Safari ^
      lines [index] = 'k.bm(p,"-webkit-user-select","auto")';
      finished++;
    } else if (line.startsWith(r'k.bm(p,"-ms-user-select"')) {  // Edge/IE ^
      lines [index] = 'k.bm(p,"-ms-user-select","auto")';
      finished++;
    } else if (line.startsWith('C.d.V(g,C.d.N(g,"pointer-events")')) {  // catching pointer events
      lines [index] = 'C.d.V(g,C.d.N(g,"pointer-events"),"auto","")';
      finished++;
    } else if (finished == 4) {
      break;
    }
  }
  if (finished != 4) {
    throw StateError("Could not make modifications");
  }
  jsFile.writeAsStringSync(lines.join("\n"));
}
```

**Comment by 1g0rrr** [comment]
Is it possible to turn on this flag for debug builds too? This will allow us to make hot reloads. Any reason against this?

**Comment by JacquesCherbuin** [comment]
When using the experimental canvas text, typing a space only moves the cusor sometimes. Letters and numbers work fine, but the spacebar doesn't move the cursor. Also, if you put the cursor in the middle of a word and then press spacebar, it bugs out and moves the cursor to the end of the word.

**Comment by stuz5000** [comment]
Is anyone working on this? Its a major bug that's been open for more than a year with little signs of movement.
Is there anything blocking a fix? Anything the community can do to speed up a fix?

**Comment by michaelchiowong** [comment]
Hi, Flutter team,

I am curious that this bug has been here long time(over one year maybe). Is this a problem that fundamental that is hard to fix?

We are using flutter web, and this multi line text input issue is a big issue. We use "flutter build web --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true" as a workaround, but this introduces other issues. 

It will be really a big help if you can fix this issue.

Thanks!

Michael.

**Comment by yizenlim** [comment]
Not able to copy selected texts with FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true

**Comment by sgehrman** [comment]
FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true didn't work for me.

This seems like a show stopper for flutter web.  I can't used TextFields?

**Comment by mdebbar** [comment]
The `FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT` flag is now enabled by default in master.

@michaelchiowong and everyone else, please file all the issues you are seeing so we can track them and fix them.

@yizenlim copying selected text is another issue that is filed here: https://github.com/flutter/flutter/issues/47234

**Comment by dannnnthemannnn** [comment]
Can anyone guide me on how to tell when this functionality makes it to beta? I always see fixes but I don't see anyway of knowing if I have the fix on my local beta branch. I tried running this with the experimental flag = true but multiline text is still not highlightable.
