### ISSUE TITLE
Planned Cupertino Library Features Jul-Sept 2019

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#35026]
This issue represented Cupertino library work we'd planned to undertake from July-September 2019. It has been replaced by a new similar issue that covers October-December 2019. If you're interested in voting or commenting on our latest plans please review https://github.com/flutter/flutter/issues/43041.

During the period covered by this issue we accomplished a subset of what we'd hoped to do. Here's a summary; see below for details.

- Significant progress on dark mode support.
- Significant progress up on the updated Switch component.

In the same time we landed [46 pull requests](https://github.com/flutter/flutter/pulls?utf8=%E2%9C%93&q=repo%3Aflutter%2Fflutter+label%3A%22f%3A+cupertino%22+type%3Apr+merged%3A2019-07-01..2019-10-04) and [closed 30 issues](https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=repo%3Aflutter%2Fflutter+label%3A%22f%3A+cupertino%22+is%3Aissue+closed%3A2019-07-01..2019-10-04). Many of the issues, and some of the pull requests were provided by developers outside of the Flutter team within Google. We thank you-all for that!

There's a similar list of Material library features, see <a href="https://github.com/flutter/flutter/issues/43035">#43035</a>.

## Dark mode (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60052238-953d0180-9689-11e9-826a-a7e6833020a9.png" />
Support iOS13's dark mode and dynamic system  colors.

 - [x] CupertinoDynamicColor, CupertinoSystemColors, <a href="https://github.com/flutter/flutter/pull/37719">#37719</a>, <a href="https://github.com/flutter/flutter/pull/39927">#39927</a>, <a href="https://github.com/flutter/flutter/pull/39430">#39430</a>.
 - [x] CupertinoButton and (bottom) CupertinoTabBar, <a href="https://github.com/flutter/flutter/pull/39765">#39765</a>.
 - [x] CupertinoActionSheet, CupertinoActionDialog <a href="https://github.com/flutter/flutter/pull/39215">#39215</a>, https://github.com/flutter/flutter/pull/40007.
 - [x] CupertinoActivityIndicator and CupertinoApp, <a href="https://github.com/flutter/flutter/pull/39289">#39289</a>.
  
## Modal presentations (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60052501-480d5f80-968a-11e9-9b71-b0e0e26f22bb.png" />
Shows a new view on top of the current view that looks like a stacked card.

  * https://github.com/flutter/flutter/issues/33799
  * https://github.com/flutter/flutter/issues/33798
  * https://github.com/flutter/flutter/issues/42560

## Context menus (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60053978-17c7c000-968e-11e9-99d1-f95163bbceb5.png" />
Similar to “peek and pop”, but don’t rely on 3D touch.

  * https://github.com/flutter/flutter/issues/34728
## Text Editing Gestures (iOS 13)
<img width="200" src="https://user-images.githubusercontent.com/389558/60058693-4483d380-969e-11e9-9499-fa3a074a5637.PNG" />
Various new gestures related to text editing.  See the issue for details.

  * https://github.com/flutter/flutter/issues/34749
## New CupertinoSwitch (iOS 13)
<img width="394" alt="Screen Shot 2019-06-24 at 3 14 36 PM" src="https://user-images.githubusercontent.com/389558/60055566-dede1a00-9692-11e9-8c84-7ae609bf4a11.png">
Simple visual change.

  * :heavy_check_mark: https://github.com/flutter/flutter/issues/33797
  * Background color dark mode problem: https://github.com/flutter/flutter/issues/37312
  * Accessibility: https://github.com/flutter/flutter/issues/4830

## New SegmentedControl (iOS 13)
<img width="402" alt="Screen Shot 2019-06-24 at 3 14 32 PM" src="https://user-images.githubusercontent.com/389558/60055565-de458380-9692-11e9-9aed-3ce5fd598f82.png">

  * https://github.com/flutter/flutter/issues/33796
## Support SF Symbols (iOS 13)
<img width="200" src="https://developer.apple.com/design/human-interface-guidelines/sf-symbols/images/sf-symbols-scales-weights_2x.png" />
New icons

  * https://github.com/flutter/flutter/issues/33916
## Long press and drag to select text (iOS 13)
<img width="200" src="https://user-images.githubusercontent.com/389558/60037987-ec31df00-9667-11e9-9b27-121f0c939585.gif" />
Should be same selection gesture as Android.

  * https://github.com/flutter/flutter/issues/35010
## ✔️ Draggable scrollbar (iOS 13)
<img width="100" src="https://user-images.githubusercontent.com/389558/60194883-034f0900-97ef-11e9-991b-1f1e40e8117e.gif" />
<p></p>
It's possible to drag the scrollbar by long-pressing or dragging in from the right.

 - [x] iOS 13 scrollbar, <a href="https://github.com/flutter/flutter/pull/35829">#35829</a>.
 - [x] iOS 13 scrollbar vibration, <a href="https://github.com/flutter/flutter/pull/37724">#37724</a>.

## ~~Loupe magnifying glass for text cursor~~
Long press on text to show a loupe that zooms in on the cursor.
This was actually removed from iOS 13 by Apple!

  * https://github.com/flutter/flutter/issues/9507
## CupertinoSearchBar
<img width="140" src="https://developer.apple.com/design/human-interface-guidelines/ios/images/SearchBar_Prominent_2x.png" />
Similar to Material's SearchDelegate etc.

  * https://github.com/flutter/flutter/issues/9784

**Comment by davidlantrip** [comment]
The scrubbable scroll bar is iOS 13 would be nice to have. Since it looks like it's going to be the default behavior for UIScrollView, it would help maintain 'normal' iOS app expectations. It's also a pretty slick way to quickly go through a scrollview.

**Comment by justinmc** [comment]
@davidlantrip Thanks for pointing that out, I wasn't aware!  I'll add it.

**Comment by vanelizarov** [comment]
Guys, I’ve just released plugin [flutter_ios_dark_mode](https://pub.dev/packages/flutter_ios_dark_mode) that allows to check if iOS 13 Dark Mode is currently in enabled state or not and subscribe to this state changes. PRs and suggestions are highly appreciated 🙂

[Plugin’s Github repo](https://github.com/vanelizarov/flutter_ios_dark_mode)

**Comment by eliezedeck** [comment]
Context Menu, Search Bar please.

**Comment by orestesgaolin** [comment]
Woah, there's a lot of possibilities there!

In my opinion one of the most important features of iOS apps is text handling. Both manipulation of text in various inputs, and also selection in simple text views. Features like magnifying glass or text editing gestures would be the most important for me.

**Comment by drys262** [comment]
Search Bar please

**Comment by duncanhoggan** [comment]
The text editing goodies please!

**Comment by d3xt3r2909** [comment]
Please, text handling. It is critical for every iOS user..

**Comment by wendrpatrck** [comment]
SliverAppBar with search field please! 
![image](https://user-images.githubusercontent.com/35619496/62946357-eaa6ac80-bdb6-11e9-971a-4d994d9818ae.png)

**Comment by EliasDeuss** [comment]
Issue #33873 needs to be added to the list @justinmc

**Comment by bitsydarel** [comment]
@EliasDeuss I think it’s already there (the first item on the list). But I don’t see comment about adding the darkTheme property to the Cupertino app widget, also the darkTheme property on Material app widget need to also work on iOS 13.

**Comment by justinmc** [comment]
@LongCatIsLooong is the above mentioned dark mode stuff on your radar?

**Comment by LongCatIsLooong** [comment]
@justinmc we're already getting it from `MediaQuery.platformBrightness`: https://github.com/flutter/engine/pull/10791

**Comment by justinmc** [comment]
Ah cool, thanks.

**Comment by HansMuller** [comment]
I'm closing this issue, since it's been replaced by an updated planning issue: https://github.com/flutter/flutter/issues/43041.
