### ISSUE TITLE
Upcoming Material Library Features

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#35088]
This issue represented material library work we'd planned to undertake from July-September 2019. It has been replaced by a [new similar issue that covers October-December 2019](https://github.com/flutter/flutter/issues/43035). If you're interested in voting or commenting on our latest plans please review https://github.com/flutter/flutter/issues/43035.

During the period covered by this issue we accomplished a subset of what we'd hoped to do. Here's a summary; see below for details.

 - Support for dark mode per the latest Material spec. 
 - New ToggleButtons widget.
 - Exposed Android 10's system "gesture insets".

Over the same three months we landed [113 pull requests](https://github.com/flutter/flutter/pulls?utf8=%E2%9C%93&q=repo%3Aflutter%2Fflutter+label%3A%22f%3A+material+design%22+-label%3A%22f%3A+cupertino%22+type%3Apr+merged%3A2019-07-01..2019-10-04) and [closed 146 issues](https://github.com/flutter/flutter/pulls?utf8=✓&q=repo%3Aflutter%2Fflutter+label%3A"f%3A+material+design"+-label%3A"f%3A+cupertino"+is%3Aissue+closed%3A2019-07-01..2019-10-04). Most of the issues, and some of the pull requests were provided by developers outside of the Flutter team within Google. We thank you-all for that!

Features for which the work is now relatively complete are marked with ✔️. 

There's a similar list of Cupertino library features, see <a href="https://github.com/flutter/flutter/issues/35026">#35026</a>.

 ## ✔️ **Dark Mode**

<p>
Existing support to be updated per the latest <a href="https://material.io/design/color/dark-theme.html">Material spec</a>.
</p>
<img width="400" src="https://user-images.githubusercontent.com/1377460/60136668-a8b79d80-9759-11e9-8499-d4b595880e45.png" />
<p></p>

 - [x] Updated ColorScheme.dark(), <a href="https://github.com/flutter/flutter/pull/36106">#36106</a>.
 - [x] Material widget's color now changes per elevation in dark mode, <a href="https://github.com/flutter/flutter/pull/35560">#35560</a>.
 - [x] SnackBar dark mode updates, <a href="https://github.com/flutter/flutter/pull/37038">#37038</a>.
 - [x]  Added ThemeData.from(): Construct a Theme from a ColorScheme, <a href="https://github.com/flutter/flutter/pull/37355">#37355</a>.
 - [x] Added MaterialApp.themeMode to sync the app with the system dark mode setting, <a href="https://github.com/flutter/flutter/pull/35499">#35499</a>, <a href="https://github.com/flutter/flutter/pull/36399">#36399</a>.

 ## **Updated Date Picker**
<p>
An improved UI that handles small screens better and supports selecting date intervals.
</p>
<img width="200" src="https://user-images.githubusercontent.com/1377460/60137155-f41e7b80-975a-11e9-85f3-f2d88ffcc8ca.png" />
<p></p>

 - [x] Improve small screen layout, <a href="https://github.com/flutter/flutter/pull/31514">#31514</a>.
 - [x] Increase TimePicker touch targets, <a href="https://github.com/flutter/flutter/pull/32053">#32053</a>.
 - [x] TimePicker moves to minute mode after hour selection, <a href="https://github.com/flutter/flutter/pull/31566">#31566</a>.

 ## **Search Bar**
<p>
Support for "persistent search" per the <a href="https://material.io/design/navigation/search.html#persistent-search">Material spec</a>. There's an existing <a href="https://github.com/flutter/flutter/issues/17119">issue</a> for this.
</p>
<img width="400" src="https://user-images.githubusercontent.com/1377460/60137365-858ded80-975b-11e9-901e-022ba7d5bee5.png" />
<p></p>
 
 ## ✔️ **Toggle Button** 
<p>
Also called a "Segmented Control". Defined in the <a href="https://material.io/design/components/buttons.html#toggle-button">Material spec</a>. 
</p>
<img width="400" src="https://user-images.githubusercontent.com/1377460/60137444-bff78a80-975b-11e9-8d54-a1774eb67bfb.png" />
<p></p>

 - [x] Added ToggleButtons widget, <a href="https://github.com/flutter/flutter/pull/34599">#34599</a>.
 - [x] Added ToggleButtons.textStyle, <a href="https://github.com/flutter/flutter/pull/38813">#38813</a>.
 - [x] ToggleButtons testing and docs, <a href="https://github.com/flutter/flutter/pull/38898">#38898</a>, <a href="https://github.com/flutter/flutter/pull/38635">#38635</a>.
 - [x] - Toggle button minimum size constraints, <a href="https://github.com/flutter/flutter/pull/39857">#39857</a>.

 ## **Reorderable List Animation**
<p>
Improved interaction drag and drop animation, support for animating insert and remove.
</p>
<img width="200" src="https://user-images.githubusercontent.com/1377460/60137414-ac4c2400-975b-11e9-8fe4-234066a419c1.png" />
<p></p>

 ## **Android Q Navigation**
<p>
Android Q can reserve swipe gestures that are initiated from the edges of the screen for system navigation. Apps will need to be aware of the system's "gesture insets" and the Scaffold drawer will have to accommodate them. 

An overview of the work planned for Android Q (now "Android 10") is here: <a href="https://github.com/flutter/flutter/issues/39858">Android 10 / Android Q Issues and Features</a>.
</p>
<img width="200" src="https://user-images.githubusercontent.com/1377460/60525961-3d635380-9ca4-11e9-9c05-24a1f364b83c.png" />
<p></p>

 - [x] Add MediaQuery.systemGestureInsets to support Android Q, <a href="https://github.com/flutter/flutter/pull/37416">#37416</a>.
 - [x] (Engine) systemGestureInsets, <a href="https://github.com/flutter/engine/pull/10413">engine/10413</a>.
 - [x] (Engine) systemGestureExclusionRects, <a href="https://github.com/flutter/engine/pull/11441">engine/11441</a>, <a href="https://github.com/flutter/engine/pull/11451">engine/11451</a>.

**Comment by byshy** [comment]
maybe create a listview that has a feature of enabling the user to select multiple items inside it and give the developer the freedom to implement the actions to manipulate the selected items

**Comment by rknell** [comment]
Calendar controls would be the hardest for me to get right, the rest I could hack together and feel like it would work, but a top notch calendar (would love a good time picker to work with it) would be awesome

**Comment by JaspervanRiet** [comment]
We have built a date picker with almost the exact functionality shown here, using some code from the current date picker (but turning it into a vertically scrolling and interval supporting version). However, achieving good performance with that widget is rather hard, so we would welcome an official version.

That said, I feel the priority should be on Android Q navigation since it's quite obviously vital to have that working.

**Comment by mlican** [comment]
There is some jitter in Flutter ListView scrolling, and the scrolling speed is a little slow. It is hoped that it will be further optimized.

**Comment by MichaelPriebe** [comment]
The built in search widgets are just down right awful! Everything is hard-coded, plus I've never seen an app actually use a search page that looked like that. The Persistent Search is VERY needed.

**Comment by Waffulz** [comment]
This is hard though. Im between date picker, toggle button and search bar.

**Comment by mdrideout** [comment]
Date picker please!

**Comment by codinesh** [comment]
Dark mode and date picker please.

**Comment by kolmakovruslan** [comment]
Calendar, search bar

**Comment by rahulraj64** [comment]
I think you missed one of the most important widgets which play a crucial role in user-friendliness, which is 'Feature discovery'.

**Comment by TahaTesser** [comment]
Search Bar  & Toggle Button

**Comment by amugofjava** [comment]
Search Bar gets my vote. This is such a common widget in apps this would be extremely useful and time saving.

**Comment by amrfarid140** [comment]
Reorderable List Animation and date picker are the most needed ones for me.

**Comment by PieterAelse** [comment]
In order: Android Q Navigation support, SearchBar, Reorderable List Animation and DatePicker

(or was I supposed to pick only one? 😝)

**Comment by iceman750** [comment]
Search bar and then Dark mode!!! 😋

**Comment by orestesgaolin** [comment]
In our apps there was always a discussion about proper date picker so I would love to see a good quality and versatile date picker from Flutter team. 

Search and dark mode with system support would be also important to me.

**Comment by drys262** [comment]
Search Bar and Date Picker

**Comment by jffiorillo** [comment]
"persistent search" per the [Material spec](https://material.io/design/navigation/search.html#persistent-search) please.

**Comment by MichaelPriebe** [comment]
Let's get these features a'cookin'!

**Comment by laxxxguy** [comment]
date range picker is very necessary component. i am glad you thought that.

**Comment by HansMuller** [comment]
I'm closing this issue, since it's been replaced by an updated planning issue: https://github.com/flutter/flutter/issues/43035.
