### ISSUE TITLE
Updating vignettes in gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4120]
- [ ] removing weather (which was blocked by https://github.com/flutter/flutter/issues/3804 and https://github.com/flutter/flutter/issues/3808 and https://github.com/flutter/flutter/issues/3805)

- [ ] removing jumping jacks (which was blocked on https://github.com/flutter/flutter/issues/2459)

- [x] removing fancy lines (which was blocked on https://github.com/flutter/flutter/issues/3781)

**Comment by sethladd** [comment]
@Hixie did you want to make copies of these?

cc @HansMuller for where to put these in the meantime.

**Comment by Hixie** [comment]
Haven't touched these. I thought Hans was going to do it. :-) It should be pretty easy. I'd start with cloning the entire gallery into dev/manual_tests, then removing everything from there except the bits we are removing from the gallery, then removing just those bits from the actual gallery, such that the app is split cleanly into two almost completely different parts with nothing but the core skeleton in common.

Then I'd make sure all the bugs above are still visible on the new test app.

I can do this if you want but it'd be below three other things on my list. Let me know.

**Comment by HansMuller** [comment]
Hans is planning to do it. Just wanted to get Shrine v0 finished first.

**Comment by sethladd** [comment]
Thanks for the update! Makes sense.
