### ISSUE TITLE
Samsung Keyboard bugs [Tracking Issue]

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#42273]
This issue is to create a central place to track the various issues related to Samsung's keyboard and how it works in Flutter:

- [x] https://github.com/flutter/flutter/issues/31512 [Partial workaround in place] Flutter TexField and TextFormField duplicates text when using initial value or controller to set initial text.
- [x] https://github.com/flutter/flutter/issues/51893 Samsung keyboard composing region duplication on subset of devices
- [x] https://github.com/flutter/flutter/issues/41990 Ordering of IMM calls
- [x] https://github.com/flutter/flutter/issues/30656 Samsung Handwriting issues
- [x] https://github.com/flutter/flutter/issues/29341 Korean characters are displayed abnormally in TextField when moved cursor.
- [x] https://github.com/flutter/flutter/issues/41315 Textinput bug on Samsung device (deduped)
- [x] https://github.com/flutter/flutter/issues/53052 Obscured change freezes app and keyboard
- [x] https://github.com/flutter/flutter/issues/49796 Return key not working - Not restricted to Samsung
- [x] https://github.com/flutter/flutter/issues/53612 Samsung Keyboard crash/freeze when dismissing and reopening keyboard

https://github.com/flutter/flutter/issues/41990 "Ordering of IMM calls" has high potential to be the root cause of many of these bugs. (update: this was not the case)

Cleanup (not real issues):

- [ ] https://github.com/flutter/flutter/issues/54245 Cleanup redundant workarounds

It has been shown that restarting the IMM is not sufficient to fix all of these, as it is effective in only a few scenarios. I suspect some may require the root fix to resolve fully.

**Comment by Hixie** [comment]
(removing customer critical label since there's no customer label)

**Comment by GaryQian** [comment]
I have reordered the IMM calls in https://github.com/flutter/flutter/pull/43865, however it does not seem to have resolved this.

**Comment by timsneath** [comment]
Customer label added. (The underlying bugs had the customer label added.)

**Comment by Kiboom** [comment]
A lot of users are having trouble with writing text, which is just the most basic function of the app.
I know you're working on the issue hard, but please deal with this issue as soon as possible 🙏
I can't believe we have to wait for this issue to be resolved until May.

**Comment by Rossdex** [comment]
Hi,

I've had a few issues on Samsung devices where using TextCapitalization.sentences causes the capitalization to be the opposite of what is intended. 

E.g. you will get 'tHis iS mY tEST sENTENCE' rather than 'This is my test sentence'. 

This is only happening on Samsung devices and is only present when using the default Samsung keyboard. The current workaround I am having to use is TextCapitalization.none however this is far from ideal. 

`TextField(
        maxLines: 10,
        keyboardType: TextInputType.multiline,
        textCapitalization: TextCapitalization.sentences,
        controller: controller,
        onChanged: (newValue) {
       
        },
      )`

**Comment by GaryQian** [comment]
@Rossdex Thanks for reporting this! This is actually the first I have seen this issue reported, so do you think you can file a separate issue regarding this and link it here?

It would be very helpful if you could provide a minimal reproduction of the bug as well as the exact device/OS/etc you are able to reproduce this on.

**Comment by crtl** [comment]
The return key is not working on samsung keyboards.
Tested on A320F and A520F (Galaxy A3/A5 2017).

On Pixel 3 emulator it is working.

```
TextField(
  maxLines: 20,
  keyboardType: TextInputType.multiline,
),
```

Pressing the `Return` key has no effect.

I have created a basic demo: [crtl/flutter-text-field-return-demo](https://github.com/crtl/flutter-text-field-return-demo)

```
[√] Flutter (Channel master, v1.15.3-pre.58, on Microsoft Windows [Version 10.0.18362.657], locale en-DE)
    • Flutter version 1.15.3-pre.58 at D:\dev\flutter\sdk
    • Framework revision f769bcc5c4 (6 days ago), 2020-02-10 20:55:48 -0500
    • Engine revision e4f46f32f1
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 fd992e423e)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\dev\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\dev\Android\SDK
    • Java binary at: D:\Programms\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\Programms
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM A520F   • 5210ae1cf4a7448d • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome           • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

```

**Comment by MichelMelhem** [comment]
I'm facing the same issue does someone know if their is a working fix ????
It really annoy me as this is a principal feature of my app :/

**Comment by xster** [comment]
<triage> 
@timsneath is there a subset of this meta bug that are customer blockers? Trying to figure out what are priorities of the remaining items.

**Comment by Inf0rmatix** [comment]
Hi, I have already reported another Samsung keyboard related bug. Those issues are a real problem, since we have already deployed our app and just have to force our users to use the google keyboard since the samsung keyboard doesn't work properly. Please pay attention and fix this asap :)

**Comment by GaryQian** [comment]
@Inf0rmatix Yes, this is currently my active line of work.

**Comment by GaryQian** [comment]
I have landed a fix for https://github.com/flutter/flutter/issues/51893 and it seems to have resolved may of the bugs seen here. I will check on the remaining handwriting issue and hopefully close out this bug soon.

**Comment by GaryQian** [comment]
All the components of this tracker seems to have been resolved. There is currently one remaining outstanding issue I have just filed (https://github.com/flutter/flutter/issues/54310) that was extracted out of one of the other bugs, so we can just track that there directly.

Thanks for everyone's bug reports and patience in dealing with these issues!
