### ISSUE TITLE
Upcoming Material Library Features

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#43035]
This is a list of the new Material library features that we're likely to work on in the next three months. It does not include the ongoing work related to bugs and other existing issues. The goal is to emphasize new widgets and features we're hoping to work on in near term, and to solicit feedback. We'd welcome comments about the features listed here and features we may have missed.

Features for which the work is relatively complete are marked with ✔️. 

This issue obsoletes https://github.com/flutter/flutter/issues/35088, which covered July-September 2019. The comments and votes submitted for #35088 will not be forgotten, we're assuming that they all still apply to this new roll up.

There's a similar list of Cupertino library features, see <a href="https://github.com/flutter/flutter/issues/43041">#43041</a>.

  ## **Updated Date Picker**
<p>
An improved UI that handles small screens better and supports selecting date intervals.
</p>
<img width="200" src="https://user-images.githubusercontent.com/1377460/60137155-f41e7b80-975a-11e9-85f3-f2d88ffcc8ca.png" />
<p></p>
<p>
This project has been underway for a while already. It was announced in <a href="https://github.com/flutter/flutter/issues/35088">September 2019</a>.

 - [x] Improve small screen layout, <a href="https://github.com/flutter/flutter/pull/31514">#31514</a>.
 - [x] Increase TimePicker touch targets, <a href="https://github.com/flutter/flutter/pull/32053">#32053</a>.
 - [x] TimePicker moves to minute mode after hour selection, <a href="https://github.com/flutter/flutter/pull/31566">#31566</a>.

 ## **Text Selection Menu update**
The current text selection menu is lacking in terms of native fidelity and flexibility. For example:
https://github.com/flutter/flutter/issues/35826,  https://github.com/flutter/flutter/pull/39624 https://github.com/flutter/flutter/issues/24407. The overall goal here is to closely match the native platforms in terms of visuals, behavior, and flexibility.

## **Autofill Support**
The overall goal for this project will be to add engine support for the native autofill services, provide an SDK widget that exposes the autofill service data, and integrate autofill with the default text selection menu.

There is strong interest in this feature: <a hef="https://github.com/flutter/flutter/issues/13015">#13015</a>

## Rotate/Pan/Zoom Widget
A demo of such a widget was included in the Flutter gallery nearly a year ago. This generally useful (and difficult to write) widget will be extracted from the gallery demo and folded into the SDK. 

<img width="200" src="https://user-images.githubusercontent.com/1377460/67132971-a3c2a200-f1bf-11e9-9053-565fb38fe56a.png" />

<p></p>

## **Simplified I18N Process**
<p>
Apps will use a tool to generate a localized resources class from handwritten application resource bundle (".arb") files, one per supported locale.
</p>
<p>
There's a relatively detailed proposal  in <a href="https://github.com/flutter/flutter/issues/41437">#41437</a>. This feature applies to both the Cupertino and Material libraries.

## **Search Bar**
<p>
Support for "persistent search" per the <a href="https://material.io/design/navigation/search.html#persistent-search">Material spec</a>. There's an existing <a href="https://github.com/flutter/flutter/issues/17119">issue</a> for this.
</p>
<img width="400" src="https://user-images.githubusercontent.com/1377460/60137365-858ded80-975b-11e9-901e-022ba7d5bee5.png" />
<p></p>
 
 ## **Reorderable List Animation**
<p>
Improved interaction drag and drop animation, support for animating insert and remove.
</p>
<img width="200" src="https://user-images.githubusercontent.com/1377460/60137414-ac4c2400-975b-11e9-8fe4-234066a419c1.png" />
<p></p>

 ## ✔️ **Android 10 Route Transition Animation**
<p>
The default route transition animation needs to be updated for Android 10.
</p>
<p>
An overview of the work planned for Android Q (now "Android 10") is here: <a href="https://github.com/flutter/flutter/issues/39858">Android 10 / Android Q Issues and Features</a>
</p>
<img width="200" src="https://user-images.githubusercontent.com/27032613/66861471-f001ae00-ef43-11e9-88a3-47761f246818.gif"/>
<p></p>

 - [x] [Android 10] Activity zoom transition, <a href="https://github.com/flutter/flutter/pull/41935">#41935</a>.

 ## **Systematic Fidelity Measurement and Tracking**
Measure look and feel fidelity by comparing Flutter with native apps. This process needs to be part of post-submit testing; just like performance benchmarking.

The goal is to verify that a user can not distinguish between native and Flutter apps for visuals and behaviors that are intended to match their native counterparts.

 This project applies to both the Cupertino and Material libraries.

**Comment by MichaelPriebe** [comment]
🚀

**Comment by Zazo032** [comment]
I think the Date Picker now follows system's accent color (at least in Android 10). Will this feature added to the widget? Maybe it's present in other widgets, or even that accent color could be access (Android 10+) over `SystemChrome` widget.

**Comment by GregorySech** [comment]
Is autofill gonna be supported in Cupertino too?

**Comment by justinmc** [comment]
@GregorySech Yes!  I just added it to the corresponding Cupertino issue: https://github.com/flutter/flutter/issues/43041

**Comment by SwissCheese5** [comment]
Multiple date selection should be added as well. Many people have a use case for this.

**Comment by justinmc** [comment]
@darrenaustin is multiple date selection something you're aware of?

**Comment by zerox1212** [comment]
Can we please have a generic "picker/spinner" for Android/Material Design? We have a Cupertino picker.

I just want to supply a list of strings to fill a picker. The 3rd party options leave a lot to be desired or cause build issues.

**Comment by Levi-Lesches** [comment]
You could use [`showBottomSheet`](https://api.flutter.dev/flutter/material/ScaffoldState/showBottomSheet.html) to show a `ListView` on the bottom part of the screen.

**Comment by zerox1212** [comment]
> You could use [`showBottomSheet`](https://api.flutter.dev/flutter/material/ScaffoldState/showBottomSheet.html) to show a `ListView` on the bottom part of the screen.

ListView is an option, but having a picker widget fits the flutter fast-design theme and the functionality itself is widespread in general. It was important enough to add a Cupertino widget at any rate.

**Comment by Levi-Lesches** [comment]
I still think `ListView` is enough to cover the Material Design standards. Cupertino does need its own widget to implement the different scrolling animation (it looks like it's rotating instead of simply moving -- see [`ListWheelScrollView`](https://api.flutter.dev/flutter/widgets/ListWheelScrollView-class.html)). For Material Design, all you really need is just a standard list.

**Comment by darrenaustin** [comment]
> @darrenaustin is multiple date selection something you're aware of?

We have been thinking about it. However, we don't currently have a UI design for this from the Material team. The current plan is to implement the design they do have for the ranged date picker, and take it from there. I will make sure this feedback gets to the design team and see what they think.

**Comment by kaarens93** [comment]
hi, wanted to see where the team's at with autofill
know you guys are working hard but this is a very important feature

**Comment by roman-petrov** [comment]
Just found a possible related issue with `InkSplash`/`InkRipple` Flutter animations which differs from native animation in Android. There are a couple of Flutter issues:

- [InkWell and InkResponse not close enough to the real thing](https://github.com/flutter/flutter/issues/20922)
- [Add ripple effect style of new Android versions](https://github.com/flutter/flutter/issues/49957)

Maybe these issues also should be added to this proposal somehow?

**Comment by justinmc** [comment]
@roman-petrov Thanks for bringing that up.  I think the author of the second issue there had a solution in a gist, I'll try to get a pull request opened for that.

**Comment by GroovinChip** [comment]
Hi, any progress on #31247?

**Comment by HansMuller** [comment]
Closing this issue; please look to the linked issues and PRs for updates about progress, or to provide additional feedback.
