### ISSUE TITLE
Upcoming Cupertino Library Features

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#43041]
This is a list of the new Cupertino library features that we're likely to work on in the next three months. It does not include the ongoing work related to bugs and other existing issues. The goal is to emphasize new widgets and features we're hoping to work on in near term, and to solicit feedback. We'd welcome comments about the features listed here and features we may have missed.

Features for which the work is relatively complete are marked with ✔️. 

This issue obsoletes https://github.com/flutter/flutter/issues/35026, which covered July-September 2019. The comments and votes submitted for #35026 will not be forgotten, it's assumed that they all still apply to this new roll up.

There's a similar list of Material library features, see <a href="https://github.com/flutter/flutter/issues/43035">#43035</a>.

##  ✔️ Dark mode (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60052238-953d0180-9689-11e9-826a-a7e6833020a9.png" />

Support iOS13's dark mode and dynamic system  colors.

This project has been underway for a while already. It was announced in <a href="https://github.com/flutter/flutter/issues/35026">September 2019</a>.

 - [x] CupertinoTheme & CupertinoTextTheme dark mode updates, <a href="https://github.com/flutter/flutter/pull/41859">#41859</a>.
 - [x] CupertinoDynamicColor, CupertinoSystemColors, <a href="https://github.com/flutter/flutter/pull/37719">#37719</a>, <a href="https://github.com/flutter/flutter/pull/39927">#39927</a>, <a href="https://github.com/flutter/flutter/pull/39430">#39430</a>.
 - [x] CupertinoButton and (bottom) CupertinoTabBar, <a href="https://github.com/flutter/flutter/pull/39765">#39765</a>.
 - [x] CupertinoActionSheet, CupertinoActionDialog <a href="https://github.com/flutter/flutter/pull/39215">#39215</a>, https://github.com/flutter/flutter/pull/40007.
 - [x] CupertinoActivityIndicator and CupertinoApp, <a href="https://github.com/flutter/flutter/pull/39289">#39289</a>.
 - [x] Dark Mode R: Refresh Control, <a
href="https://github.com/flutter/flutter/pull/40454">#40454</a>.
 - [x] Dark mode CupertinoNavigationBar, <a
href="https://github.com/flutter/flutter/pull/40189">#40189</a>.
 - [x] Dark mode for CupertinoSwitch and CupertinoScrollbar, Fidelity updates, <a
href="https://github.com/flutter/flutter/pull/40636">#40636</a>.
 - [x] CupertinoPageScaffold dark mode, <a
href="https://github.com/flutter/flutter/pull/40690">#40690</a>.
 - [x] Remove CupertinoSystemColors in favor of CupertinoColors, <a
href="https://github.com/flutter/flutter/pull/40566">#40566</a>.
  - [x] CupertinoDatePicker & CupertinoTimerPicker dark mode, <a
href="https://github.com/flutter/flutter/pull/39919">#39919</a>.
  - [x] Cupertino { TabScafold, TextSelection, TextField } dark mode & minor fidelity update, <a
href="https://github.com/flutter/flutter/pull/41431">#41431</a>.
  - [x] CupertinoTheme & CupertinoTextTheme dark mode updates, <a
href="https://github.com/flutter/flutter/pull/41859">#41859</a>.

## Modal presentations (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60052501-480d5f80-968a-11e9-9b71-b0e0e26f22bb.png" />

Shows a new view on top of the current view that looks like a stacked card.

 * https://github.com/flutter/flutter/issues/33799
 * https://github.com/flutter/flutter/issues/33798
 * https://github.com/flutter/flutter/issues/42560

## ✔️ Context menus (iOS 13)
<img height="200" src="https://user-images.githubusercontent.com/389558/60053978-17c7c000-968e-11e9-99d1-f95163bbceb5.png" />
Similar to “peek and pop”, but don’t rely on 3D touch.

This project has been underway for a while already. It was announced in <a href="https://github.com/flutter/flutter/issues/35026">September 2019</a>.

 - [x] https://github.com/flutter/flutter/pull/37778

## Text Editing Gestures (iOS 13)
<img width="200" src="https://user-images.githubusercontent.com/389558/60058693-4483d380-969e-11e9-9499-fa3a074a5637.PNG" />
Various new gestures related to text editing.  

 * https://github.com/flutter/flutter/issues/34749.

## ✔️ New CupertinoSwitch (iOS 13)
<img width="394" alt="Screen Shot 2019-06-24 at 3 14 36 PM" src="https://user-images.githubusercontent.com/389558/60055566-dede1a00-9692-11e9-8c84-7ae609bf4a11.png">

 - [x] https://github.com/flutter/flutter/pull/36087
 - [x] https://github.com/flutter/flutter/pull/40636
 - [ ] https://github.com/flutter/engine/pull/12404 (Landed and reverted. When this is re-landed, see comment on original PR about the duplicate notification registration)

## ✔️ New SegmentedControl (iOS 13)
<img width="402" alt="Screen Shot 2019-06-24 at 3 14 32 PM" src="https://user-images.githubusercontent.com/389558/60055565-de458380-9692-11e9-9aed-3ce5fd598f82.png">

This project has been underway for a while already. It was announced in <a href="https://github.com/flutter/flutter/issues/35026">September 2019</a>.

 - [x] https://github.com/flutter/flutter/pull/42775

## **Simplified I18N Process**
<p>
Apps will use a tool to generate a localized resources class from handwritten application resource bundle (".arb") files, one per supported locale.
</p>
<p>
There's a relatively detailed proposal  in <a href="https://github.com/flutter/flutter/issues/41437">#41437</a>. This feature applies to both the Cupertino and Material libraries.
  
## Support SF Symbols (iOS 13)
<img width="200" src="https://developer.apple.com/design/human-interface-guidelines/sf-symbols/images/sf-symbols-scales-weights_2x.png" />

 * https://github.com/flutter/flutter/issues/33916

## Long press and drag to select text (iOS 13)
<img width="200" src="https://user-images.githubusercontent.com/1377460/67131756-ba1a2f00-f1ba-11e9-8cba-80fa21c832f8.gif"/>
Should be same selection gesture as Android.

 * #35010

## CupertinoSearchBar
<img width="140" src="https://developer.apple.com/design/human-interface-guidelines/ios/images/SearchBar_Prominent_2x.png" />
Similar to Material's SearchDelegate etc.

  * https://github.com/flutter/flutter/issues/9784

 ## **Systematic Fidelity Measurement and Tracking**
Measure look and feel fidelity by comparing Flutter with native apps. This process needs to be part of post-submit testing; just like performance benchmarking.

The goal is to verify that a user can not distinguish between native and Flutter apps for visuals and behaviors that are intended to match their native counterparts.

 This project applies to both the Cupertino and Material libraries.

## Autofill Support ✔️ 
The overall goal for this project will be to add engine support for the native autofill services, provide an SDK widget that exposes the autofill service data, and integrate autofill with the default text selection menu.

This is also part of the [upcoming Material features](https://github.com/flutter/flutter/issues/43035).

  * https://github.com/flutter/flutter/issues/13015
  * https://github.com/flutter/flutter/issues/33040

**Comment by bitsydarel** [comment]
Simplified I18N Process

Can this task also take care of updating the info.plist about the supported languages so that we won’t have to do it manually for iOS?

**Comment by GregorySech** [comment]
Is autofill blocked for cupertino?

**Comment by HansMuller** [comment]
@bitsydarel - That's a good idea. Could you add a comment to #41437?

**Comment by justinmc** [comment]
@GregorySech Autofill is not blocked for Cupertino.  I just added a section above about it.  Hopefully a lot of the work for autofill for Material and Cupertino is able to be shared, besides the native platform code.

**Comment by bitsydarel** [comment]
Yes sure

**Comment by cbracken** [comment]
@HansMuller I've unchecked the checkbox for flutter/engine#12404, since it was reverted. I've also added a note about a fix that will be required in two places: beside the checkbox, and on the original PR.

**Comment by genert** [comment]
Any way to help with autofill support for Cupertino?

**Comment by justinmc** [comment]
@genert Let's discuss on the main Autofill issue, I just posted here: https://github.com/flutter/flutter/issues/13015#issuecomment-548932823

**Comment by lanmonster** [comment]
Is there a scheduled time when these features will be released? just looking for a rough estimate (days, weeks, months, ...)

**Comment by justinmc** [comment]
@lanmonster The features with a ✔️ have been released in master (there are links to the PRs above if you need to know the exact versions).  For those without a check yet, take a look at the linked issues and follow the progress in there.  Dark Mode and Modal Presentations are both under active development and have linked PRs too, for example.  Others will probably get picked up after those two are done, probable on a "months" timeline unless someone steps in and wants to work on them.

**Comment by vanlooverenkoen** [comment]
@justinmc any idea when ModalPresentations will be implemented? This ticket is not updated for a long time

**Comment by justinmc** [comment]
Unfortunately I was only able to do some initial investigation for ModalPresentations before I had to focus on other things, so it's not going to be soon.  The issue mentioned for it (https://github.com/flutter/flutter/issues/42560) has a link to a Pub package that might be what you need in the meantime.

**Comment by vanlooverenkoen** [comment]
:( that is sad news. I think the Flutter team should make sure we can also build native looking like apps with Flutter. One of the things we were worried about when taking a look at Flutter were the "native like" widgets provided by the flutter team. This should be a high priority with every design change.

**Comment by justinmc** [comment]
I totally agree and I hope we can get back to this soon.  In the meantime, if you or anyone else cares enough about this feature to implement it yourself, PRs are always welcome and I'd be happy to help out with code review and guidance.

**Comment by adeolaex** [comment]
Is the cupertinoSearchBar in flutter now ?

**Comment by justinmc** [comment]
@adeolaex No, but you can follow https://github.com/flutter/flutter/issues/9784 for any progress.

**Comment by justinmc** [comment]
I'm going to close this as I'm no longer working on planning the high level Cupertino effort.  Check the issues in the original description for any updates on individual features.
