### ISSUE TITLE
☂️ Device-specific keyboard events should happen in the embedder

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#44918]
In order to make implementing https://github.com/flutter/flutter/issues/33521 easier, and because it is a better factoring of the code, it makes sense to have the embedding side translate the local key events into a generic representation that the framework can then pass along.

This could be done by moving all of the keyboard key translation to the engine side, normalize it there, and just send a generic key event to the framework.

This would be a large breaking change on the framework side to remove the ability to look at the raw key event data on the framework side, but that is a fairly uncommon operation.  We would have to make sure that we encoded all the relevant information in the generic key event (key repeat counts, left/right modifier information, etc.).

**Comment by gspencergoog** [comment]
cc @stuartmorgan

**Comment by gspencergoog** [comment]
Here's the current design doc for this: https://flutter.dev/go/platform-based-key-events

**Comment by dkwingsmt** [comment]
Related PRs:
- [ ] Platform: https://github.com/flutter/flutter/pull/70876
- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] Linux (GTK)
- [ ] macOS
- [ ] Web
- [ ] Fuchsia
- [ ] Platform codegen

Probably fixing issues: (still collecting)
- [ ] RawKeyboardListener returning incorrect keys on Windows (https://github.com/flutter/flutter/issues/72533)
- [ ] [Windows] Page Down and Up keys produce wrong type of Logical Key (https://github.com/flutter/flutter/issues/70553)
- [ ] Problem with @ key in flutter desktop (https://github.com/flutter/flutter/issues/68713)
- [ ] Key handling should make a distinction between a lock key being "down" and the lock state being "on". (https://github.com/flutter/flutter/issues/64761)

**Comment by ds84182** [comment]
Wait, would this refactor remove the ability to get device information in key event payloads? That's a HUGE breaking change for us, since we use the device info to clean up key events since Android sends lots of duplicate events.

**Comment by dkwingsmt** [comment]
@ds84182 Yes it is. Thanks for informing us timely. Can you specify what information exactly you're using, and how you're detecting them? Maybe we can work out a solution, or even embed this process into our engine code.

**Comment by ds84182** [comment]
@dkwingsmt We use `RawKeyEventDataAndroid`'s eventSource to detect and ignore Android's synthetic events for gamepads. Otherwise gamepads can trigger shortcut actions multiple times.

In addition to the normal gamepad events, Android sends `Select` when pressing A, Start, or L3/R3 (control sticks). It sends `Context Menu` for the Select button, `Backspace` for the X button, and `Space` for the Y button.

We also detect and ignore key repeats, to avoid triggering actions multiple times if a button is held down.

Fortunately we don't depend on anything too exotic, like `deviceId` and `vid/pid`. We'd have to move this filtering logic back up into the Android layer, where we already intercept key events. But this will prevent future work, like detecting which device a particular key is coming from, or devices that produce custom keycodes that aren't part of `LogicalKeyboardKey`.

**Comment by dkwingsmt** [comment]
Ok. Let me break it down.
1. Repeat events should be easily filtered out since they'll be a completely different type. The new system will have 3 types of events. Every key press sequence consists of 1 Down, 0 or more Repeats, and 1 Up. You can simply ignore Repeat events.
2. Gamepad keys are a bit complicated. Theoretically gamepads should produce either separate physical keys or separate logical keys, or both, which makes them very distinguishable. Realistically though I'd not be surprised if Android also map them to actual keys. I'll see if I can test them with Android emulator (although I understand that Android distributions may behave differently between each other). The worst case is that we can add a `deviceSource` into the payload.

Does it sound good to you?

**Comment by ds84182** [comment]
@dkwingsmt Sounds good. We can also look into moving this filtering up into the Android layer, since this is an Android-specific issue.

**Comment by inceptusp** [comment]
@dkwingsmt I have a question: Will this change solve the keyboard "stop working" problem on linux after some backspacing?

https://user-images.githubusercontent.com/17789155/110005366-25ed3100-7cf7-11eb-979b-ccf926fe1cd8.mp4

If so, any predictions on when we can test it?

**Comment by dkwingsmt** [comment]
@inceptusp I anticipate yes. This is a full rewrite with many corner cases taken into consideration.

**Comment by inceptusp** [comment]
@dkwingsmt I have searched but, the most closely, that I've found was https://github.com/flutter/flutter/issues/73544 but it is an android bug specific to one (maybe two according to https://github.com/flutter/flutter/issues/73544#issuecomment-768287589) virtual keyboard and I don't even know if it has the same cause 'cause I don't know exactly how to track the keyboard input to check what causes the issue... Other than that, I have not found any that matches the problem...

At the moment, I only know that the keyboard works and then stops working after using backspace some times (only backspace keeps working) and that it occurs on Linux (I can only test on Linux and Windows)... The only way to get the keyboard to work again is closing and opening the app again...

If you remember of any issue that matches my description, let me know so I can follow and contribute with what I can. If you think that I should open an issue related to this, let me know too.

Thx =D

**Comment by dkwingsmt** [comment]
@inceptusp Yeah it would be helpful if you can open and issue for us to track. Thank you very much.

**Comment by Mr-Pepe** [comment]
@dkwingsmt  I suggest adding #77461 to your list if it is within the scope of this rewrite.

**Comment by edwardaux** [comment]
Hating to be one of "those guys", but I'm curious if this ticket is still being actively pursued? 

There's a bunch of other tickets that are being closed in favour of this one... but if this ticket isn't being worked on (or if the anticipated completion date is still months/years away), then there's a bit of a gap where genuine keyboard problems are impacting users in the meantime.

Not trying to be difficult... just trying to see how aggressively I should be pursuing workarounds to my existing keyboard problems vs. waiting for a fix.

**Comment by dkwingsmt** [comment]
@edwardaux Yes I'm still fully focusing on the keyboard system, especially all the issues that were found recently.

**Comment by edwardaux** [comment]
Ah, lovely. Thanks for the status update @dkwingsmt ... I appreciate that it is a big task 👍

**Comment by dkwingsmt** [comment]
@gspencergoog has gone through the trouble of migrating everything in the Framework to `KeyEvent` and `onKeyEvent` and started a deprecation. Let's call this issue done!
