### ISSUE TITLE
[cloud_firestore] Add support for web

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45293]
We should support `cloud_firestore` on Flutter for web.

## -- Tasks --

- [x] Move cloud_firestore to its own subdirectory to allow for federated implementations
- [x] Add `cloud_firestore_platform_interface` package, with the core interface that the plugin implements, and the MethodChannel implementation
- [x] Port `cloud_firestore` to use the interface defined above
- [x] Add `cloud_firestore_web` implementing the interface, for web
- [ ] Endorse `cloud_firestore_web` from `cloud_firestore` as the official web platform implementation.

**Comment by rahulraj64** [comment]
What about the Firebase Realtime Database?

**Comment by ditman** [comment]
Working on this!

**Comment by ditman** [comment]
(Tentative milestone added)

**Comment by ditman** [comment]
Work is actually progressing here:

https://github.com/FirebaseExtended/flutterfire/pull/1670 thanks to @amrfarid140!

**Comment by surajmandalcell** [comment]
Any update on this?

**Comment by rodydavis** [comment]
How will the caching work on Flutter Web? On mobile I believe it uses SQLite. Also would love to use this on MacOS too. Right now I am using the rest api.

**Comment by ditman** [comment]
@rodydavis Do you mean caching as in "offline mode" or caching as in "do not request data from the DB that you already have in your cache"? 

For web we're using the JS SDK at the bottom of all the layers, so whatever it does officially, we get. See [Access data offline](https://firebase.google.com/docs/firestore/manage-data/enable-offline) maybe?

**Comment by rodydavis** [comment]
If it’s using the js implementation then that answers my question 👍🏼

I was curious about the server, cache or both server and cache option that is already available on the current SDK and how it would work with web.

**Comment by ditman** [comment]
cloud_firestore has been updated to use the platform interface [here](https://github.com/FirebaseExtended/flutterfire/pull/1945)

**Comment by HerrNiklasRaab** [comment]
Does this mean, that the cloud_firestore package can be used in AngularDart applications to in the future?

Does this mean, that the cloud_firestore package can be used in Cloud Functions written in Dart in the future?

At the moment we are developing an app using cloud_firestore, is there anything we need to pay attention to, to be able to use this later in our Flutter Web project?

**Comment by ditman** [comment]
> At the moment we are developing an app using cloud_firestore, is there anything we need to pay attention to, to be able to use this later in our Flutter Web project?

@HerrNiklasRaab You'll need to change your `web/index.html` slightly, to download the Firebase + Firestore JS SDK, and initialize your App there. You can take a sneak peek at the changes you'll have to do [here](https://pub.dev/packages/firebase_auth_web) (+ one script line downloading firestore).

> Am I right, that in future there will be the "cloud_firestore" package with all the interfaces, there will be a "cloud_firestore_flutter" package for all flutter specific implementations and a "cloud_firestore_web" for use in Angular Dart and Cloud Functions. Or am I completely on the wrong track there?

@HerrNiklasRaab Check the documentation about "[Flutter Federated Plugin Implementations](flutter.dev/go/federated-plugins)" so this makes more sense. TL;DR, this is what this change includes:

1. The platform API (the one you have to implement if you want to support additional platforms) and the MethodChannel (iOS/Android) implementations in `cloud_firestore_platform_interface`
2. The public plugin API (the one that plugins users use) in the `cloud_firestore` package. The core plugin uses the platform API defined in (1) to provide platform-specific functionality.
3. The web implementation of (1) in `cloud_firestore_web`.

If a new platform were to appear and need to implement their own version of the plugin, they'd just need to repeat the work in "3", and everybody else's Apps would be able to run the plugin in that platform.

With Federation, the owner of the core plugin (2) can "endorse" implementations so they become the "official implementation", and the tooling is able to pick them up automatically for all the users.

I'm not sure if you can get Angular Dart to use Flutter's plugin architecture.

**Comment by ditman** [comment]
cloud_firestore_web has been merged, and published [here](https://github.com/FirebaseExtended/flutterfire/pull/1950)

**Comment by ditman** [comment]
Merged and published [cloud_firestore 0.13.2](https://pub.dev/packages/cloud_firestore) with web support! Thanks @amrfarid140 for the super hard work!!

**Comment by HerrNiklasRaab** [comment]
Hello @ditman, thank you a lot for the explanation. I got it. One last question:

Why do you need the dependency of flutter in https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web? 

There is nothing used from flutter package, wouldn't this mean, you could just add Dart JS as a target platform with very little to no effort and close this issue to https://github.com/FirebaseExtended/firebase-dart/issues/170?

**Comment by ditman** [comment]
> Why do you need a dependency of flutter in `cloud_firestore_web`?

@HerrNiklasRaab the dependency in `flutter` is required so the package can identify itself as a flutter plugin for the web platform:

```
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirestoreWeb
        fileName: cloud_firestore_web.dart
```

> ... Just add Dart JS as a target platform with very little to no effort and close FirebaseExtended/firebase-dart#170

I think it'd be a non-trivial amount of effort. The current implementation of the plugin has:

* A completely different API than the underlying implementation (`.document()` vs `.doc()` is only one example, there are a bunch like that, no matter what we do, it'll be a breaking change either for the plugin users, or package:firestore.)
* Almost every data type needs its own custom implementation because of the above
* There's a required layer that "bridges the gap" between the JS SDK implementation (the one that firebase-dart knows how to handle) and the Plugin implementation (the one that plugin users are currently using).

Maybe you're seeing some path that I'm not seeing to merging the implementations here, and if so, please **do** submit a PR (or design doc) with your proposed changes. I'm very new to this product, and I often do make mistakes :)

**The goal of this project was to support the `cloud_firestore` plugin for the Flutter web platform**, not to converge/unify/improve in any way with the underlying implementation. We used package:firebase as the "backend" because it is very well battle tested! It also allowed us to not have to worry about the JS interop with the JS SDK :)

PS: I'm locking this thread, since it has run its course. Again, please do contribute code or designs if you see a better path forward! Thanks!
