### ISSUE TITLE
The Great Scrollables Refactor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#5288]
Our scrollables logic has gotten rather messy and needs refactoring now that we have a better idea of our overall needs.
- [x] Use a new render object approach: https://github.com/flutter/flutter/issues/4430
- [x] Refactor ScrollBehavior: https://github.com/flutter/flutter/issues/5281
- [x] ClampOverscrolls should probably be refactored to just use of ScrollConfiguration. (The tricky part is reverting to system defaults after, e.g. so that you can say this Block doesn't overscroll, but its sub-blocks do.)
- [ ] Implement the material toolbar "Flexible space with overlapping content" feature as a proof of concept: https://github.com/flutter/flutter/issues/404
- [ ] Look into padding the lists with one item each way to keep shadows visible: https://github.com/flutter/flutter/issues/170

cc @HansMuller, @abarth

**Comment by Hixie** [comment]
This may also fix https://github.com/flutter/flutter/issues/5339

**Comment by Hixie** [comment]
Closing this bug. The refactor is well under way and we don't need to track it via this bug any more.
