### ISSUE TITLE
Support iPadOS pointer interactions

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#55809]
This is an umbrella issue that tracks the support for iPadOS pointer interactions.
However, features beyond basic cursor type and hover effect will likely have a low priority for a while.

## Reference
- Apple's [Design guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/pointers/)
- UIKit's [Documentation](https://developer.apple.com/documentation/uikit/pointer_interactions)

## TODO
- Support basic mouse features
  - [ ] Support background color change in hover effect
  - [ ] Support basic cursor styles (those without magnetism) on hoverable regions
- Support region-aware features
  - [ ] Support highlight effect
  - [ ] Support lift effect
- [ ] Support trajectory prediction

## Related issues
- Previous discussion: https://github.com/flutter/flutter/issues/52912
- Scroll wheels: https://github.com/flutter/flutter/issues/54663
- General mouse cursor: https://github.com/flutter/flutter/issues/31952

**Comment by jmagman** [comment]
@dkwingsmt is this a duplicate of https://github.com/flutter/flutter/issues/53456?  Can we combine?

**Comment by xster** [comment]
no it's different. This one's about using a pointer device like a mouse. The other one's about displaying highlight focus when not using a mouse (such as navigating via keyboard) (which iOS doesn't quite do properly yet)

**Comment by rodydavis** [comment]
Nice to have would be having the animated cursor on the demo where it can transform into the inkwell shape of the material components. 

Other things needed that are related to this are receiving pointer signals scrolling on a trackpad or external mouse, or just simple hover gestures too.

**Comment by SoolyChristy** [comment]
P5 level 。。。

**Comment by dkwingsmt** [comment]
@SoolyChristy P5 is the default level for new features, just like P4 is the default level for bugs. Higher levels are for features and bugs that blocks customers.

**Comment by alexmarkley** [comment]
I propose a priority bump for this family of issues. On a very short time scale (by the end of the year) this will become a blocker for nearly every iOS app developer using Flutter.

See:
- https://github.com/flutter/flutter/issues/66184
- https://github.com/flutter/flutter/issues/54663#issuecomment-695500705

**Comment by nt4f04uNd** [comment]
@dkwingsmt i think you missed a checkbox for custom developer defined cursor shapes

**Comment by nt4f04uNd** [comment]
also, why did you exclude magnetism

**Comment by adamsowinski** [comment]
Unfortunately this is a showstopper for me. I can't use Flutter as pointer is a hard requirement. I doubt we will switch to Flutter at a later stage once we have a fully functional iOS app.

**Comment by kevinwei666** [comment]
It seems the mouse cursor style still not being supported on ios/ipadOS

**Comment by dkwingsmt** [comment]
We haven't got the bandwidth to investigate this issue yet. If you're interested in contributing to this issue, I'd be very happy to review the design docs and/or PRs.
