### ISSUE TITLE
☂️ Add support for ARM macOS host

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60118]
Umbrella issue tracking developing Flutter on macOS ARM.
Use case: developer buys ARM Mac, installs Flutter tooling on the Mac, deploys Flutter to an iPhone.

- Build tool on macOS ARM
- Build ARM host dependencies (iproxy, libimobiledevice).  Rosetta translation?
- IDE support
- Infrastructure support

Note: this is tracking host-side issues.  Running Flutter on ARM macOS as a target is tracked by https://github.com/flutter/flutter/issues/60113.

Wiki page: https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon

Update: Flutter should be fully working on M1 with Rosetta translation (particularly tooling and iOS simulator).  The remaining work is to get it working natively without Rosetta.

### Infrastructure
- [ ] https://github.com/flutter/flutter/issues/87508 Add Mac M1 ARM machines to the prod pool

### Native host development (`flutter` tool)
- [x] https://github.com/flutter/flutter/issues/84453 
- [ ] https://github.com/flutter/flutter/issues/69157 (ios-deploy, libimobiledevice, etc)
- [x] https://github.com/flutter/flutter/issues/86926
  - [x] https://github.com/flutter/flutter/issues/97658 

#### Sub-issues
- [x] https://github.com/flutter/flutter/issues/84601 Update iOS and macOS engine builders to Xcode 12.0
- [x] https://github.com/flutter/flutter/pull/60119 [flutter_tools] separate target platform, host platform, and architecture
- [x] https://github.com/dart-lang/sdk/issues/42534 Building flutter tool on ARM macOS host fails
- [x] https://github.com/dart-lang/sdk/issues/42773 Dart SDK version is built for macOS ARM host
- [x] https://github.com/flutter/flutter/issues/96745 Support building the engine on macOS ARM hosts

#### Physical devices
- [x] https://github.com/flutter/flutter/issues/65133 "flutter build ios" fails on ARM macOS, ibtoold crashes compiling xcassets/storyboards
- [x] https://github.com/flutter/flutter/issues/65976#issuecomment-717523043 Add macOS architecture to doctor output for host
- [x] https://github.com/flutter/flutter/issues/79430 Add mac m1 machines to the staging pool

#### Simulator
- [x] https://github.com/flutter/flutter/issues/85062 iOS engine artifacts Flutter.xcframework contains old architecture triples directories
- [x] https://github.com/flutter/flutter/issues/84672 Update Flutter Engine recipes to handle ARM64 simulator 
- [x] https://github.com/flutter/flutter/issues/82736 Adding ARM iOS simulator times out the engine artifacts build
- [x] https://github.com/flutter/flutter/issues/66926 engine gn updates required for simulator on macOS arm
- [x] [b/162290052](https://b.corp.google.com/issues/162290052) Cannot launch Android emulators
- [x] https://github.com/flutter/flutter/issues/60109 Distribute engine as Flutter.xcframework
- [x] https://github.com/flutter/flutter/issues/69718 Deprecate `flutter build ios-framework --universal`
- [x] https://github.com/flutter/flutter/issues/65901 XCode SDK needs to be updated on mac LUCI builders
- [x] https://github.com/flutter/flutter/issues/66925 flutter engine on iOS arm simulator does not build
- [x] https://github.com/flutter/flutter/issues/73066 Update engine script create_ios_framework to optionally take ARM simulator path
- [x] https://github.com/flutter/flutter/issues/84670 Add buildroot support for ARM64 simulator engine builds
- [x] https://github.com/flutter/flutter/issues/69334 Add ARM simulator architecture slice to App.framework to support Apple Silicon
- [x] https://github.com/flutter/flutter/issues/64502 Flutter cannot build against iOS ARM simulators (on ARM macOS host)
- [x] https://github.com/flutter/flutter/issues/85713 When plugins do not support ARM iOS simulators, the app fails to build

#### Plugin support
- [x] https://github.com/flutter/flutter/issues/70796 Work around ffi "symbol not found" error from CocoaPods
- [x] https://github.com/ffi/ffi/issues/800 SEVG on Apple silicon macOS
- [x] https://github.com/invertase/firestore-ios-sdk-frameworks/issues/16 firestore-ios-sdk-frameworks pre-built xcframeworks should support Apple Silicon ARM simulators
- [x] https://github.com/flutter/flutter/issues/73686 CocoaPods Rosetta workaround has issues
- [x] https://github.com/flutter/flutter/issues/87242 Mark google_maps_flutter as not supporting arm64 iOS simulator
- [x] https://github.com/flutter/flutter/issues/87243 Mark google_sign_in as not supporting arm64 iOS simulators
- [x] https://github.com/flutter/flutter/issues/85713

Tracking Apple Silicon as a target device separately at https://github.com/flutter/flutter/issues/60113.

**Comment by cbenhagen** [comment]
Building flutter tool on ARM macOS host currently fails with:
```
Building flutter tool...
oah error: unhandled 16KB-unaligned mmap addr=0x0 len=0xdd28c0 offset=0x1000 prot=1 flags=2
/Users/ben/development/flutter/bin/internal/shared.sh: line 20:  1298 Trace/BPT trap: 5       "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

Leaving this here so it can be found by a google search. But maybe it should be moved to a separate issue?

**Comment by jmagman** [comment]
> Building flutter tool on ARM macOS host currently fails with:
> 
> ```
> Building flutter tool...
> oah error: unhandled 16KB-unaligned mmap addr=0x0 len=0xdd28c0 offset=0x1000 prot=1 flags=2
> /Users/ben/development/flutter/bin/internal/shared.sh: line 20:  1298 Trace/BPT trap: 5       "$PUB" upgrade "$VERBOSITY" --no-precompile
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
> ```
> 
> Leaving this here so it can be found by a google search. But maybe it should be moved to a separate issue?

Yes, can you file a separate issue?  I heard about this but we don't have DTKs yet.  I'll link it back to this umbrella meta issue.

**Comment by jmagman** [comment]
@cbenhagen Can you file in https://github.com/dart-lang/sdk ?

**Comment by cbenhagen** [comment]
Done: https://github.com/dart-lang/sdk/issues/42534

**Comment by christopherfujino** [comment]
Just to cross reference, tracking linux arm host support on https://github.com/flutter/flutter/issues/56992

**Comment by alexmarkley** [comment]
I'm happy to report that my experience with Flutter master branch on Apple Silicon / DTK has been much better than others early experiences ( ala https://github.com/dart-lang/sdk/issues/42534 ). At this point Rosetta seems to be able to run most of the host tooling, and I am able to target iOS using the generated Xcode project.

Per https://github.com/flutter/flutter/issues/65132 the `flutter run` tool is still not working. Also, per https://github.com/flutter/flutter/issues/64502 the simulator does not work correctly on ARM hosts.

However, and I think this is super cool, actually building and running the Flutter application on-device using Xcode 12.2 Beta _is working as expected_. I can even use `flutter attach` to observe and interact with the running application!

If I am able to get my local development environment to work correctly ( https://github.com/dart-lang/sdk/issues/43488 ) I'm optimistic that I can participate in the porting effort to get the tooling running natively on the ARM host.

**Comment by jmagman** [comment]
`flutter run -d macos` worked out of the box (as a rosetta app):
![Screen Shot 2020-09-30 at 6 49 44 PM](https://user-images.githubusercontent.com/682784/94756976-dc667780-034d-11eb-9a2f-e11cd94f32d9.png)
![Screen Shot 2020-09-30 at 6 50 08 PM](https://user-images.githubusercontent.com/682784/94757025-fa33dc80-034d-11eb-80d9-6f12a07565b8.png)

**Comment by xster** [comment]
@jmagman I think we were talking about "XCode SDK needs to be updated on mac LUCI builders" just now. Should that be better named as "mac LUCI builders' Xcode need to use the iOS 14 SDK"?

**Comment by jmagman** [comment]
> @jmagman I think we were talking about "XCode SDK needs to be updated on mac LUCI builders" just now. Should that be better named as "mac LUCI builders' Xcode need to use the iOS 14 SDK"?

Done at https://github.com/flutter/flutter/issues/65901#issuecomment-702368354.

**Comment by jonahwilliams** [comment]
Ship it!

**Comment by joniaiuser** [comment]
Trying to understand the current state of this issue.. Is it accurate to say that if I were to buy an ARM Mac next week, I would probably require a physical iOS device to do Flutter development as Flutter would not be able to build on ARM simulators running on the new Macs.

**Comment by jmagman** [comment]
> Trying to understand the current state of this issue.. Is it accurate to say that if I were to buy an ARM Mac next week, I would probably require a physical iOS device to do Flutter development as Flutter would not be able to build on ARM simulators running on the new Macs. But I should still be able to build a release version of the app for iOS without problems.

That's a good summary. I would add that mac desktop apps are working in Rosetta.

**Comment by jmagman** [comment]
Sorry didn't mean to close this.

**Comment by jmagman** [comment]
> > Trying to understand the current state of this issue.. Is it accurate to say that if I were to buy an ARM Mac next week, I would probably require a physical iOS device to do Flutter development as Flutter would not be able to build on ARM simulators running on the new Macs. But I should still be able to build a release version of the app for iOS without problems.
> 
> That's a good summary. I would add that mac desktop apps are working in Rosetta.

Also, last time I tried, CocoaPods wasn't working on arm, so apps with plugins won't work.

**Comment by joniaiuser** [comment]
> > > Trying to understand the current state of this issue.. Is it accurate to say that if I were to buy an ARM Mac next week, I would probably require a physical iOS device to do Flutter development as Flutter would not be able to build on ARM simulators running on the new Macs. But I should still be able to build a release version of the app for iOS without problems.
> > 
> > 
> > That's a good summary. I would add that mac desktop apps are working in Rosetta.
> 
> Also, last time I tried, CocoaPods wasn't working on arm, so apps with plugins won't work.

I saw in one of the linked issues someone posted a workaround, is that not a viable solution? 

https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-656418556

**Comment by jmagman** [comment]
> I saw in one of the linked issues someone posted a workaround, is that not a viable solution?
> 
> [CocoaPods/CocoaPods#9907 (comment)](https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-656418556)

It didn't work for me, CocoaPods would crash with `LoadError - dlsym(0x7fbbeb6837d0, Init_ffi_c): symbol not found`.  [Workaround](https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-729980327) is to install x86_64 `ffi` gem:
```
arch -x86_64 sudo gem install ffi
```
Flutter work tracked at https://github.com/flutter/flutter/issues/70796

**Comment by jtoy** [comment]
excited to see this working soon!

**Comment by EArminjon** [comment]
Today, is it possible to use flutter to make mobile app on Apple Silicon Big Sur ?
I would by mac mini but if we can't.... ?

**Comment by sunface** [comment]
expected to see this before the end of this year :)

**Comment by benjaminschreck** [comment]
> Today, is it possible to use flutter to make a mobile app on Apple Silicon Big Sur ?
> I would buy the new mac mini but if we can't.... ?

Is is possible, but you have to use physical devices to test your code. I tested it with the Apple Silicon MBP 13 16GB, IPhone XS Max, IPad Pro 2020. 
Flutter web just works as expected. 

If you want to use plugins, you should install the ffi gem mentioned earlier.

**Comment by jmagman** [comment]
This [wiki page](Wiki page: https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon) is a more digestible form of what works and what doesn't.  This issue is a convenience meta issue, so I'm going to lock for now to prevent noise.

**Comment by xster** [comment]
Should we leave https://github.com/flutter/flutter/issues/64502 and create a separate bug for running iOS simulator on rosetta?

**Comment by jmagman** [comment]
> Should we leave #64502 and create a separate bug for running iOS simulator on rosetta?

https://github.com/flutter/flutter/issues/72294

**Comment by xster** [comment]
Created https://github.com/flutter/flutter/issues/74662 to wrap up documentation for the next stable

**Comment by jmagman** [comment]
On Flutter 2 deploying your app in Rosetta mode to the iOS simulator with the command line tool `flutter run`/ `flutter build ios --simulator`, or from a Flutter IDE plugin should work.  Targeting the iOS simulator from Xcode is supported without manual project changes as of https://github.com/flutter/flutter/pull/73828, which is currently available on the master channel.

**Comment by jmagman** [comment]
Native arm64 iOS simulator without Rosetta now available as of https://github.com/flutter/flutter/pull/85642.

**Comment by cbracken** [comment]
Engine building on arm64 mac hosts as of https://github.com/flutter/engine/pull/33244

**Comment by jmagman** [comment]
There are also arm64 Mac tests running like
https://github.com/flutter/flutter/blob/708c363920b9a11c8aa4fdc5dd9d7eb78fe6f56f/.ci.yaml#L3122

This is complete.  We can track the ew remaining x64 binaries separately at https://github.com/flutter/flutter/issues/69157.

**Comment by cbracken** [comment]
SGTM. We're now arm64/arm64 (as well as x64/simarm64) binaries for gen_snapshot in macOS engine host builds. I'm happy to take a look at getting a lipo'ed universal binary for gen_snapshot in place.

**Comment by jmagman** [comment]
> SGTM. We're now generating arm64/arm64 (as well as x64/simarm64) binaries for gen_snapshot in macOS engine host builds. I'm happy to take a look at getting a lipo'ed universal binary for gen_snapshot in place.

@zanderso says it's more complicated than lipoing, more info in https://github.com/flutter/flutter/issues/101138.

**Comment by cbracken** [comment]
If I understand the issue pointed to there, a bunch of that was fixed in https://github.com/flutter/engine/pull/33244. That's what I meant by us now generating native arm64/arm64 binaries rather than x86/simarm64. But maybe I'm misreading this?

**Comment by jmagman** [comment]
> If I understand the issue pointed to there, a bunch of that was fixed in https://github.com/flutter/engine/pull/33244.

Neat, I didn't see that PR.  Feel free to close what you think is complete.

> but my understanding was that https://github.com/flutter/flutter/issues/101138 is about an arm64->arm64 gen_snapshot, not the arm64->x64 case.

That's what I meant to track with that issue since that's within our ability do to now given dart limitations.

@zanderso I thought we couldn't just lipo gen_snapshots together because of... some reason you've explained to me at least 4 times.

**Comment by zanderso** [comment]
We could lipo together the `gen_snapshot` binaries that target arm64, but not the `gen_snapshot` binaries that target x64. The reason is that Dart only supports generating intel code when running on an intel host.

My suggestion for now is to keep things simple and ship non-lipo'd `gen_snpashot`s targeting both `arm64` and `x64` as intel binaries, which will run under Rosetta on M1.

**Comment by cbracken** [comment]
sgtm!
