### ISSUE TITLE
☂️ Support Xcode 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#60133]
Umbrella issue tracking developing Flutter apps working with Xcode 12.

- [ ] https://github.com/flutter/flutter/issues/60025 Fix all "Double-quoted include in framework header, expected angle-bracketed instead" warnings
- [ ] https://github.com/flutter/flutter/issues/62880 Migrate existing apps/plugins with minimum supported iOS version from 8.0 to 9.0

## Available in 1.22 
- [x] https://github.com/flutter/flutter/issues/60035 Increase app template minimum supported iOS version from 8.0 to 9.0
- [x] https://github.com/flutter/flutter/issues/60043 build_ios_framework_module_test fails with Xcode 12
- [x] https://github.com/flutter/flutter/issues/60072 flutter run fails Xcode 12: fruitstrap_.py, in connect_command process
- [x] https://github.com/flutter/flutter/pull/63252 Bump Cirrus image Xcode version
- [x] https://github.com/flutter/flutter/issues/63613 Engine doesn't build in Xcode 12

## Available in 1.23.0-13.0.pre
- [x] https://github.com/flutter/flutter/issues/63253 Increase plugin template minimum supported iOS version from 8.0 to 9.0

### Related umbrella issues
iOS 14 support tracked separately at https://github.com/flutter/flutter/issues/61047.
ARM macOS host tracked separately at https://github.com/flutter/flutter/issues/60118.

**Comment by ghenry** [comment]
Hi all,

I've just upgraded to xcosw 12 and am trying to `flutter run` on a iOS 13.7 iPhone 8. I'm getting this and Google is not returning much. I've switched to the dev channel just in case as I get it on stable and beta. Is this an Xcode 12 issue?

```
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries:
    (/xxxx/ios/Flutter/Flutter.framework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in
    verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in
    verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in
    `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/xx/development/flutter
    • Framework revision a27c242b0e (8 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ghenry/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Users/xx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/xx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Gavin’s iPhone (mobile) • 78be4d4c687a2701dd01a06b79860111d3d95edf • ios • iOS 13.7
```

**Comment by ghenry** [comment]
Seems unrelated. For others, I followed https://github.com/flutter/flutter/issues/14161#issuecomment-627593995 :

`For me, I deleted the ios/Flutter/Flutter.framework folder and install pods pod install again then it worked.`

but now hitting this https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/

**Comment by ghenry** [comment]
I did this (a bit rough):

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
    flutter_additional_ios_build_settings(target)
  end
end
```

in ios/Podfile

**Comment by ghenry** [comment]
My app is now running as per the previous flutter doctor I posted with hot reload, but not seeing any logs. Thanks for listening!

**Comment by jmagman** [comment]
Please have discussions about bugs and features in their respective issues (or file new ones) so the right teams can investigate and track them down.  This is an umbrella issue tracking all of it.  Locking.

**Comment by shreyaspapi** [comment]
Any ETA for this to release?

**Comment by jmagman** [comment]
1.22 released today. https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f
I rearranged the issue list so you can see which fixes are available in which channel.

**Comment by NikunjKumbhani** [comment]
Here is the output after run `flutter doctor -v ` 

I am using Xcode 12.0.1 and flutter 1.23.0 from the master channel 

in All Simulator everything Working Fine

**But in iOS 14 Real Device with connected via cable everything working fine but once I disconnect the device and launch the app after that Just Display While Screen and Close the app** 

![Screenshot 2020-10-13 at 12 31 55 PM](https://user-images.githubusercontent.com/24408314/95827850-e460e700-0d51-11eb-8018-9b395fc9c29e.png)

**Comment by minikin** [comment]
@NikunjKumbhani Does it happen in release mode too, or only in debug?

**Comment by daniil-shumko** [comment]
@NikunjKumbhani this is a known issue and it is documented on the [Developing for iOS 14](https://flutter.dev/docs/development/ios-14#launching-debug-flutter-without-a-host-computer) section of the docs.

**Comment by jmagman** [comment]
For anyone seeing issues with Xcode 12 or iOS 14, please (please please) file a new issue and completely fill out the template, including the output of `flutter doctor -v`.  This is an umbrella/meta issue tracking fixed and outstanding Xcode 12 issues, for planning and informational purposes.  We don't track individual bugs here (we can't assign it, we can't add milestones, we can't triage it, we can't close as a duplicate...).  We may add your issue to this list as needed.
Thank you!

**Comment by zanderso** [comment]
Closing in favor of tracking with the issues for the remaining items.
