### ISSUE TITLE
☂️ Support iOS 14

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#61047]
Umbrella issue tracking developing Flutter apps on iOS 14

### Blockers
- [x] https://github.com/flutter/flutter/issues/60424 flutter run ios 14 crashing on release mode
- [x] https://github.com/flutter/flutter/issues/60634 Running debug on iOS 14 shows "would like to find and connect to devices on your local network" popup 
- [x] https://github.com/flutter/flutter/issues/60013 Some text is displaying incorrectly on iOS 14
- [x] https://github.com/flutter/flutter/issues/63552 add-to-app via CocoaPods doesn't work on iOS 14
- [x] https://github.com/flutter/flutter/pull/65138 Cannot connect to the observatory on a physical iOS 14 device
- [x] https://github.com/flutter/flutter/issues/64045 flutter_tools/ios-deploy can't deploy to physical iOS 14 devices
- [x] https://github.com/flutter/flutter/issues/65207 flutter drive tests fail targeting iOS 14, stuck on local network permission popup
- [x] https://github.com/flutter/flutter/issues/65991 iOS 14 release Invalid Binary related to Invalid font when adding a Widget Extension
- [ ] https://github.com/flutter/flutter/issues/67624 iOS 14 app crashes with a segfault in debug when opening from the home screen

### JIT crash
- [x] https://github.com/flutter/flutter/issues/60657 App crashes on launch on physical iOS 14 device
- [x] https://github.com/flutter/flutter/issues/62518 Show error message in app when ptrace is not permitted on iOS 14 instead of crashing
- [x] https://github.com/flutter/flutter/issues/62531 Document that debug Flutter apps cannot be manually launched on the device on iOS 14
- [x] https://github.com/flutter/flutter/issues/62883 Delete the debug app from iOS 14 device when quitting resident runner
- [x] https://github.com/flutter/flutter/issues/66161 Relaunching debug iOS 14 app from home shows white screen in dark mode

### Other bugs
- [x] https://github.com/flutter/flutter/issues/64605 flutter screenshot fails on iOS 14 beta 5: Could not connect to screenshotr!
- [x] https://github.com/flutter/flutter/issues/62437 Zoomed in mode/5.4" inch screen support
- [x] https://github.com/flutter/flutter/issues/63893 flutter attach for add-to-app modules doesn't work on iOS 14, document how to add _dartobservatory._tcp to host app

### Aesthetic 
- [ ] https://github.com/flutter/flutter/issues/60034 Add package for SF Symbols 2
- [x] https://github.com/flutter/flutter/issues/60047 New iOS 14 CupertinoActivityIndicator
- [ ] https://github.com/flutter/flutter/issues/60762 Add a Sidebar widget to Cupertino for a native look on iPadOS
- [x] https://github.com/flutter/flutter/issues/62521 Deprecate iOSVersionStyle.iOS13
- [x] https://github.com/flutter/flutter/issues/62652 Rounded rectangles painted badly
- [ ] https://github.com/flutter/flutter/issues/60145 Unsolicited iOS14 clipboard permission prompt 
- [x] https://github.com/flutter/flutter/issues/63694 Update picker widget style

### New features
- [ ] https://github.com/flutter/flutter/issues/60026 Explore home widgets for iOS 14
- [x] https://github.com/flutter/flutter/issues/60029 Support app clips on iOS 14
- [ ] https://github.com/flutter/flutter/issues/60298 Pull-Down Menus for iOS 14
- [ ] https://github.com/flutter/flutter/issues/61278 Pencil scribble in text fields
- [ ] https://github.com/flutter/flutter/issues/63693 New date picker widget in iOS 14
- [ ] https://github.com/flutter/flutter/issues/63696 New time picker widget in iOS 14

Xcode 12 support tracked separately at https://github.com/flutter/flutter/issues/60133.

**Comment by EliasDeuss** [comment]
@jmagman shouldn't #60145 be added to that list?

**Comment by jmagman** [comment]
Added, thanks @EliasDeuss.

**Comment by xster** [comment]
Also https://github.com/flutter/flutter/issues/60034

**Comment by xster** [comment]
I'm moving the font issue up. It's too noticeable.

**Comment by EliasDeuss** [comment]
> I'm moving the font issue up. It's too noticeable. 

Yea and the iOS 14 Public beta is rolling out today so it will probably be affecting more people now.

**Comment by timsneath** [comment]
Related: https://github.com/flutter/flutter/issues/61278

**Comment by xster** [comment]
Added pencil scribble to non blocking list

**Comment by omerbengal** [comment]
Anybody with a solution for the crash problem?
almost 3 weeks of me unable to run my apps on my device :(

**Comment by timsneath** [comment]
Sorry for the inconvenience. To be clear, we don't guarantee to support early beta versions of pre-release software. As per the Apple beta documentation:

> Please note that since the public beta software has not yet been commercially released by Apple, it may contain errors or inaccuracies and may not function as well as commercially released software. Install the beta software only on non-production devices that are not business critical. We strongly recommend installing on a secondary system or device, or on a secondary partition on your Mac.

The reason for beta releases like this is to allow time for developers to update to the latest version, which is what we're doing. We're working on these issues ahead of the official release, but if you need to run your app on that device now, you'll need to downgrade. 

Thanks for supporting Flutter!

**Comment by pedromassangocode** [comment]
Related https://github.com/flutter/flutter/issues/62652

**Comment by xster** [comment]
I moved #60145 out of blocker since it won't trigger a system notification on master. The remaining bug is just to re-enable clipboard detection before showing the paste button.

**Comment by pedromassangocode** [comment]
Related to fonts on iOS 14 https://github.com/flutter/flutter/issues/64528

**Comment by xster** [comment]
#64528 is a duplicate. We're ok there.

**Comment by xster** [comment]
Is #64605 a blocking issue?

**Comment by jmagman** [comment]
@xster You're right, added an "Other bugs" section.

**Comment by pedromassangocode** [comment]
Support to test IAP locally with StoreKit on iOS 14 https://github.com/flutter/flutter/issues/65082

**Comment by acoutts** [comment]
On the topic of the new loading indicator, wouldn't it be better to detect the current iOS version and use the appropriate indicator style for that iOS version if we have support all the way back to 9.0?

**Comment by jmagman** [comment]
@acoutts You can file a new feature request so the framework team can look at it.

**Comment by jmagman** [comment]
@pedromassangocode That's a new framework in iOS 14 but it shouldn't be tracked here, it's a feature request for unit testing arbitrary native frameworks.

**Comment by EliasDeuss** [comment]
Looks like iOS 14 and iPadOS 14 will roll out tomorrow.

**Comment by timsneath** [comment]
Thanks @EliasDeuss. We've been preparing for this for a while, and now that we have a clear timeframe, we know what we need to spin up ahead of the iOS 14 rollout. Stay tuned for more in the next 24 hours.

**Comment by jmagman** [comment]
We didn't have a proper standalone issue for prompting the "would like to find and connect to devices on your local network" popup when the dart observatory publishes, so added https://github.com/flutter/flutter/pull/65138 PR to the blocked list (already merged).  More investigation information in https://github.com/flutter/flutter/issues/63893.

Moved #63893 out of blockers since it's now tracking an add-to-app documentation issue.

**Comment by lukasloh** [comment]
> Thanks @EliasDeuss. We've been preparing for this for a while, and now that we have a clear timeframe, we know what we need to spin up ahead of the iOS 14 rollout. Stay tuned for more in the next 24 hours.

Any updates? I think that iOS 14 is rolling out anytime now.

**Comment by Jeremywhiteley** [comment]
IOS 14 is already out now!  Does Flutter support IOS 14 home widgets?

**Comment by timsneath** [comment]
Just posted, here: 
https://medium.com/flutter/supporting-ios-14-and-xcode-12-with-flutter-15fe0062e98b

**Comment by aseef17** [comment]
> IOS 14 is already out now!  Does Flutter support IOS 14 home widgets?   

Hey @Jeremywhiteley 
I understand your eagerness about working with the new widgets and I'm pretty sure that the flutter team is working hard to support iOS14. 
Applications built and targeted for iOS13 do work in iOS 14 without any issues and we just deployed an application couple of weeks ago. It worked completely fine during with iOS public beta and works fine with the stable iOS 14 release. 
All we have to do now is just be a little patient until flutter completely supports iOS14
Cheers.

**Comment by jmagman** [comment]
@Jeremywhiteley @aseef17 Let's have discussions about bugs and features in their respective issues (https://github.com/flutter/flutter/issues/60026).  This is an umbrella issue tracking all of it.

**Comment by aytunch** [comment]
@aseef17 since home widgets are something completely new for iOS users, they will most probably have an extra interest towards apps utilizing this feature and these apps will have higher downloads. Thats my humble opinion. So I believe supporting home widgets asap while it is still new as a very important topic. Also I remember in another issue someone said there are some technical impossibilities for home widget support because of their native implementation through swift ui. Is that true?

**Comment by jmagman** [comment]
@aytunch
> Let's have discussions about bugs and features in their respective issues (#60026). This is an umbrella issue tracking all of it.

**Comment by Jeremywhiteley** [comment]
> @Jeremywhiteley @aseef17 Let's have discussions about bugs and features in their respective issues (#60026). This is an umbrella issue tracking all of it.

Ok.  IOS Home Screen widgets were announced months ago.  They are going to be a very big deal for IOS users.   I haven't seen much on the topic.  No clear direction or path.

**Comment by yanweimin7** [comment]
when did 1.17.x support ios14, any progress ?

**Comment by vasilich6107** [comment]
@yanweimin7 I assume that 1.17.x will never support ios14
You need to upgrade to 1.20.x or latest beta

**Comment by yanweimin7** [comment]
> @yanweimin7 I assume that 1.17.x will never support ios14
> You need to upgrade to 1.20.x or latest beta
that sad,
we just upgrade it 2 month ago.  we spent much time to do upgrade.

**Comment by jmagman** [comment]
The [Medium article](https://medium.com/flutter/supporting-ios-14-and-xcode-12-with-flutter-15fe0062e98b) linked above explains that, other than the clipboard notification problem, your existing deployed apps should continue to work on your customers' iOS 14 devices.  However, for you the developer to use iOS 14 for debugging, etc. you will need to upgrade to the Flutter 1.22 beta.  You can look at the list in this issue to see what features and bug fixes you'll be missing out on.

> If your iOS 14 app uses TextField, CupertinoTextField, or TextFormField, you’ll want to make sure that it’s built with Flutter 1.20 or later to ensure that your users are not bothered by unnecessary clipboard notification messages, as per Apple’s updated clipboard policy.
> Otherwise, existing production apps will run just fine on your end-users’ iOS 14 devices. However, if you’re upgrading your development phone to iOS 14 today and want to continue to use it with Flutter, you have two choices.
> Your first choice is to use the latest hotfix release of Flutter on the stable channel (1.20.4), which supports development-time deployment to physical iOS 14 devices. Unfortunately, there’s another change that is quite a bit more intrusive (and therefore more risky) which is needed for debugging and hot reload on iOS 14. We’re deferring this fix to our next stable release, which we are planning to release in the next few weeks.

Flutter's policy is to not hotfix older stable versions:
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
> Note that we only hotfix the latest version --- if you see bugs on older versions of the stable channel, please consider moving to the latest stable channel version.

**Comment by i6x86** [comment]
I'm on 1.22.0 and my app still crashes in debug. Well it runs fine, but after detach the iPhone and kill the app and then run it again it crashes. Is there any chance to get this fixed now or will have to wait some of the next versions?

**Comment by timsneath** [comment]
@i6x86 can you share your `flutter doctor -v` results?

**Comment by jmagman** [comment]
@i6x86 Can you share those results in a new issue, completely fill out the template, and include the crash log (Xcode > Window > Devices and Simulators > your device > View Console Logs)?  This is an meta issue tracking outstanding iOS 14 tasks, and we don't want to add noise about specific bugs/features.  I will add your issue to this list, though.

**Comment by i6x86** [comment]
> @i6x86 can you share your `flutter doctor -v` results?

Sure, sorry for the late reply.
Here it is:

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale es-ES)
    • Flutter version 1.22.0 at .......
    • Framework revision d408d302e2 (9 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ......
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by i6x86** [comment]
> @i6x86 Can you share those results in a new issue, completely fill out the template, and include the crash log (Xcode > Window > Devices and Simulators > your device > View Console Logs)? This is an meta issue tracking outstanding iOS 14 tasks, and we don't want to add noise about specific bugs/features. I will add your issue to this list, though.

Ok. I'll take a look and will post new issue.

**Comment by i6x86** [comment]
@jmagman @timsneath  I opened a new issue here https://github.com/flutter/flutter/issues/67624

**Comment by SandipSerantec** [comment]
Here is the output after run `flutter doctor -v ` 

I am using Xcode 12.0.1 and flutter 1.23.0 from the master channel 

in All Simulator everything Working Fine

**But in iOS 14 Real Device with connected via cable everything working fine but once I disconnect the device and launch the app after that Just Display While Screen and Close the app** 

![Screenshot 2020-10-13 at 12 31 55 PM](https://user-images.githubusercontent.com/68903322/95826658-43256100-0d50-11eb-8410-2942f0c4fda9.png)

**Comment by NikunjKumbhani** [comment]
**Please Help to Solve this** https://github.com/flutter/flutter/issues/60133#issuecomment-707542459

**Comment by jmagman** [comment]
Let's track the remaining iOS 14 features individually now that it's been out awhile.  Closing this umbrella issue.
