### ISSUE TITLE
Migrate framework devicelab tests to iOS 14 SDK and Xcode 12

### ISSUE THREAD

**Issue by xster** [flutter/flutter#70222]
- [ ] https://github.com/flutter/flutter/issues/70414 - integration_ui_ios_screenshot
- [x] https://github.com/flutter/flutter/issues/70416 - external_ui_integration_test_ios
- [x] https://github.com/flutter/flutter/issues/70422 - flutter_view_ios__start_up
- [x] https://github.com/flutter/flutter/issues/70869 - tiles_scroll_perf_ios__timeline_summary
- [x] https://github.com/flutter/flutter/issues/71232 - Pods-Runner does not support provisioning profiles

3 remaining migration blockers:

----
```
error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'macosx' (in target 'watch' from project 'Runner')
[ios_app_with_extensions_test] [STDOUT] stdout:     error: unable to find sdk 'watchos' (in target 'watch' from project 'Runner')
```
https://logs.chromium.org/logs/flutter/led/godofredoc_google.com/5aaab33f10eae0d7e0be177c15763c1f22a0f80a6fd382ee3f8e1ff4e9431ee3/+/steps/run_ios_app_with_extensions_test/0/stdout

----
```
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Installing and launching...                                        39.4s
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Application failed to start on attempt: 1
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Installing and launching...                                        36.6s
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Application failed to start on attempt: 2
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Installing and launching...                                        36.9s
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Application failed to start on attempt: 3
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Application failed to start. Will not run test. Quitting.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] "/opt/s/w/ir/k/flutter/bin/flutter" exit code: 1
[flutter_gallery__transition_perf_e2e_ios] [STDERR] Task failed: Executable "/opt/s/w/ir/k/flutter/bin/flutter" failed with exit code 1.
```
https://logs.chromium.org/logs/flutter/led/godofredoc_google.com/3168dfdb0b4ef7b09880118b9c8eafe92a1861dc291386a9fc2724ebbbd2ab78/+/steps/run_flutter_gallery__transition_perf_e2e_ios/0/stdout

---
```
[smoke_catalina_start_up_ios] [STDOUT] stderr: [        ] Error running application on iPhone.
[smoke_catalina_start_up_ios] [STDOUT] stdout: [   +4 ms] "flutter run" took 53,520ms.
[smoke_catalina_start_up_ios] [STDOUT] stderr: [   +4 ms] 
[smoke_catalina_start_up_ios] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[smoke_catalina_start_up_ios] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:617:7)
[smoke_catalina_start_up_ios] [STDOUT] stderr:            <asynchronous suspension>
[smoke_catalina_start_up_ios] [STDOUT] stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:18)
[smoke_catalina_start_up_ios] [STDOUT] stderr:            <asynchronous suspension>
[smoke_catalina_start_up_ios] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:33)
[smoke_catalina_start_up_ios] [STDOUT] stderr:            <asynchronous suspension>
```
https://logs.chromium.org/logs/flutter/led/godofredoc_google.com/131f3dde81ce0d85410c00987bdcacd9c83a3aadb2e2e893f8b8076abc02e6b5/+/steps/run_smoke_catalina_start_up_ios/0/stdout

**Comment by xster** [comment]
Note for reference:

```
ios-deploy[1929:21390] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!

``` 

Means forgetting to xcode-select a newer xcode to be able to deploy to iOS 14.

**Comment by xster** [comment]
Cleared up a little bit. More failure types are being revealed. 

<img width="1263" alt="Screen Shot 2020-11-25 at 10 45 34 AM" src="https://user-images.githubusercontent.com/156888/100269427-5ad53500-2f0b-11eb-976e-e1eb550e97d5.png">

**Comment by jmagman** [comment]
The devicelab is on Xcode 12.3.
