### ISSUE TITLE
☂️ Scrollbar Fixes & Updates

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#70866]
This is an umbrella issue that covers several related issues for work being done on scrollbars.

- [x] Refactor Scrollbar and CupertinoScrollbar to share common methods
  - A couple of different RawScrollbar options have been discussed (https://github.com/flutter/flutter/pull/70850, https://github.com/flutter/flutter/pull/70798), the later being the current agreed upon direction.
  - [x] We should also fix this while we're at it: https://github.com/flutter/flutter/issues/70105
    - This is caused by explicitly creating a drag gesture in CupertinoScrollbar when dragging on the thumb. Instead, we should just update the position. Fix already produced in #70798
- [x] https://github.com/flutter/flutter/issues/31753: Scrollbars should be fully interactive
  - This includes dragging the thumb, tapping the track
  - CupertinoScrollbar already supports thumb dragging
- [ ] https://github.com/flutter/flutter/issues/40107: Scrollbars should be created by default for scrollables on Web and Desktop
  - will need to find a way to identify and exclude some cases, like TextFields and PageViews
- [x] https://github.com/flutter/flutter/issues/61362: Scrollbars should have a theme
  - Allows for customization across the app

Initial design doc:
flutter.dev/go/update-scrollbars

**Comment by xster** [comment]
If you're looking into reworking the scrollbar, it might be interesting to look at https://github.com/flutter/flutter/issues/13253 and avoid overlapping other slivers.

**Comment by Bwolfs2** [comment]
Will be able to add the gestureDetecture, Drag or Scroll when clicked on the ScrollBar?

**Comment by Piinks** [comment]
> Will be able to add the gestureDetecture, Drag or Scroll when clicked on the ScrollBar?

Yes

**Comment by lazylazyllama** [comment]
Will you also take care of the scrollbar with, which is very huge on android right now?

#72202

**Comment by khari998** [comment]
Do scrollbars work in SingleChildScrollViews in Flutter Web? I tried making this a request as it was renamed https://github.com/flutter/flutter/issues/43694

**Comment by Piinks** [comment]
@khari998 yes to all, please follow the linked changes for current status.

**Comment by lazylazyllama** [comment]
Now with the current implementation overscrolling by mouse with the draggable scrollbar in flutter web creates a bounce effect, which is typical for ios I think?

I don't know if macOS does it like this too, but on windows with Chrome it feels very weird. There shouldn't be such effect, it should just stop scrolling

**Comment by creativecreatorormaybenot** [comment]
@lazylazyllama This does not happen on Windows by default.

The overscroll glow is used instead on Chrome on Windows.

**Comment by lazylazyllama** [comment]
> @lazylazyllama This does not happen on Windows by default.
> 
> The overscroll glow is used instead on Chrome on Windows.

That is incorrect. I am not talking about scrolling by the mouse wheel. I am talking about dragging the scrollbar with the mouse, which is a new behavior. And it results in creating a bounce effect.

Here is some evidence:

![example](https://user-images.githubusercontent.com/10547444/102610216-18c79980-412d-11eb-9d26-b4ca57aef439.png)

**Comment by Piinks** [comment]
> Now with the current implementation overscrolling by mouse with the draggable scrollbar in flutter web creates a bounce effect

Thanks for finding and reporting this @lazylazyllama I have filed https://github.com/flutter/flutter/issues/72728 for the unintended overscroll.

**Comment by Sun3** [comment]
@Piinks I found a scenario that creates errors using the Scroolbar in Flutter Web. I filed the Flutter Web Scrollbar issue #[72814](https://github.com/flutter/flutter/issues/72814)

Summary:
## Steps to Reproduce by using Flutter Web

1. Add a Scrollbar to the Scaffold Body using a ScrollController
2. Run app and when you move your mouse inside the body you received the error 'Exception caught by gesture library'

Source Code:
```
ScrollController _scrollController = ScrollController();

body: Scrollbar(
  isAlwaysShown: true,
  thickness: 10.0,
  controller: _scrollController,
  child: SingleChildScrollView(
    controller: _scrollController,
    child: Form(
      key: _formStateKey,
      onChanged: _onFormChanged,
      onWillPop: _showSaveWarningDialog,
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Container(),
      ),
    ),
  ),
),
```

**Expected results:** 
Should not get errors.


Thank you.

**Comment by Piinks** [comment]
There is one remaining aspect of this issue that needs to be implemented, default instantiation. I've thought about this a lot, and have a few ideas, but most importantly we want to do this considerately. Some scrollables would not want auto-scrollbars, so we need to determine which those are and how to identify them. Also, we definitely would want to provide a way for users to control this feature, so no one is stuck with a scrollbar they cannot control or toggle on and off. 

I think this requires more thorough design and discussion, so I am going to re-open the individual issue for this: #40107 Please follow-up there on this specific feature.

Everything else in this 'umbrella' issues has landed, and so I am going to close this. 🎉

**Comment by HansMuller** [comment]
I'm reopening this issue per #40107; helps with out internal bookkeeping.

**Comment by nt4f04uNd** [comment]
pinging this here 
https://github.com/flutter/flutter/issues/74907#issuecomment-770267571
https://github.com/flutter/flutter/issues/74907#issuecomment-770267953

**Comment by franarolas** [comment]
Is there any way to paint the new Scrollbar class? As it ignores CustomPaint and ScrollbarThemeData.

**Comment by Piinks** [comment]
> Is there any way to paint the new Scrollbar class? As it ignores CustomPaint and ScrollbarThemeData.

Hi @franarolas can you file a separate issue with a reproduction and the output of `flutter doctor -v`? Thanks!

**Comment by franarolas** [comment]
@Piinks #75643

**Comment by Macacoazul01** [comment]
After this feature is released will be any short code sample showing how to use the new scroll on flutter web/desktop vs mobile?

**Comment by Sun3** [comment]
I am also looking for any insight on the Flutter Web scrollbars since I have a production app that relies on this feature.

Thank you.

**Comment by aliyazdi75** [comment]
https://github.com/flutter/flutter/issues/77609

**Comment by creativecreatorormaybenot** [comment]
@Piinks I am wondering (as I have not actively followed this): should we remove all manual scrollbars on web now? :)

**Comment by Macacoazul01** [comment]
@Piinks will the team release any document/post/sample teaching us how to use this new implemented scrollbar?

**Comment by Piinks** [comment]
> @Piinks I am wondering (as I have not actively followed this): should we remove all manual scrollbars on web now? :)

Hey @creativecreatorormaybenot! Only on desktop, since that is the platform we are applying them automatically now. Although, I did make some changes before then that makes it easier to change this to apply scrollbars on all platforms or no platforms... see https://github.com/flutter/flutter/pull/76739 for those changes. :) 

> @Piinks will the team release any document/post/sample teaching us how to use this new implemented scrollbar?

Hi @Macacoazul01 there is already some samples in the api docs on the master channel, like here: https://master-api.flutter.dev/flutter/material/Scrollbar-class.html
But there are also more PRs out to add to more, like here: https://github.com/flutter/flutter/pull/78284

**Comment by Sun3** [comment]
@Piinks Will the web platform receive the same automatic scrollbars apply as the desktop platform? I am hoping yes :)

Thank you.

**Comment by Piinks** [comment]
> @Piinks Will the web platform receive the same automatic scrollbars apply as the desktop platform? I am hoping yes :)

If the browser is running on a desktop platform, yes. Otherwise you can create your own `ScrollBehavior` and override `buildScrollbar` to change this setting to however you would like. :)

**Comment by Sun3** [comment]
Ok, if I understand correctly, for the web platform we should keep adding our own Scrollbar().

**Comment by GreenLim** [comment]
notice SingleChildScrollView is always show a scrollbar on desktop now, but how to invisible it ? I can not find a property related to hide the scrollbar.

**Comment by hillelcoren** [comment]
Here's a widget we use which shows/hides the scroll bar on hover

https://github.com/invoiceninja/flutter-client/blob/master/lib/ui/app/app_scrollbar.dart
