### ISSUE TITLE
Audit code in flutter/packages/* for null safety

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71506]
We should make sure all the code in flutter/packages/* has been migrated to null safety.

- [x] flutter
- [x] flutter_driver (TODO: https://github.com/flutter/flutter/issues/74849)
- [x] flutter_goldens (https://github.com/flutter/flutter/issues/74850)
- [x] flutter_goldens_client
- [x] flutter_localizations
- [x] flutter_test
- [x] flutter_tools (TODO: https://github.com/flutter/flutter/issues/71511)
- [x] flutter_web_plugins
- [x] fuchsia_remote_debugging_protocol
- [x] integration_test (TODO: https://github.com/flutter/flutter/issues/71379)

**Comment by goderbauer** [comment]
Updated top-level comment with a check list.

**Comment by goderbauer** [comment]
When any of the remaining packages is migrated, we should also remember to enable sound null safety for tests running on the bots here: https://github.com/flutter/flutter/blob/8043d6723e04d9d68f98e2289f6fe6b36b22a0a9/dev/bots/test.dart#L672

**Comment by parlough** [comment]
Closing this as fixed as the sub-tasks have all been closed as fixed and Dart only supports running in sound null safety mode, so if we're running Dart code, it is running with null safety now :D 

If anyone has any remaining follow-up tasks, please check for existing issues or open a new one with more details, thanks!
