### ISSUE TITLE
☂️ Lightweight Flutter Engines

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#72009]
## Description
This meta issue proposes an array of improvements to Flutter for supporting customers who want to use multiple Flutter instances in an app, focused on the Add-to-app use case.  It includes improvements for performance and ease-of-use.

## Design doc
http://flutter.dev/go/multiple-engines

#### iOS
- [x] API - iOS - https://github.com/flutter/flutter/issues/72010
- [x] Threads - iOS - https://github.com/flutter/flutter/issues/72019
- [x] Skia Contexts - iOS - https://github.com/flutter/flutter/issues/72021
- [x] GPU Contexts - iOS - https://github.com/flutter/flutter/issues/72022
#### Android
- [x] API - Android - https://github.com/flutter/flutter/issues/72018
- [x] Threads - Android - https://github.com/flutter/flutter/issues/72528
- [x] Skia Contexts - Android - https://github.com/flutter/flutter/issues/73597
- [x] GPU Contexts - Android - https://github.com/flutter/flutter/issues/73599
#### Shared
- [x] Fonts - https://github.com/flutter/flutter/issues/72024
- [x] Spawn -> Kill Spawner Integration test  - https://github.com/flutter/flutter/issues/72319
- [x] Documentation - https://github.com/flutter/flutter/issues/37644
- [x] Sample Code - https://github.com/flutter/flutter/issues/74530 (written, not landed, waiting for API to hit stable)
- [x] Handle thread merging (Crashing) - https://github.com/flutter/flutter/issues/73620
### Share Engine Components
- [x] IsolateGroups - https://github.com/flutter/flutter/issues/72025
### More performance tightening
- [ ] Squeeze an extraneous 0.1MB per engine from Android embedding - https://github.com/flutter/flutter/issues/74941
- [x] Squeeze an extraneous 0.32MB per engine from Dart VM - https://github.com/flutter/flutter/issues/74942
### FlutterView / FlutterEngine integration
- [x] Android FlutterView ergonomics- https://github.com/flutter/website/issues/7785
### Tests
- [x] Shared engine memory benchmark - https://github.com/flutter/flutter/issues/72026
- [ ] Spawn->Kill Integration test for Android - https://github.com/flutter/flutter/issues/72527
### Cleanup
- [ ] Refactor Spawn-> Kill integration test - https://github.com/flutter/flutter/issues/72525
- [x] Handle thread merging (platform views) - https://github.com/flutter/flutter/issues/73620
- [x] InitialRoute missing in the API - https://github.com/flutter/flutter/issues/78931

## Phase 3
- [ ] Async VM and Shell creation - https://github.com/flutter/flutter/issues/72028
- [ ] Easier engine↔engine interop - https://github.com/flutter/flutter/issues/33288
- [ ] Signal garbage collection only when all isolates are idle - https://github.com/flutter/flutter/issues/72031
- [ ] Cleanup non-visible view surfaces
- [ ] Shared image cache - https://github.com/flutter/flutter/issues/72033
- [ ] Consider separate UI threads per engine
- [ ] Create lightweight engines from existing FlutterEngineGroup in FlutterActivity/FlutterViewController - https://github.com/flutter/flutter/issues/72742

**Comment by foxsofter** [comment]
Good!

**Comment by xster** [comment]
As a preliminary check on the current state on the engine repo head, on a Pixel 3 with 5 runs with a mixture of force gc before each step and not, using the default create counter app as a test sample, creating 10 engines vs 1 engine costs 0.83mb extra per engine.

**Comment by xster** [comment]
Looking like iOS will be 1.13MB per additional engine on engine repo master head

**Comment by xster** [comment]
On the latest master head, the per engine overhead is just 180kB now for both Android and iOS. This matches our prototype more correctly.

**Comment by fengnudexiaoniao** [comment]
The memory is still increased by 32M（not ～180K ），when new FlutterViewController in ios 

each additional Flutter instance in new FlutterViewController beyond the first instance ，
The memory is still increased by 32m, not ～180K，Did you really test it? Do you provide any supporting data

**Comment by xster** [comment]
Running again on stable 2.0.1:

**1 engine:**
![Screen Shot 2021-03-05 at 10 42 05 AM](https://user-images.githubusercontent.com/156888/110159466-99e31400-7d9f-11eb-8338-273e198c5d68.png)

**2 engines:**
![Screen Shot 2021-03-05 at 10 42 55 AM](https://user-images.githubusercontent.com/156888/110159471-9bacd780-7d9f-11eb-9096-e95d43045813.png)

The 2 engine case happens to be smaller than the 1 engine case since it's within the margin of error. We took the 180kB measurement by taking many runs and taking the median number. 

Also on the VM tracker:

**1 engine:**
![Screen Shot 2021-03-05 at 10 46 14 AM](https://user-images.githubusercontent.com/156888/110160125-75d40280-7da0-11eb-904d-f3f85f161010.png)

**2 engines:**
![Screen Shot 2021-03-05 at 10 46 55 AM](https://user-images.githubusercontent.com/156888/110160145-7bc9e380-7da0-11eb-86bb-a20cd68d3ccd.png)

It takes a bit of work to get the right number (and then de-noise it again by taking multiple runs). We have to remove the "Performance tool data" memory from both the before and after's dirty size to get the real application memory consumption. But you can see the ballpark at least. 

Also note, the measured memory is the cost of the Flutter Engine supporting a second engine (which includes the Java/Obj-C bootstrapping classes, a second instance of the core C++ engine, a second Dart isolate etc) and the cost of a second Flutter Framework instance (all the Flutter Dart layers from Foundation to Material) in a minimal app. If you have a full Flutter application which consumes memory itself (such as reading files, downloading network resources etc) and then create a second instance of your application, it'll likely consume 2x the memory. It would be upon you, the user, to modularize your code to run separate code (such as via different entrypoints) to show separate UI on multiple Flutter instances as needed. 

Also follow https://github.com/dart-lang/sdk/issues/36097 for future plans on sharing Dart data between isolates and https://github.com/flutter/flutter/issues/72033 for potentially sharing image caches between Flutter instances.

**Comment by iLees** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.0 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.

code：
`
class HostViewController: UIViewController, DataModelObserver {
  @IBOutlet weak var countView: UILabel!
    let appdelegate = UIApplication.shared.delegate as? AppDelegate

  deinit {
    UIApplication.shared.keyWindow?.backgroundColor = UIColor.white;
  }

  func onCountUpdate(newCount: Int64) {
    self.countView.text = String(format: "111111%d", newCount)
  }

  @IBAction func onAddCount() {
    DataModel.shared.count = DataModel.shared.count + 1
  }

  @IBAction func onNext() {
    let navController = self.navigationController!
    let vc = SingleFlutterViewController(withEntrypoint: nil)
    navController.pushViewController(vc, animated: true)
  } 
}

class SingleFlutterViewController: FlutterViewController, DataModelObserver {
  private var channel: FlutterMethodChannel?

  init(withEntrypoint entryPoint: String?) {
    let appDelegate: AppDelegate = UIApplication.shared.delegate as! AppDelegate
    let newEngine = appDelegate.engines.makeEngine(withEntrypoint: entryPoint, libraryURI: nil)
    super.init(engine: newEngine, nibName: nil, bundle: nil)
  }

  required init(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }

  func onCountUpdate(newCount: Int64) {
    if let channel = channel {
      channel.invokeMethod("setCount", arguments: newCount)
    }
  }

  override func viewDidLoad() {
    super.viewDidLoad()
    channel = FlutterMethodChannel(
      name: "multiple-flutters", binaryMessenger: self.engine!.binaryMessenger)
    channel!.invokeMethod("setCount", arguments: DataModel.shared.count)
    let navController = self.navigationController!
    channel!.setMethodCallHandler { (call: FlutterMethodCall, result: @escaping FlutterResult) in
      if call.method == "incrementCount" {
        DataModel.shared.count = DataModel.shared.count + 1
        result(nil)
      } else if call.method == "next" {
        let vc = SingleFlutterViewController(withEntrypoint: nil)
        navController.pushViewController(vc, animated: true)
      } else {
        result(FlutterMethodNotImplemented)
      }
    }
  }
}

`

Xcode run profile :
![8EAD48A3D8A1D1392ED2BE8F7E680CBB](https://user-images.githubusercontent.com/13429343/110284122-416c7a80-801c-11eb-8ad6-70524f863d5d.jpg)

<img width="1294" alt="截屏2021-03-08 下午2 35 05" src="https://user-images.githubusercontent.com/13429343/110284289-885a7000-801c-11eb-89f6-f616de9cc2f0.png">

click the next button：
![8A9213D7C8ACB32C75979315A6CCE1BE](https://user-images.githubusercontent.com/13429343/110284371-acb64c80-801c-11eb-8983-74e17adfe342.jpg)
Persistent Memory ：2.36MB

<img width="1287" alt="截屏2021-03-08 下午2 35 42" src="https://user-images.githubusercontent.com/13429343/110284380-b17b0080-801c-11eb-9012-5751a915f3d9.png">
Persistent Memory ：45.35MB

click the next button of the flutter page：
<img width="1286" alt="截屏2021-03-08 下午2 35 57" src="https://user-images.githubusercontent.com/13429343/110284525-e8511680-801c-11eb-89cd-87be33400b4a.png">
Persistent Memory ：88.51MB

**Comment by gaaclarke** [comment]
@iLees I pulled out your report in an issue so it can be investigated.  ( https://github.com/flutter/flutter/issues/77621 )

**Comment by krmao** [comment]
very very good !

**Comment by iLees** [comment]
> @iLees I pulled out your report in an issue so it can be investigated. ( #77621 )

Fine, I get it.

**Comment by iprox** [comment]
hi folks, according to the https://flutter.dev/docs/development/add-to-app/multiple-flutters

>  Warning: In 2.0.0, the use of platform views is not supported in conjunction with multiple Flutters. When a second Flutter instance is created, platform views will be globally disabled.

is it planned to remove the limitation above?

**Comment by krmao** [comment]
1. engines can't set initialRoute
2. engines render need **splash view** if engine render slower while from one FlutterViewController push to another FlutterViewController, current release may delay 30ms and then push will looks like ok

**Comment by xlgoodman** [comment]
I found this [thrio](https://github.com/flutter-thrio/flutter_thrio)

**Comment by gaaclarke** [comment]
> now I have found few problems by used multi engine with android/ios:
> 
> 1. engines can't set initialRoute

Couldn't you set the initial route in your entrypoint?

> 2. engines render need **splash view** if engine render slower while from one FlutterViewController push to another FlutterViewController, current release may delay 30ms and then push will ios looks like ok, android need transparent looks like ok but a little delay

You are talking about the first FlutterEngine in a FlutterEngineGroup, right?  We've talked about having a call that can prewarm a FlutterEngineGroup, and potentially keep it warmed at a cost to memory.  That seems like it would help you.

> 3. now ios releame every FlutterViewController with engines increase 11-13MB not 180k, android is about 3MB each FlutterViewActivity

If you look above in this conversation there is an outstanding issue on iOS where resources are cached then released when under memory pressure, we are trying to make that behavior more deterministic (https://github.com/flutter/flutter/issues/77621).  The actual cost of an engine will depend on what is happening in the code, each engine still has its own heap for example.  The numbers we used were with a minimal sample project.  The ongoing memory benchmark for Android can be found [here](https://flutter-flutter-perf.skia.org/e/?queries=test%3Dlinux_flutter_engine_group_performance) and [here](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_engine_group_performance.dart).

**Comment by krmao** [comment]
thanks to the reply . 

> > now I have found few problems by used multi engine with android/ios:
> > 
> > 1. engines can't set initialRoute
> 
> Couldn't you set the initial route in your entrypoint?
> 

only first FlutterEngine in a FlutterEngineGroup can set initialRoute.
set the initial route in entrypoint  you mean set dartEntrypointFunctionName ? this could be work by set multi **@pragma('vm:entry-point')**.

of course it's already great !
if the spawn engine could set initialroute, may the code looks good and all engines can use the same entry-point with different definition in **MaterialApp.routes**
```
void initAndRunApp(RoutesBuilder routesBuilder) {
  appRun(routesBuilder);
}

//region dartEntrypointFunctionName 仅比 initialRoute 多一个 main 前缀, 方便以后灵活的切换 '多引擎单路由' / '单引擎多路由'
@pragma('vm:entry-point')
void mainFlutterBridge() =>
    initAndRunApp((String uniqueId, String argumentsJsonString) => {
          '/': (BuildContext context) => BasePageDefault(
              state: BridgeWidgetState(
                  uniqueId: uniqueId, argumentsJsonString: argumentsJsonString))
        });

@pragma('vm:entry-point')
void mainFlutterSettings() =>
    initAndRunApp((String uniqueId, String argumentsJsonString) => {
          '/': (BuildContext context) => BasePageDefault(
              state: SettingsState({},
                  uniqueId: uniqueId, argumentsJsonString: argumentsJsonString))
        });
```

FlutterEngineGroup.java
> The engine needs to receive the Flutter app's initial route before executing any Dart code to ensure that the initial route arrives in time to be applied.

```
  public FlutterEngine createAndRunEngine(
      @NonNull Context context, @Nullable DartEntrypoint dartEntrypoint) {
    FlutterEngine engine = null;

    if (dartEntrypoint == null) {
      dartEntrypoint = DartEntrypoint.createDefault();
    }

    if (activeEngines.size() == 0) {
      engine = createEngine(context);
      engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
    } else {
      engine = activeEngines.get(0).spawn(context, dartEntrypoint);

            
            // The engine needs to receive the Flutter app's initial route before executing any
            // Dart code to ensure that the initial route arrives in time to be applied.
            // engine.getNavigationChannel().setInitialRoute(initialRoute);
    }

    activeEngines.add(engine);
```

> > 1. engines render need **splash view** if engine render slower while from one FlutterViewController push to another FlutterViewController, current release may delay 30ms and then push will ios looks like ok, android need transparent looks like ok but a little delay
> 
> You are talking about the first FlutterEngine in a FlutterEngineGroup, right? We've talked about having a call that can prewarm a FlutterEngineGroup, and potentially keep it warmed at a cost to memory. That seems like it would help you.
> 
no, I mean the spawn engine, the second or more engine with new FlutterViewController.
now my delay code

```
+(void) openNewFlutterViewControllerByName:(UIViewController* _Nullable)fromViewController pageName:(NSString* _Nullable) pageName pageParams:(NSDictionary* _Nullable) pageParams{
    NSLog(@"openNewFlutterViewControllerByName pageName=%@, pageParams=%@", pageName, pageParams);
    UINavigationController *navigationController = [fromViewController isKindOfClass:[UINavigationController class]] ? (UINavigationController*)fromViewController : fromViewController.navigationController;
    
    NSString* initialRoute = pageName;
    NSString* finalDartEntrypointFunctionName = (![STFlutterInitializer sharedInstance].enableMultiEnginesWithSingleRoute || [initialRoute isEqualToString: @"/"]) ? @"main" : [NSString stringWithFormat:@"main%@",initialRoute];
    // NSString* finalInitialRoute = (![STFlutterInitializer sharedInstance].enableMultiEnginesWithSingleRoute)? initialRoute : @"/";
    
    STFlutterMultipleViewController *flutterViewController = [[STFlutterMultipleViewController alloc] initWithDartEntrypointFunctionName:finalDartEntrypointFunctionName];
    
    [flutterViewController setRequestData:0 requestData: @{@"argumentsJsonString":pageParams[@"argumentsJsonString"]}];
    
    int delta = 20 * NSEC_PER_MSEC;
    #if defined(DEBUG)
        NSLog(@"BUILD-TYPE -> DEBUG");
        delta = 300 * NSEC_PER_MSEC; // DEBUG >= 300
    #else
        NSLog(@"BUILD-TYPE -> RELEASE");
        delta = 20 * NSEC_PER_MSEC; // RELEASE >= 20
    #endif
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, delta), dispatch_get_main_queue(), ^{
        [navigationController pushViewController:flutterViewController animated:YES];
    });
}
```

**Comment by wei120698598** [comment]
> Running again on stable 2.0.1:
> 
> **1 engine:**
> ![Screen Shot 2021-03-05 at 10 42 05 AM](https://user-images.githubusercontent.com/156888/110159466-99e31400-7d9f-11eb-8338-273e198c5d68.png)
> 
> **2 engines:**
> ![Screen Shot 2021-03-05 at 10 42 55 AM](https://user-images.githubusercontent.com/156888/110159471-9bacd780-7d9f-11eb-9096-e95d43045813.png)
> 
> The 2 engine case happens to be smaller than the 1 engine case since it's within the margin of error. We took the 180kB measurement by taking many runs and taking the median number.
> 
> Also on the VM tracker:
> 
> **1 engine:**
> ![Screen Shot 2021-03-05 at 10 46 14 AM](https://user-images.githubusercontent.com/156888/110160125-75d40280-7da0-11eb-904d-f3f85f161010.png)
> 
> **2 engines:**
> ![Screen Shot 2021-03-05 at 10 46 55 AM](https://user-images.githubusercontent.com/156888/110160145-7bc9e380-7da0-11eb-86bb-a20cd68d3ccd.png)
> 
> It takes a bit of work to get the right number (and then de-noise it again by taking multiple runs). We have to remove the "Performance tool data" memory from both the before and after's dirty size to get the real application memory consumption. But you can see the ballpark at least.
> 
> Also note, the measured memory is the cost of the Flutter Engine supporting a second engine (which includes the Java/Obj-C bootstrapping classes, a second instance of the core C++ engine, a second Dart isolate etc) and the cost of a second Flutter Framework instance (all the Flutter Dart layers from Foundation to Material) in a minimal app. If you have a full Flutter application which consumes memory itself (such as reading files, downloading network resources etc) and then create a second instance of your application, it'll likely consume 2x the memory. It would be upon you, the user, to modularize your code to run separate code (such as via different entrypoints) to show separate UI on multiple Flutter instances as needed.
> 
> Also follow [dart-lang/sdk#36097](https://github.com/dart-lang/sdk/issues/36097) for future plans on sharing Dart data between isolates and #72033 for potentially sharing image caches between Flutter instances.
> 
> If you share a simple reproduction project for your case, we can take a look to debug as well. It's very possible we have a bug as well.

What is tool?

**Comment by gaaclarke** [comment]
> What is tool?

Xcode / Instruments

**Comment by zsunkun** [comment]
Is there any plan to support Platform Views?  When will it be supported?

**Comment by gaaclarke** [comment]
@zsunkun It's not being actively developed, you can track it / upvote here: https://github.com/flutter/flutter/issues/73620

**Comment by SivaramSS** [comment]
Any update on Software Transactional Memory? Badly in need of a shared memory to share images without sending as message and decoding on the main isolate.

**Comment by zsunkun** [comment]
@xster Any update on [DataSync](https://docs.google.com/document/d/1yH96-p-SkMmt6hL5xHHDtMvCKRz2XGrMuw9ZY_nE954/edit?pli=1#heading=h.d69w0eu7mr7t)? This is essential for using multiple Engines in complex scenarios.

**Comment by gaaclarke** [comment]
@zsunkun DataSync is still planned but is lower priority.  Please see this Flutter sample on how to create your own solution for synchronizing data across multiple engines: https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters

**Comment by Danopie** [comment]
@gaaclarke I tested with the latest stable (2.5.3) on android and see that we can use FlutterEngineGroup along with PlatformViews such as google_maps_flutter and webview_flutter. Switching to hybrid composition mode, however, causes the app to crash. I cannot reproduce it on master. Is this related to #73620?

**Comment by gaaclarke** [comment]
@Danopie I'm surprised that platform views work for you at all on 2.5.3.  The feature hasn't hit stable yet: https://github.com/flutter/flutter/commit/1c6d2633ef5df46ea45c5aeb3683afe4930a15bb

Try out the `2.8.0-3.2.pre` branch that looks like the most recent branch that will probably lead to the next stable release in Q1 2022.

**Comment by marziman** [comment]
Hello @gaaclarke can you please help us or am I wrong in this thread?

We have the following scenario:
- From one Android/Flutter app, we need to draw UIs on 2 screens with different content
- We are starting 2 Flutter Engines and want them to communicate with each other to share data, navigation state as they together make up one "logical bigger app".

Could be use the multiple Flutters feature for this?
Currently we are having 2 completely isloated FlutterEngines and same code loaded in both enignes.
We are than doing some kinda a IPC communication by native platform channels (message service) to make those 2 FlutterEngines know each other. 

Your help would be much appreciated.
Thanks!
Mehmet

**Comment by yanwei49** [comment]
> @zsunkun DataSync is still planned but is lower priority. Please see this Flutter sample on how to create your own solution for synchronizing data across multiple engines: https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters

I downloaded your demo and compiled it in the release mode of IOS real machine, and the result reported an error: nosuchmethoderror: no top-level getter 'bottommain' declared

Receiver: top-level，Tried calling: bottomMain, stack trace: #0 NoSuchMethodError._ Thrownew (dart:core-patch/errors_patch.dart:222) multiplefluttersios[4219:2013305] [verbose-2:dart_isolate.cc (681)] could not resolve main entry point function Could not run the run main Dart entrypoint. Could not create root isolate. Could not launch engine with configuration.

It is normal in debug mode. 
My fluent -- version:
Flutter 2.10.6-0.0.pre.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db1bda399e (83 minutes ago) • 2022-04-24 19:24:50 +0800
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

My iphone info: iPhone 7 , systom: iOS14.0

**Comment by krmao** [comment]
android FlutterEngineGroup destroyEngine false

SystemChrome.setSystemUIOverlayStyle only first time open work

**Comment by lubritto** [comment]
Hello @gaaclarke, I found an interesting issue with the EngineGroups that is actually easy to reproduce and would like to understand if it's a known behavior or not.

On the MultipleFlutters example project, when adding any platform view (WebView, GoogleMaps) to the Flutter screen, everything works normally. But there's a bug happening when the **first engine of the group was never loaded into a ViewController**, when moving from one screen with PlatformView to another screen with/without platform view, the next engine crashes with EmptyScreen, and no logs on Native neither on Flutter.

To give a bit more context, in our project, we have a UI Less Engine that is always alive like an API to get some information from Flutter. We usually load it in the app startup to check if the deep link is available or not on the Flutter side before opening an engine, that's why this engine has no view controller attached to it.

I'm working to provide the minimum reproducible code soon.

<img height="400" src="https://github.com/flutter/flutter/assets/14953997/5a4883b8-f0d9-41f7-82a7-6cdadf740354" />

**Comment by dodatw** [comment]
About FlutterEngineGroup + PlatfromView Crash, may be same issue https://github.com/flutter/flutter/issues/127168

**Comment by mkustermann** [comment]
> About FlutterEngineGroup + PlatfromView Crash, may be same issue https://github.com/flutter/flutter/issues/127168

https://github.com/flutter/flutter/issues/127168 has been fixed now.

**Comment by dodatw** [comment]
> > About FlutterEngineGroup + PlatfromView Crash, may be same issue https://github.com/flutter/flutter/issues/127168
> 
> #127168 has been fixed now.

Which version invlude this fixing?
I tried flutter 3.13.7 still can reporduce this issue.

**Comment by jonahwilliams** [comment]
Given that most work has been complete here I think the meta issue has outlived its usefullness and I'm closing it. remaining work can be tracked in the individual bugs.
