### ISSUE TITLE
Flutter crash on startup (metabug)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7314]
```
$ rm -rf build; flutter run --pid-file /tmp/run.pid
Running 'flutter packages get' in dummy...          819ms
Launching lib/main.dart on Nexus 6 in debug mode...
Building APK in debug mode (android-arm)...         6694ms
Installing build/app.apk...                         14400ms
Diagnostic server listening on http://127.0.0.1:8101
Observatory listening on http://127.0.0.1:8100/
Request to Dart VM Service timed out: getIsolate({isolateId: isolates/645436071})
Exception from flutter run: TimeoutException after 0:00:10.000000: Future not completed
dart:async                                                 _Completer.completeError
package:flutter_tools/src/vmservice.dart 589               VM.invokeRpcRaw.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_tools/src/vmservice.dart                   VM.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 754               Isolate.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 740               Isolate._fetchDirect
package:flutter_tools/src/vmservice.dart 288               ServiceObject.reload.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/vmservice.dart                   ServiceObject.reload
package:flutter_tools/src/vmservice.dart 259               ServiceObject.load.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/vmservice.dart                   ServiceObject.load
package:flutter_tools/src/vmservice.dart 532               VM.getFromMap
package:flutter_tools/src/vmservice.dart 173               _upgradeList
package:flutter_tools/src/vmservice.dart 162               _upgradeMap.<fn>
dart:collection                                            _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach
package:flutter_tools/src/vmservice.dart 158               _upgradeMap
package:flutter_tools/src/vmservice.dart 151               _upgradeCollection
package:flutter_tools/src/vmservice.dart 450               VM._update
package:flutter_tools/src/vmservice.dart 330               ServiceObject.update
package:flutter_tools/src/vmservice.dart 293               ServiceObject.reload.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 581               VM.invokeRpcRaw.<async>
dart:async                                                 _SyncCompleter.complete
package:json_rpc_2/src/client.dart 174                     Client._handleSingleResponse
package:json_rpc_2/src/client.dart 164                     Client._handleResponse
dart:async                                                 _StreamController.add
package:json_rpc_2/src/peer.dart 91                        Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/vmservice.dart                   ServiceObject.reload
package:flutter_tools/src/vmservice.dart 124               VMService.getVM
package:flutter_tools/src/resident_runner.dart 139         ResidentRunner.connectToServiceProtocol.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 47                VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/resident_runner.dart             ResidentRunner.connectToServiceProtocol
package:flutter_tools/src/hot.dart 192                     HotRunner._run.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 366  AndroidDevice.startApp.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/protocol_discovery.dart 74       ProtocolDiscovery.nextUri.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 718  _AndroidDevicePortForwarder.forward.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                         HotRunner._run
package:flutter_tools/src/hot.dart 88                      HotRunner.run.<fn>
package:stack_trace                                        Chain.capture
package:flutter_tools/src/hot.dart 87                      HotRunner.run
package:flutter_tools/src/commands/run.dart 245            RunCommand.runCommand.<async>

Request to Dart VM Service timed out: _flutter.listViews({})
Error connecting to the service protocol: TimeoutException after 0:00:10.000000: Future not completed
```

From `adb logcat`, all the output for the process that at some point uses the `flutter` tag (we really should show more of this in the `flutter run` output, especially the error messages):
```
12-27 11:01:23.130 21027 21027 I art     : Late-enabling -Xcheck:jni
12-27 11:01:23.132  2202  9075 I ActivityManager: Start proc 21027:com.yourcompany.dummy/u0a162 for activity com.yourcompany.dummy/org.domokit.sky.shell.SkyActivity
12-27 11:01:23.246 21027 21027 I cr.library_loader: Time to load native libraries: 22 ms (timestamps 7511-7533)
12-27 11:01:23.246 21027 21027 I cr.library_loader: Expected native library version number "", actual native library version number ""
12-27 11:01:23.420 21027 21027 E ApkAssets: Error while loading asset assets/icudtl.dat: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
12-27 11:01:23.441 21027 21027 I Adreno  : QUALCOMM build                   : 74df444, I409c65498b
12-27 11:01:23.441 21027 21027 I Adreno  : Build Date                       : 06/22/16
12-27 11:01:23.441 21027 21027 I Adreno  : OpenGL ES Shader Compiler Version: XE031.08.00.02
12-27 11:01:23.441 21027 21027 I Adreno  : Local Branch                     : N16
12-27 11:01:23.441 21027 21027 I Adreno  : Remote Branch                    :
12-27 11:01:23.441 21027 21027 I Adreno  : Remote Branch                    :
12-27 11:01:23.441 21027 21027 I Adreno  : Reconstruct Branch               :
12-27 11:01:23.544 21027 21054 I OpenGLRenderer: Initialized EGL, version 1.4
12-27 11:01:23.544 21027 21054 D OpenGLRenderer: Swap behavior 1
12-27 11:01:23.914 21027 21074 I flutter : Diagnostic server listening on http://127.0.0.1:47897
12-27 11:01:23.929 21027 21074 I flutter : Observatory listening on http://127.0.0.1:47861/
12-27 11:01:24.594 21027 21048 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 21048 (ui_thread)
12-27 11:01:24.597   270   270 W         : debuggerd: handling request: pid=21027 uid=10162 gid=10162 tid=21048
12-27 11:01:24.636   270   270 W         : debuggerd: resuming target 21027
12-27 11:01:24.693  2202  9074 I ActivityManager: Process com.yourcompany.dummy (pid 21027) has died
12-27 11:01:24.693  2202  9074 D ActivityManager: cleanUpApplicationRecord -- 21027
```

There's lots of changes to the Dart code of this app, but nothing that should be able to cause a crash.

**Comment by Hixie** [comment]
Things that should be resolved here:
- [ ] Flutter tool shouldn't dump a huge stack trace when it times out.
- [ ] Flutter tool should give a pretty error message saying that the engine may have crashed, rather than "Request to Dart VM Service timed out: getIsolate({isolateId: isolates/645436071})" which doesn't mean much to our users.
- [ ] Indeed, the Flutter tool should know that the engine has crashed, and say so for sure, along with the reason why.
- [ ] Flutter tool should show all the error messages from the logs.
- [ ] Flutter engine shouldn't output anything that isn't an error message (e.g. why are we outputting that stuff on the `Adreno` tag, or the `OpenGLRenderer` tag?)
- [ ] Flutter engine should give more information when it crashes, so that we can debug the crash. There's no stack trace or anything.
- [ ] We shouldn't use `com.yourcompany`. Not sure how we figure out what to use, but that shouldn't be it.
- [ ] The `ApkAssets` error.
- [ ] The `cr.library_loader` error.
- [ ] The crash itself.
- [ ] That I had to `rm -rf build`.
- [ ] That we say "Launching" before we have even built or installed the app.
- [ ] That we output the "diagnostic server listening" and "observatory listening" lines.

**Comment by chinmaygarde** [comment]
> Flutter engine shouldn't output anything that isn't an error message (e.g. why are we outputting that stuff on the Adreno tag, or the OpenGLRenderer tag?)

Thats not Flutter. It the system logging basic information on `eglInitialize`.

**Comment by Hixie** [comment]
Yeah, I figured. I don't suppose we can silence it somehow?

**Comment by bkonyi** [comment]
Closing since there's been no activity on this issue for years and many of these crashes have likely been resolved / captured in other issues.
