### ISSUE TITLE
☂️ Migrate all first-party plugins to NNBD

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#75247]
Everything in flutter/plugins needs to be migrated to null-safety. There has been some accidental duplication of effort in the community, and there's also no easy place for interested parties to track the remaining progress, so this will serve as an overview and a way to find the relevant issues.

Community contributions are welcome! If you are interested in porting a plugin or package, please check that it's not already assigned, and comment in the relevant issue to say that you are working on it (and if it's a federated plugin, which specific sub-package(s)), to reduce the chance of duplicate effort.

flutter/plugins:
- [ ] [`android_alarm_manager`](https://github.com/flutter/flutter/issues/75233)
- [x] `android_intent`
- [x] `battery`
- [ ] [`camera`](https://github.com/flutter/flutter/issues/75228)
- [ ] `connectivity`
  - Mostly done, but [web](https://github.com/flutter/flutter/issues/68669) needs to be migrated and re-endorsed.
- [x] `cross_file`
- [x] `device_info`
- [ ] ~`e2e`~ N/A; replaced by `integration_test`
- [x] `espresso` - Contains no Dart code, so no migration needed
- [ ] [`file_selector`](https://github.com/flutter/flutter/issues/75235)
- [x] `flutter_plugin_android_lifecycle`
- [ ] [`google_maps_flutter`](https://github.com/flutter/flutter/issues/75236)
- [x] `google_sign_in`
- [ ] [`image_picker`](https://github.com/flutter/flutter/issues/75162)
- [ ] [`in_app_purchase`](https://github.com/flutter/flutter/issues/75237)
- [ ] `integration_test`
  - Being moved to `flutter/flutter`, where NNBD migrations has finished. Status of flutter/plugins version TBD.
- [ ] [`ios_platform_images`](https://github.com/flutter/flutter/issues/75238)
- [x] `local_auth`
- [ ] [`package_info`](https://github.com/flutter/flutter/issues/75239)
- [ ] [`path_provider`](https://github.com/flutter/flutter/issues/75240)
- [x] `plugin_platform_interface`
- [ ] [`quick_actions`](https://github.com/flutter/flutter/issues/75241)
- [ ] [`sensors`](https://github.com/flutter/flutter/issues/75242)
- [x] `share`
- [ ] [`shared_preferences`](https://github.com/flutter/flutter/issues/74876)
- [ ] `url_launcher`
  - Mostly done, but [web](https://github.com/flutter/flutter/issues/75244) needs to be migrated and re-endorsed.
- [x] `video_player`
- [x] `webview_flutter`
- [ ] [`wifi_info_flutter`](https://github.com/flutter/flutter/issues/75246)

**Comment by kevmoo** [comment]
I noticed we're super close to `path_provider`. Woo hoo!
