### ISSUE TITLE
[cocoon] Create scheduler service

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#76140]
flutter/cocoon has several separate locations for scheduling. Unifying it all behind a single service will make it easier to track the scheduling logic Cocoon has.

Currently there are separate request handlers for scheduling initial tasks and retrying these tasks. Instead, there should be a scheduler service the request handlers call.

This will make it cleaner to schedule against webhooks while still supporting the cron methods.

## Checklist
- [X] Create scheduler service - https://github.com/flutter/cocoon/pull/1087
- [X] Schedule prod tasks on GitHub webhook - https://github.com/flutter/cocoon/pull/1109
- [X] Recipes support checkouts from GitHub instead of GoB
- [x] Schedule postsubmit targets from `.ci.yaml` - https://github.com/flutter/flutter/issues/81795
- [x] Validate `.ci.yaml` changes in presubmit - https://github.com/flutter/flutter/issues/79579
- [x] Support presubmit targets - https://github.com/flutter/flutter/issues/77858
- [x] Prod LUCI tasks are updated - https://github.com/flutter/cocoon/pull/1210
 - [x] Deprecate "validate_json" step: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/json_util/api.py

**Comment by CaseyHillers** [comment]
Initial PR reverted as Cocoon stopped picking up new commits. Looking at the logs, there was no errors being thrown. Instead, Cocoon wasn't recognizing any of the latest GitHub commits as being new, so it wasn't processing them.

**Comment by CaseyHillers** [comment]
This work is complete. Future feature work (such as postsubmit scheduling) is being tracked in separate issues.
