### ISSUE TITLE
Umbrella issue: infrastructure/test cherrypicks for 2.0.x stable branch

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#78064]
- [x] `complex_layout_ios__start_up` brings up a system dialog that makes next tests fail. #75048
- [x] `ios_platform_view_tests` fail when device is rotated in landscape https://github.com/flutter/flutter/issues/75648
- [x] `flutter_gallery__transition_perf_e2e_ios` and `flutter_gallery_ios__transition_perf` fail when device is rotated in landscape https://github.com/flutter/flutter/issues/75647
- [x] FIx devicelab reboot https://github.com/flutter/flutter/issues/76027

**Comment by christopherfujino** [comment]
> Another one needs to be picked up [#77981 (comment)](https://github.com/flutter/flutter/issues/77981#issuecomment-797848946)?

Thanks, added it

**Comment by kf6gpe** [comment]
Here's one more: 
`NoSuchMethodError: The method ‘cancel’ was called o null at AnsiSpinner:finish`
https://github.com/flutter/flutter/issues/75677
fb0b7671b495273a1ab201fb624ed4a2a2f0550a
