### ISSUE TITLE
[video_player] video, audio and text track selections

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#79079]
## Use case
There have been multiple requests to support getting and setting `trackSelection`s.
- https://github.com/flutter/flutter/issues/59437

## Proposal
Providing an easy way to get all types of `trackSelections` (like video, audio, and text) and set the requested track selection.
The current video player uses `auto` quality. `trackSelection`s are useful to change the qualities of video and audio manually and choose the text `trackSelection` which could be a caption in this proposal. Since the current video player uses a widget to present captions, this can't be done by backed like `exoplayer` and needs to extract all embedded subtitle files by some tools like `ffmpeg` for `mp4` video files, then providing a method that returns a string of current subtitle file.

Some workarounds have been done in this repository (https://github.com/aliyazdi75/plugins/tree/feature_track_selection) that supports `android` getting and setting `trackSelection`, but not the subtitle method mentioned above and I needed to take some feedback about it. I haven't started the `ios` and `web` sides because I wanted to make sure that are some good methods to implement this amazing feature.

## TODO
[] Get list of `trackselection` include `auto` with their specifications for `video`, `audio` and `text` ([x] `android`, [] `ios` and [] `web`)
[x] Provideing a class (`TrackSelectionNameResource`) which helps to change the suggestion `trackName` by the specific strings.
[] Set the requested `trackSelection` include `auto` for `video`, `audio` and `text` ([x] `android`, [] `ios` and [] `web`)
[] Providing a method to get the string of the currently embedded subtitle file ([] `android`, [] `ios` and [] `web`)

**Comment by TejasDhanda-L11** [comment]
could you provide example app something simple so we can understand how to implement track selection in android

**Comment by aliyazdi75** [comment]
> could you provide example app something simple so we can understand how to implement track selection in android

It's already implemented in the example.

**Comment by ForgottenUmbrella** [comment]
Is it possible to deselect text tracks with your fork, like https://developer.android.com/reference/android/media/MediaPlayer#deselectTrack(int)?

**Comment by nateshmbhat** [comment]
any update on this issue ? this will be very nice feature addition

**Comment by Gustl22** [comment]
> Providing a method to get the string of the currently embedded subtitle file. 

Regarding getting the current subtitle, one can listen to the `onCues` events, to get the current subtitles (after setting the track of course in the mentioned PR):

```kotlin

internal interface VideoPlayerCallbacks {
    // ...
    override fun onCues(cueGroup: CueGroup) {
        events.onTextTrackUpdate(cueGroup.cues)
    }
}
    

internal class VideoPlayerEventCallbacks private constructor(private val eventSink: EventSink) : VideoPlayerCallbacks {
    // ...
    override fun onTextTrackUpdate(cues: List<Cue>) {
        val event: MutableMap<String, Any> = HashMap()
        event["event"] = "textTrackUpdate"
        event["cues"] = cues.map {
            // For docs, see: https://developer.android.com/reference/kotlin/androidx/media3/common/text/Cue
            hashMapOf(
                "size" to it.size,
                "text" to it.text,
                "textSize" to it.textSize,
                "textAlignment" to it.textAlignment?.name,
                "position" to it.position,
                "positionAnchor" to it.positionAnchor,
                "line" to it.line,
                "lineAnchor" to it.lineAnchor,
                "windowColor" to it.windowColor,
            )
        }
        eventSink.success(event)
    }
}
```

**Comment by abdoutech93** [comment]
I did the major of the work and I did a pull request but I was not able to merge it, if some one would continue. 

I remember I implemented : 

- [x] Get all sounds inside the video 
- [x] get all closed captions inside the video
- [ ] select a sound 
- [ ] select a closed captions

**Comment by ezamagni** [comment]
https://github.com/flutter/packages/pull/9925 looks very promising 🤞

**Comment by abdoutech93** [comment]
> I did the major of the work and I did a pull request but I was not able to merge it, if some one would continue. 
> 
> https://github.com/flutter/packages/pull/5548
> 
> I remember I implemented : 
> 
> - [x] Get all sounds inside the video 
> - [x] get all closed captions inside the video
> - [ ] select a sound 
> - [ ] select a closed captions 
> 
> 

Someone can helps to finalize this work 🫣 ?
