### ISSUE TITLE
☂ Enable Windows UWP builds

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#82085]
Items required for UWP builds:

### Build tooling
* [x] Land `uwptool` (https://github.com/flutter/flutter/issues/81756)
  * [X] listapps (https://github.com/flutter/engine/pull/26038)
  * [X] launch (https://github.com/flutter/engine/pull/26038, https://github.com/flutter/engine/pull/26105)
  * [x] launch arguments (https://github.com/flutter/engine/pull/26038)
  * [x] install (https://github.com/flutter/flutter/issues/82399) (currently implemented in tool)
  * [x] uninstall (https://github.com/flutter/flutter/issues/82399, https://github.com/flutter/engine/pull/26122, https://github.com/flutter/flutter/pull/82481)
* [x] Land `uwptool` recipe change ([flutter/recipes#13320](https://flutter-review.googlesource.com/c/recipes/+/13320))
* [x] Land flutter tooling around `uwptool` (~https://github.com/flutter/flutter/issues/70211~, https://github.com/flutter/flutter/pull/82373)
* [x] Land build template (https://github.com/clarkezone/runner-uwp/pull/2)
* [x] Inject template name, filename etc into appxmanifest, parse manifest for name and use that for launching @jonahwilliams
* [ ] Flutter doctor support to detect absence of UWP, UWP c++ install 

### API
* [x] Land ViewController API update (https://github.com/flutter/engine/pull/25879)

### Notable bugs
* [ ] Pressing control key causes app to throw native exception (https://github.com/flutter/flutter/issues/82440)
* [x] After first run, appx package not correctly reinstalled leading to stale content (workaround: uninstall before flutter run)

### Ecosystem
* [x] Fix `url_launcher` infra issue: (https://github.com/flutter/flutter/issues/81297) @stuartmorgan (windows plugin builds currently disabled)
* [ ] Land `url_launcher` (https://github.com/flutter/flutter/issues/70207, https://github.com/flutter/plugins/pull/3828) @stuartmorgan Requires template for `flutter create . ` on bot
* [ ] Land `path_provider` blocked on (https://github.com/timsneath/win32/issues/228) @timsneath 

### Developer tools
* [X] ~~VS code debugging issue [requires E2E tooling to file]~~ (not reproducing; perhaps not an issue, or not uwp-specific)

**Comment by devoncarew** [comment]
Do you have a bit more details on the `VS code debugging issue` item?

**Comment by cbracken** [comment]
Closing since we've released the alpha and the remaining work is tracked by separate issues.
