### ISSUE TITLE
[Proposal] Add Missing Cupertino Icons

### ISSUE THREAD

**Issue by berlonce** [flutter/flutter#82634]
car and car_fill look a bit wonky

This issue is a consolidated proposal to add missing Cupertino icons and fix incorrect icons

### Incorrect icons

- [ ] `car`icon is incorrect https://github.com/flutter/flutter/issues/82634
- [ ] `gear` displays the same icon as `gear_icon` https://github.com/flutter/flutter/issues/80868
- [ ] `settings_solid` displays the same icon as `settings` https://github.com/flutter/flutter/issues/88885
- [ ] `square_pencil` and `square_pencil_fill` are the same #68436
- [ ] `create` icon is incorrect https://github.com/flutter/flutter/issues/116594

### Proposal 

- [ ] Add AirPlay icons https://github.com/flutter/flutter/issues/91786
- [ ] Add missing clipboard icons https://github.com/flutter/flutter/issues/116565
- [ ] Add Face ID icon to CupertinoIcons https://github.com/flutter/flutter/issues/167394

**Comment by darshankawar** [comment]
On latest master:

<img width="100" alt="Screenshot 2021-05-17 at 4 32 37 PM" src="https://user-images.githubusercontent.com/67046386/118478461-894f0280-b72d-11eb-82a5-cb5c117192d0.png">

Also, same behavior using cupertino icons gallery:

<img width="565" alt="Screenshot 2021-05-17 at 4 33 25 PM" src="https://user-images.githubusercontent.com/67046386/118478601-b69bb080-b72d-11eb-97ef-54e57e6cbf48.png">

https://flutter.github.io/cupertino_icons/

**Comment by guidezpl** [comment]
@xster I think you know more about this than me

**Comment by kyle-seongwoo-jun** [comment]
any updates?

**Comment by maheshmnj** [comment]
cc @xster

**Comment by MitchellGoodwin** [comment]
Icons are generated based on this fork of framework7: https://github.com/xster/framework7-icons. Adding new icons and adjusting them are going to likely come from updating that. This is on my radar to update, and I'm likely going to take ownership of this, so harass me for updates, but it may take me a while to get to this as a focus.

**Comment by nxcco** [comment]
Is there any update on this?

**Comment by Decron** [comment]
What is the status on these updates, is anyone still actively trying to fix this? It's been 3 years and pencil_square is still incorrect.

**Comment by Hilbert2048** [comment]
> What is the status on these updates, is anyone still actively trying to fix this? It's been 3 years and pencil_square is still incorrect.

try cupertino_icons: ^1.0.8

**Comment by ziqq** [comment]
Would be nice add CupertinoIcons.mail_slash icon. I really miss this icon.

Use case

```dart
Icon(CupertinoIcons.mail_slash)
```

**Comment by thilojaeggi** [comment]
Why is every new Proposal being closed, and redirected to this issue? The AirPlay Icons have still not been added to CupertinoIcons and it has been requested as far back as 2021.

**Comment by MitchellGoodwin** [comment]
> Why is every new Proposal being closed, and redirected to this issue?

It's much easier for a lot of smaller issues to get lost in the pile, as compared to one umbrella issue that can be upvoted by everyone requesting it. Currently work is being done to refactor Cupertino icons to be easier to build on top of, so these likely won't be addressed until that is done, but then hopefully it will be much easier to update the icons in the future.

**Comment by maheshj01** [comment]
Everyone who lands here, this is a consolidated issue thread to keep track of missing/incorrect cupertino icons. If you file a new issue requesting a missing/incorrect icon we will update this thread's issue description to track yoru request.

**Comment by just-doit** [comment]
Add me to the list. I'm missing some important (at least for me 😉) icons.

**Comment by bugrevealingbme** [comment]
face id needed
