### ISSUE TITLE
☂️ Support UWP plugins in flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#82822]
In order to land UWP support in flutter/plugins, the remaining work is:
- [ ] [flutter driver support](https://github.com/flutter/flutter/issues/82821)
- [ ] [flutter/plugins tooling support](https://github.com/flutter/flutter/issues/82817)
- [x] [flutter/plugins CI infra](https://github.com/flutter/flutter/issues/82729)

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
