### ISSUE TITLE
Migrate everything in flutter/flutter to null-safety

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#84014]
## Packages needing migration:

- [x] ./dev/devicelab/pubspec.yaml
  - [x] ./dev/devicelab/lib - #86325
  - [x] tasks: analyzer_benchmark.dart - flavors_test_win.dart #86374
  - [x] tasks: flutter_attach_test_fuchsia.dart - integration_ui_textfield.dart #86378
  - [x] tasks: ios_app_with_extensions_test.dart - windows_chrome_dev_mode.dart #85998
  - [x] ./dev/devicelab/bin/* & ./dev/devicelab/tests - #85999
- [x] ./dev/bots/pubspec.yaml (requires **dev/devicelab** to be migrated), https://github.com/flutter/flutter/pull/86522
- [x] ./packages/integration_test/integration_test_macos/pubspec.yaml
- [x] ./packages/flutter_tools/test/data/asset_test/font/pubspec.yaml
- [x] ./packages/flutter_tools/test/data/asset_test/main/pubspec.yaml
- [x] ./packages/flutter_test/test/test_config/project_root/pubspec.yaml
- [x] ./dev/tools/vitool/pubspec.yaml
- [x] ./dev/docs/platform_integration/pubspec.yaml
- [ ] ./dev/integration_tests/android_semantics_testing/pubspec.yaml -  Not completed, but now being tracked in its own bug #90633.
- [x] ./dev/integration_tests/hybrid_android_views/pubspec.yaml - https://github.com/flutter/flutter/pull/84140
- [x] ./dev/integration_tests/channels/pubspec.yaml - https://github.com/flutter/flutter/pull/84145
- [x] ./dev/benchmarks/complex_layout/pubspec.yaml - https://github.com/flutter/flutter/pull/83894
- [x] ./dev/benchmarks/macrobenchmarks/pubspec.yaml - https://github.com/flutter/flutter/pull/85501
- [x] ./dev/benchmarks/platform_channels_benchmarks/pubspec.yaml - https://github.com/flutter/flutter/pull/84066

## Files needing migration (excluding files in `flutter_tools`):
- [x] ./dev/conductor/... #86117
  - ./dev/conductor/test/start_test.dart
  - ./dev/conductor/test/clean_test.dart
  - ./dev/conductor/test/roll_dev_test.dart
  - ./dev/conductor/bin/conductor.dart
  - ./dev/conductor/lib/clean.dart
  - ./dev/conductor/lib/proto/conductor_state.pbjson.dart
  - ./dev/conductor/lib/proto/conductor_state.pb.dart
  - ./dev/conductor/lib/proto/conductor_state.pbenum.dart
  - ./dev/conductor/lib/proto/conductor_state.pbserver.dart
  - ./dev/conductor/lib/status.dart
  - ./dev/conductor/lib/start.dart
  - ./dev/conductor/lib/state.dart
- [x] ./dev/tools/mega_gallery.dart - https://github.com/flutter/flutter/pull/84061
- [x] ./dev/tools/update_icons.dart - https://github.com/flutter/flutter/pull/84063
- [x] ./dev/tools/localization/... - https://github.com/flutter/flutter/pull/84064
  - ./dev/tools/localization/gen_material_localizations.dart
  - ./dev/tools/localization/bin/gen_localizations.dart
  - ./dev/tools/localization/bin/gen_date_localizations.dart
  - ./dev/tools/localization/bin/gen_missing_localizations.dart
  - ./dev/tools/localization/bin/encode_kn_arb_files.dart
  - ./dev/tools/localization/localizations_utils.dart
  - ./dev/tools/localization/localizations_validator.dart
  - ./dev/tools/localization/gen_cupertino_localizations.dart
- [x] ./dev/tools/dartdoc.dart (requires **dev/tools/dartdoc_checker.dart** to be migrated) - https://github.com/flutter/flutter/pull/84153
- [x] ./dev/tools/dartdoc_checker.dart - https://github.com/flutter/flutter/pull/84062, https://github.com/flutter/flutter/pull/84153
- [x] ~~./dev/integration_tests/web/lib/null_assert_main.dart - https://github.com/flutter/flutter/pull/84060~~ needs to remain unsafe
- [x] ./dev/integration_tests/flutter_gallery/test_driver/... - https://github.com/flutter/flutter/pull/84065
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_test.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/scroll_perf_test.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_hybrid_test.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_e2e.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/scroll_perf_web.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_e2e_test.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_e2e_with_semantics.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/transitions_perf_with_semantics_test.dart
  - ./dev/integration_tests/flutter_gallery/test_driver/scroll_perf_web_test.dart

## Ban non null safe code
Once everything is migrated we should consider making it illegal to add more non-null-safe code (see also: https://github.com/dart-lang/linter/issues/2702).

**Comment by jmagman** [comment]
> /cc @jmagman I saw you started the devicelab work in #84017

I wasn't planning on migrating it all personally, but to do enough for us to incrementally migrate it library by library.

**Comment by Abhishek01039** [comment]
Hello @jmagman 
Can you please review these PRs?
Thanks

**Comment by jmagman** [comment]
> Hello @jmagman
> Can you please review these PRs?
> Thanks

I'm not always the right person to review these, and I don't have to time to personally review all the null safety migration reviews (I've already done a lot!) https://github.com/flutter/flutter/pulls?q=is%3Apr+is%3Amerged+author%3AAbhishek01039+commenter%3Ajmagman
Someone will get to your PRs as part of various weekly triage meetings, depending on what packages you're migrating.  Thanks for your contributions!

**Comment by goderbauer** [comment]
To migrate the files in `dev/conductor` to null safety, we need to upgrade `package:protobuf` to version 2.0.0, which is the first null safe version. To be able to upgrade to that version, we also need to upgrade package:dwds to a version that contains this change: https://github.com/dart-lang/webdev/pull/1325 since dwds' build_collection dependency is preventing us from using a new build_value and fixnum version, the latter of which is required by the new protobuf version.

**Comment by goderbauer** [comment]
The other thing that's left to migrate are files in `flutter_tools`.

@jonahwilliams are there still blockers to migrate the tools? Or do we just need to "do it"?

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/issues/71511

There are several unmigrated dependencies such as dwds and dds

**Comment by darrenaustin** [comment]
As there are only two remaining issues that are being tracked in other bugs (#90633, and #71511), I am going to declare this done and close this out.

Thanks so much for everyone's hard work on this.
