### ISSUE TITLE
Tracking bug for adding ARM64 simulator artifacts to the Flutter.xcframework

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#84673]
We'd like to add ARM64 simulator to the supported architectures in the Flutter Engine's xcframework artifact.

### Blockers
- [x] https://github.com/flutter/flutter/issues/84670 Add support for ARM64 simulator builds
- [x] https://github.com/flutter/flutter/issues/84601 Update iOS and macOS engine builders to Xcode 12.0
- [x] https://github.com/flutter/flutter/issues/84672 Update Flutter Engine recipes to handle ARM64 simulator

**Comment by gw280** [comment]
cc @jmagman

**Comment by gw280** [comment]
I believe the timeout issue is no longer a problem; that being said, LUCI try runs are timing out because it takes 22 minutes to install a different version of Xcode :(

**Comment by chinmaygarde** [comment]
This should also be related to https://github.com/flutter/flutter/issues/60118

**Comment by gw280** [comment]
This should now be done. I'll close it when we've validated it.

**Comment by jmagman** [comment]
Tool change https://github.com/flutter/flutter/pull/85642 has merged.
