### ISSUE TITLE
[webview_flutter] Migrate plugin to federated architecture

### ISSUE THREAD

**Issue by mvanbeusekom** [flutter/flutter#86286]
## Use case

Migrate the "webview_flutter" package to the [federated plugin architecture](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins). This would result in the following benefits:

1. Makes it easier to add support for additional platforms (specifically desktop support e.g. Windows, macOS and Linux);
2. Allows for easier separation of concerns especially when different platforms require different configuration settings; 
3. The federated architecture also makes it easier to write automated tests and guard the API;
4. Confirms to the architecture of most other Flutter plugins, making it easier for developers to understand the project layout and contribute to the project.

## Proposal

To migrate the in_app_purchase package to federated architecture we should take the following steps:

- [x] Move the `webview_flutter` into its own subdirectory ("webview_flutter/webview_flutter") flutter/plugins#4152;
- [x] Create the `webview_flutter_platform_interface` package (see PR flutter/plugins#4302);
  - [x] Copy the `LICENSE` file from the `webview_flutter` package;
  - [x] Add a `CHANGELOG.md` file;
  - [x] Define a `pubspec.yaml` file;
  - [x] Create a `README.md` file;
  - [x] Define the platform interface in `webview_flutter_platform.dart`;
  - [x] Implement the default implementation in `method_channel_webview_flutter.dart`;
- [x] Create an Android implementation of the `webview_flutter_platform_interface` in a separate `webview_flutter_android` package (see PR flutter/plugins#4343);
- [x] Create an iOS implementation of the `webview_flutter_platform_interface` in a separate `webview_flutter_darwin` package (see PR flutter/plugins#4345);
- [x] Refactor package `webview_flutter` to use the `webview_flutter_android` and `webview_flutter_darwin` packages.
  - [x] Make sure to remove exclusion of `webview_flutter_android` and `webview_flutter_wkwebview` from [exclude_all_plugins_app.yaml](https://github.com/flutter/plugins/blob/bb3ebb2b79eb856f641398b7776c52539acfce04/script/configs/exclude_all_plugins_app.yaml) configuration file.

**Comment by stuartmorgan** [comment]
One wrinkle is that it already uses the federated structure at a code level, just not a package level, so it already has a platform interface that is part of the public API. We'll either need to re-export the platform interface from a stub file in the app-facing package, or move it as a breaking change.

For ease of migration for any existing out-of-repo implementations, I think the latter is the better option. We can remove it at some later point.

**Comment by mvanbeusekom** [comment]
Re-exposing seems a good intermediate and easy to solve solution to me. We could even mark the stub deprecated and point developers to the new platform interface. Should be very small change for developers if we leave the class name and method signatures the same. Developers simply need to add a new dependency and update the import statement.
