### ISSUE TITLE
Devicelab task tests not running anywhere

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#86802]
These `dev/devicelab/bin/tasks` are not present in [.ci.yaml](https://github.com/flutter/flutter/blob/e084e9d9466d598cb541c51740a30384c8a90c2f/.ci.yaml). Are they running anywhere?

### Missed during CI config migrations, needs builder
- [x] [animation_with_microtasks_perf_ios__timeline_summary](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/animation_with_microtasks_perf_ios__timeline_summary.dart) - introduced in #79163
- [x] [fullscreen_textfield_perf](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/fullscreen_textfield_perf.dart) - introduced in #73374
- [x] [fullscreen_textfield_perf__e2e_summary](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/fullscreen_textfield_perf__e2e_summary.dart) - introduced in #73374
- [x] [plugin_test_ios](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/plugin_test_ios.dart) (https://github.com/flutter/flutter/issues/86801) - introduced in #14560

### Should be turned on, needs builder
- [x] [android_engine_dependency_proxy_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/android_engine_dependency_proxy_test.dart) - introduced in #56164, never turned on?
- [x] [devtools_profile_start_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/devtools_profile_start_test.dart) - introduced in #83913, never turned on?
- [x] [gradle_java8_compile_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_java8_compile_test.dart) - introduced in https://github.com/flutter/flutter/pull/80600, never turned on? https://github.com/flutter/flutter/pull/86904
- [x] [plugin_dependencies_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/plugin_dependencies_test.dart) - mistakenly removed in #68110, should be run on Linux, macOS, and Windows. Host only. https://github.com/flutter/flutter/pull/86904

### Purposely turned off, should be removed
- [x] [build_aar_plugin_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_aar_plugin_test.dart) - turned off in #36966, https://github.com/flutter/flutter/pull/86911
- [x] [build_mode_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_mode_test.dart) - https://github.com/flutter/flutter/pull/86808
- [x] [flutter_gallery_instrumentation_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_gallery_instrumentation_test.dart) - https://github.com/flutter/flutter/pull/86812
- [x] [flutter_run_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_run_test.dart) - introduced in #24930, turned in #25416, https://github.com/flutter/flutter/pull/86828
- [x] [gradle_migrate_settings_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_migrate_settings_test.dart) - turned off in #36966, https://github.com/flutter/flutter/pull/86911
- [x] [textfield_perf](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/textfield_perf.dart) - reimplemented as `textfield_perf__timeline_summary`, https://github.com/flutter/flutter/pull/86827
- [x] [web_incremental_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/web_incremental_test.dart) - turned off in #44746, https://github.com/flutter/flutter/pull/86829

### Obsolete, should be removed
- [x] [codegen_integration_*](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/codegen_integration_linux.dart) - feature removed in #58328, https://github.com/flutter/flutter/pull/86962
- [x] [plugin_test_win](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/plugin_test_win.dart) - can be deleted, covered by `Windows plugin_test`, https://github.com/flutter/flutter/pull/86826
- [x] [tiles_scroll_perf_iphonexs__timeline_summary](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/tiles_scroll_perf_iphonexs__timeline_summary.dart) - https://github.com/flutter/flutter/pull/86822

### Should stay off
- [x] [gradle_non_android_plugin_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart) - removal tracked with https://github.com/flutter/flutter/issues/85347
- [x] [hot_mode_dev_cycle_linux_target__benchmark](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/hot_mode_dev_cycle_linux_target__benchmark.dart) - introduced in https://github.com/flutter/flutter/pull/73889, to be turned on with https://github.com/flutter/flutter/issues/54295
- [x] [hot_mode_dev_cycle_win_target__benchmark](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/hot_mode_dev_cycle_win_target__benchmark.dart) - introduced in https://github.com/flutter/flutter/pull/73889, to be turned on with https://github.com/flutter/flutter/issues/54295

### Unknown
- [ ] [flutter_attach_test_fuchsia](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_attach_test_fuchsia.dart) - introduced in #48472

Add [test owners](https://github.com/flutter/flutter/blob/master/TESTOWNERS) for any tests that are turned on.

**Comment by zanderso** [comment]
@iskakaushik FYI on https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/animation_with_microtasks_perf_ios__timeline_summary.dart

**Comment by keyonghan** [comment]
> ### Should be turned on, needs builder
> - [ ] [android_engine_dependency_proxy_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/android_engine_dependency_proxy_test.dart) - introduced in #56164, never turned on?

Is this for Linux, Mac, or Windows? I assume this needs an android phone? @xster 

> - [ ] [devtools_profile_start_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/devtools_profile_start_test.dart) - introduced in #83913, never turned on?

Is this for Linux, Mac, or Windows? Is this a host only test? @jonahwilliams 

> - [ ] [gradle_java8_compile_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_java8_compile_test.dart) - introduced in https://github.com/flutter/flutter/pull/80600, never turned on?

Is this for Linux, Mac, or Windows? Is this a host only test? @blasten

**Comment by blasten** [comment]
> Is this for Linux, Mac, or Windows? Is this a host only test? @blasten

Host only - Linux. Thanks!

**Comment by jmagman** [comment]
> > * [ ]  [android_engine_dependency_proxy_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/android_engine_dependency_proxy_test.dart) - introduced in [let the embedding maven engine dependency reference the storage proxy #56164](https://github.com/flutter/flutter/pull/56164), never turned on?
> 
> Is this for Linux, Mac, or Windows? I assume this needs an android phone? @xster

@blasten can you also advise for this one?  I'm guessing just Linux, and it looks host only?  Optionally it could be re-written as a `flutter_tool` integration test instead of using the devicelab.

**Comment by jmagman** [comment]
> * [ ]  [build_aar_plugin_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_aar_plugin_test.dart) - turned off in [Roll back the AAR build experiment #36966](https://github.com/flutter/flutter/pull/36966)
> * [ ]  [gradle_migrate_settings_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_migrate_settings_test.dart) - turned off in [Roll back the AAR build experiment #36966](https://github.com/flutter/flutter/pull/36966)

@blasten Do you have more context for these two?  From https://github.com/flutter/flutter/pull/36966 I can't tell if they were only temporarily turned off to fix a transient plugins repo problem, or maybe were waiting for something to roll into master?  Should these be fixed up and reenabled, or should they be deleted?

**Comment by blasten** [comment]
@jmagman actually, those tests can be removed, no needed/no value added.

**Comment by blasten** [comment]
I can send a PR to remove them in a bit

**Comment by jonahwilliams** [comment]
codegen_integration_x can be removed, the feature has been deleted

**Comment by jmagman** [comment]
> > * [ ]  [devtools_profile_start_test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/devtools_profile_start_test.dart) - introduced in [[flutter] ensure vmservice binding is registered in profile mode #83913](https://github.com/flutter/flutter/pull/83913), never turned on?
> 
> Is this for Linux, Mac, or Windows? Is this a host only test? @jonahwilliams

@keyonghan Just Linux, needs a real device.

**Comment by iskakaushik** [comment]
`animation_with_microtasks_perf_ios__timeline_summary` has been added to post-submits in https://github.com/flutter/flutter/issues/87345.

**Comment by jmagman** [comment]
> `animation_with_microtasks_perf_ios__timeline_summary` has been added to post-submits in #87345.

Awesome, will check it off once `bringup` is removed.

**Comment by jmagman** [comment]
Almost there!

- fullscreen_textfield_perf - Linux/android, benchmark so not host only (test owner `@zanderso @flutter/engine`)
- fullscreen_textfield_perf__e2e_summary - Linux/android, benchmark so not host only (test owner `@zanderso @flutter/engine`)
- plugin_test_ios - Mac/ios, hostonly (test owner `@stuartmorgan @flutter/plugin`)

@keyonghan can you add the builders for these too?

@blasten for `android_engine_dependency_proxy_test` I'm guessing just Linux, and it looks host only? Who should be the test owner?

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/17180 to add 

> Almost there!
> 
> * fullscreen_textfield_perf - Linux/android, benchmark so not host only (test owner `@zanderso @flutter/engine`)
> * fullscreen_textfield_perf__e2e_summary - Linux/android, benchmark so not host only (test owner `@zanderso @flutter/engine`)
> * plugin_test_ios - Mac/ios, hostonly (test owner `@stuartmorgan @flutter/plugin`)
> 
> @keyonghan can you add the builders for these too?

https://flutter-review.googlesource.com/c/infra/+/17180 to add them to staging. Will enable in prod once validated not flaky.

**Comment by godofredoc** [comment]
@jmagman @keyonghan can we close this bug?

**Comment by jmagman** [comment]
android_engine_dependency_proxy_test and flutter_attach_test_fuchsia still aren't running anywhere.

It looks like android_engine_dependency_proxy_test needs a builder and needs to be turned on.

@zanderso can we delete flutter_attach_test_fuchsia?

**Comment by zanderso** [comment]
If `fuchsia_attach_test` hasn't been running for over a year, and no one has noticed, then it should probably be deleted.

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/recipes/+/36380 for removing the modules and recipes that haven't been used for over a year.
