### ISSUE TITLE
☂️ - Improved raster cache heuristics for complex pictures

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#87833]
Currently flutter uses a raster cache of Pictures to speed up rendering when the same pictures are rendered frame after frame. Consider, a ScrollView of ListTiles, as you scroll each will be rendered, then raster cached, then evicted once they move off screen.

Currently the raster cache heuristics are tuned such that they work reasonably well with the Material and Cupertino libraries. These same heuristics lead to less than optimal behavior on extremely complex pictures such as SVGs, which can contain 100s or 1000s of drawing commands. These pictures may benefit from different cache heuristics and raster cache behavior, to be described in the issue list below:

## Behavior

- [ ] [Raster cache entires are eagerly evicted if they move offscreen](https://github.com/flutter/flutter/issues/87827)
- [ ] [Raster cache entries are only cached if they survive for 1+ frames](https://github.com/flutter/flutter/issues/87827)
- [ ] [Raster cache has a first-come first-served limit on cache entries per frame](https://github.com/flutter/flutter/issues/87834)

## Documentation

- [ ] [Raster cache behavior is under-documented](https://github.com/flutter/flutter/issues/87835)

## Tooling

- [ ] [We lack tooling or documentation on how to use our tooling to determine whether raster cache behavior is appropriate](https://github.com/flutter/flutter/issues/87836)

**Comment by jonahwilliams** [comment]
@flar

**Comment by flar** [comment]
cc @chinmaygarde

**Comment by zanderso** [comment]
@dnfield

**Comment by flar** [comment]
The first two referenced issues point to the same github issue even though their text describes different problems.

**Comment by jonahwilliams** [comment]
Closing as I don't believe the raster cache is worth working on anymore
