### ISSUE TITLE
[Proposal] Add Missing Material icons

### ISSUE THREAD

**Issue by SonXuanNguyen2k** [flutter/flutter#88852]
## UseCase: 

This issue is a consolidated proposal to add missing material icons 

## Proposal

Please add the missing Material icons

- [ ] Icons.free_cancellations https://github.com/flutter/flutter/issues/88852
- [ ] Icons.wechat icon https://github.com/flutter/flutter/issues/89619
- [ ] Icons.route_outlined https://github.com/flutter/flutter/issues/89684
- [ ] Icons.medication_liquid https://github.com/flutter/flutter/issues/91577
- [ ] Icons.edit_calendar https://github.com/flutter/flutter/issues/88852#issuecomment-954501168
- [ ] Icons.arrow_circle_left_outlined https://github.com/flutter/flutter/issues/93383
- [ ] Icons.heart_broken https://github.com/flutter/flutter/issues/93920
## Icons

<details>
<summary>images</summary>

### Icons.free_cancellations

<img src="https://user-images.githubusercontent.com/31410839/132657745-089d8f57-8291-4e93-bd40-db424d53998e.png" width ="200">

### Icons.wechat

<img src="https://user-images.githubusercontent.com/31410839/132658779-c560f08c-4cc8-4d36-8f05-d03cb036fc30.png" width ="200">

### Icons.route_outlined

<img src="https://user-images.githubusercontent.com/31410839/132658251-4b437fa0-a97d-4bee-a976-0cdc5e975226.png" width ="200">

### Icons.medication_liquid

<img src="https://user-images.githubusercontent.com/31410839/139405109-59ab1d1f-0cc9-4901-a63d-b18316344a08.png" width ="200">

### Icons.edit_calendar

<img src="https://user-images.githubusercontent.com/31410839/139397671-85606e51-f780-4787-a553-1fe870c48d2c.png" width ="200">

</details>

**Comment by maheshmnj** [comment]
I have updated this issue to track missing material icons and referenced the other similar issues, This will help to keep track of all the missing icons issues in one place.

cc @guidezpl
