### ISSUE TITLE
☂️ Material Theme System Updates

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#91772]
This issue mirrors the design of https://flutter.dev/go/material-theme-system-updates

## Rename the TextTheme TextStyles
- [x] #48547
- [x] https://github.com/flutter/flutter/issues/98746

## Deprecate/remove the accent properties
- [x] https://github.com/flutter/flutter/issues/56918

## Compute `brightness`, `primaryColorBrightness`, `accentColorBrightness`
- [x] Deprecate `accentColorBrightness` #81336
- [x] Change `ThemeData.brightness` to be a simple getter that returns `colorScheme.brightness` #56956
- [x] Update `SearchDelegate` #55209
- [x] Update `GridTileBar` #78574
- [x] Deprecate `primaryColorBrightness` #93396

## Deprecate/move/remove the 21 grab-bag properties
(x) indicates number of references, excluding`theme_data.dart` and tests. This can be used a proxy for disruptiveness/ease of deprecation.

- [ ] Deprecate `ThemeData.canvasColor` #116350
- [ ] Deprecate `ThemeData.scaffoldBackgroundColor` #116341
- [ ] Deprecate `ThemeData.cardColor` #116349
- [ ] Deprecate `ThemeData.dividerColor` #116347
- [ ] Deprecate `ThemeData.secondaryHeaderColor` #116342
- [ ] Deprecate `ThemeData.hintColor` #116346
- [ ] Deprecate `ThemeData.splashColor` (5) ⇒ `inkColor` or `inkFeatureColor`
- [ ] Deprecate `ThemeData.unselectedWidgetColor` (11) ⇒ see `toggleableActiveColor` deprecation
- [x] Deprecate `ThemeData.bottomAppBarColor` ⇒ #111080
- [x] Deprecate `ThemeData.selectedRowColor` #109070
- [x] Deprecate `ThemeData.buttonColor` #82196
- [x] Deprecate `ThemeData.textSelectionColor` #66482
- [x] Deprecate `ThemeData.cursorColor` #66482
- [x] Deprecate `ThemeData.textSelectionHandleColor` #66482
- [x] Deprecate `ThemeData.backgroundColor` #110162
- [x] Deprecate `ThemeData.dialogBackgroundColor` #155072
- [x] Deprecate `ThemeData.indicatorColor` #160024
- [x] Deprecate `ThemeData.errorColor` #110162
- [x] Deprecate `ThemeData.toggleableActiveColor` #97972

### Additional grab-bag properties
These grab-bag properties not in the original linked proposal, but can also be deprecated:

- [ ] Deprecate `ThemeData.shadowColor` #116343
- [ ] Deprecate `ThemeData.splashFactory` (4) ⇒ `inkFactory` or `inkFeatureFactory`
- [ ] Deprecate `primaryColor` #110848
- [ ] Deprecate `primaryColorDark` #116362
- [ ] Deprecate `primaryColorLight` #116362
- [x] Deprecate `ThemeData.fixTextFieldOutlineLabel` #87281

These factory constructor parameters can also be deprecated:
- [ ] Deprecate `primarySwatch` from `ThemeData` factory constructor (8) ⇒ `colorScheme` or `colorSchemeSeedColor` (related https://github.com/flutter/flutter/issues/120064)

### Property colors not subject to removal
- State colors like `ThemeData.disabledColor` (26), `ThemeData.focusColor` (19), and `ThemeData.hoverColor` (19) have high usage and are shared amongst many components
- There is similar widespread usage for `ThemeData.highlightColor` (13)
- Other parameters can remain in the factory constructor (e.g. `ThemeData.fontFamily` and `ThemeData.fontFamilyFallback`) for convenience

## Component Theme Normalization

All of the existing themes have been normalized except for the following:

- [x] `AppBarTheme` #169130
- [x] `BottomAppBarTheme` #168586
- [x] `InputDecorationTheme` #168981
- [x] `CardTheme` #151914
- [x] `ChipTheme` #94179
- [x] `DialogTheme`#153982
- [x] `ListTileTheme` #91840
- [x] `SnackBarTheme` #180001
- [x] `TabBarTheme` #155476

**Comment by rydmike** [comment]
Nice summary @guidezpl and great to see this collection issue for moving this topic forward and tracking its progress. It will certainly make things clearer when completed. The current situation seems to be a source of a lot of confusion for many Flutter developers, quite a few related issues open and more arriving ever so often. This will help, eventually.

Most of the colors properties already have proper homes in the `ColorScheme` and/or appropriate sub-themes, where you can override widget default inherited colors, that properly designed SDK Material UI widgets now get from `ThemeData.colorScheme`. 

For those colors everything looks fine, but not all color properties in `ThemeData` are so lucky and at that stage. Below I highlight one important case: `scaffoldBackgroundColor`, there might be others too.


## Things to Consider during the Theme System Update and Migration

In case it is not obvious, but as far as I know e.g. `ThemeData.scaffoldBackgroundColor` currently does not have a home anywhere else. If you do not want it to be same color as `ThemeData.colorScheme.background`, which presumably would be its new default, `ThemeData.from()` already assigns this color to it. Then there is no other way to currently theme it. 

The only way to set it separately, is to define the `ThemeData.scaffoldBackgroundColor`, so it needs a new home somewhere. 

Being able define slightly different background colors for depending on type of surface/background is important. It makes it possible in current version of Flutter to create applications that uses background colors with slightly different nuances, typically with different alpha blend strengths of primary color in the different surface/background colors used by Widgets, depending on their type and current default themed color behavior.

For example, currently with the factory `ThemeData.from`, that is the most up to date one of the color factories for using proper `ColorScheme` based themes, we for example have:

- `colorScheme.surface`, that is assigned to `cardColor`, used by `Card` and `Material` of type card. Expecting these widgets to use `colorScheme.surface` directly after migration. This is fine and will not hard break anything, change can imo be done easily, everything looks ready for it.
- `colorScheme.background`, that is assigned to `canvasColor`, used by `Material` of type canvas, and via that many widgets. Expecting Material of type canvas to use `colorScheme.background` directly after migration. This is fine and will not hard break anything, change can imo be done easily, everything looks ready for it.
- `dialogBackgroundColor` that gets assigned `colorScheme.background`, already has its own sub-theme, so we can easily theme it to whatever we like (we already use that route in anticipation of `dialogBackgroundColor` deprecation. This prop can imo be deprecated easily already now, migration path is clear/ready.
- `scaffoldBackgroundColor`, is also assigned `colorScheme.background`, but has no other source that can be used to theme it, other than the current `ThemeData`. **It will need it's own new sub-theme**, otherwise `scaffoldBackgroundColor` cannot be deprecated without reduction in currently used theming capabilities and flexibility. It would **break things very badly in our app**s if it cannot be themed to another color than `ThemeData.colorScheme.background` going forward.

This might apply to a few other `ThemeData` color properties on the deprecation list as well.


> PS. Yes, I'm aware Material3 brings new containers used for color and onColor, so it will have less/none of these current messy issue that many Flutter devs struggle with when it comes to theme colors for Flutter apps. Although I suspect many will think that M3 color design might be a bit complex. I think it seems pretty straight forward and makes a lot of sense. Looking forward to see how it gets implemented in Flutter. Might be a bit tricky with backward compatibility issues and potential challenges merging it with current widgets. Plus it will increase widget branching for color logic and calculation, potentially decreasing performance of current widgets. Hopefully not, will be interesting to see what the chosen approach is. Just new M3 widgets that uses new Theme designs and concepts, might be simplest, but not ideal either.

**Comment by talamaska** [comment]
@rydmike From what I see, the scaffoldBackgroundColor is moved in a ScaffoldThemeData. Maybe that's a change after your recommendations. Anyways, thanks for keeping track of the ThemeData changes for all of us.

**Comment by rydmike** [comment]
@talamaska Thanks, I noticed the addition as well. Perhaps it was a part of the plan all along. Probably so, since if it were not, it would result in new ThemeData that has no migration path for certain use cases.

**Comment by RalphBergmannKMB** [comment]
Currently, I am developing an app that should look Android'ish on Android and iOS'ish on Android. So I use the MaterialApp for Android and the CupertinoApp for iOS. And I also try to get a Material- and CupertinoTheme together, both with dark and light colors. It isn't easy :( 

I saw that CupertinoApp has only one theme parameter, and you use the [CupertinoDynamicColor](https://api.flutter.dev/flutter/cupertino/CupertinoDynamicColor-class.html) to define the light and dark colors (and some more).

Now I wonder why we don't have the same for the MaterialApp? Would it be a good idea to remove all these darkTheme, highContrastTheme, and highContrastDarkTheme from the MaterialApp and use a MaterialDynamicColor?

**Comment by rydmike** [comment]
## Additional colors to add to above list?

Should perhaps the following colors also be mentioned above among the `ThemeData` colors that should be deprecated/moved/removed?

- primaryColorLight
- primaryColorDark

### primaryColorLight

A lighter color of primary. It is only used by `CircleAvatar`.
A potential replacement color is `ColorScheme.primaryContainer`.

### primaryColorDark

A darker color of primary, it is used by `CircleAvatar`.
A potential replacement color is `ColorScheme.onPrimaryContainer`.

### Challenges
The replacements would not be an exact match, so it would be breaking, but it matches the current design intent, if `primaryContainer` and `onPrimaryContainer` are using color tones as intended by M3 color design.

### Status of primaryColorLight and pimaryColorDark

I wrote quite a bit about some past `ThemeData` color challenges here https://github.com/flutter/flutter/issues/65782. I was about to close the old issue, since most of the topics mentioned in it have been or are being addressed by the in progress `ThemeData` migration being tracked in this issue.

I did however not see anything addressing or mentioning `primaryColorLight` and `primaryColorDark` in `ThemeData`. Which does not mean it does not already exist, I might just have missed it.

The presence of `primaryColorLight` and `primaryColorDark` in `ThemeData` if kept, will continue to cause potential confusion. 

Currently if you create a theme with `ThemeData.from` or just `ThemeData` and you give it a `ColorScheme` in `colorScheme` and don't provide a `primarySwatch` that would match in tones what you used for your primary in the `ColorScheme`, or directly give the color properties `primaryColorLight` and `primaryColorDark` values that fit your `ColorScheme`'s primary color. Well, then you end up with `primaryColorLight` and `primaryColorDark`  having default color values (blue hues, or grey in dark mode) that have nothing to do with whatever color you used in your `ColorScheme` as primary color, unless it happened to be a shade of blue close to the M2 blue swatch. Plus in the deprecate/move/remove list above, there is also this:

> Deprecate `primarySwatch` from `ThemeData` factory constructor (8)

Further complicating the continued exitance of `primaryColorLight` and `primaryColorDark`. in `ThemeData`

----

cc:  @Piinks, @HansMuller & @darrenaustin

**Comment by guidezpl** [comment]
Linking in this excellent comment by @rydmike https://github.com/flutter/flutter/issues/19089#issuecomment-1106644732 so it isn't lost.

**Comment by rydmike** [comment]
Regarding planned deprecation of `ThemeData.indicatorColor`, it would be nice to have it added to the `TabBarTheme` as a convenience property, like to today in `ThemeData`. It is really handy when you only want to change the default indicator's color.

Today the `TabBarTheme` itself only contains the `Decoration` `indicator`, you can set the color of it via it, if you recreate the entire default `Decoration` and use another color for it there, it is however a bit verbose for just changing the color.

The `TabBar` widget offers both `indicatorColor` and `indicatorWeight` as convenience properties to modify the default `Decoration` `indicator`, and if an `indicator` is provided, it is used and the props `indicatorColor` and `indicatorWeight` are ignored. When deprecating `ThemeData.indicatorColor` it would be lovely if those properties could also be moved into the `TabBarTheme` with similar behavior as same widget properties.

cc: @guidezpl

**Comment by HansMuller** [comment]
@rydmike - That sounds sensible to me. In general we'd like widgets and their themes to expose the same properties.

**Comment by guidezpl** [comment]
I updated the issue. We'll soon be over the hump for cleaning up the grab-bag properties! Most of the remaining ones have clear migration paths (indicated by "⇒").

**Comment by rydmike** [comment]
Thanks @guidezpl, that's good news and nice addition with the `primaryX` deprecation and its draft prep https://github.com/flutter/flutter/pull/110848. 

Related to `primaryX`, I found some interesting fringe issues related to `ThemeData.primaryColor` that causes a few surprises when you use `ColorScheme`:s designed for Material 3 using its color system. Nothing that can't be worked around if you know what you are doing with `ThemeData`. Plus eventual deprecation of all of these will fix it. Still until all this is in stable, it might cause some surprises. I will add an issue for it tomorrow and ref to this comment. Could be useful in case someone notices same the issue, and it might be good to know for these deprecations too.

**Comment by guidezpl** [comment]
Thanks @rydmike, did you file that issue? Small note to self: while we'd like to get this done sooner rather than later, each deprecation or group of deprecations has to be done in sequence rather than parallel, due to the nature of the changes and merging conflicts.

**Comment by guidezpl** [comment]
Thanks for the feedback, I don't feel strongly about removing it, so edited the description above.

**Comment by guidezpl** [comment]
Update: I'm currently working on 10 `xColor` deprecations. Currently, I'm cleaning up internal usages, and then I will land the framework changes along with Dart fix'es and deprecations.

**Comment by TahaTesser** [comment]
@guidezpl 
Thank you! @rydmike and I are very excited about this!

**Comment by guidezpl** [comment]
Realized I never posted an update, but I unfortunately was (and remain) too busy with other work to land those ~10 closed PRs linked in the description. But they were all ready (minus conflicts), if someone wants to land them.

**Comment by TahaTesser** [comment]
> Realized I never posted an update, but I unfortunately was (and remain) too busy with other work to land those ~10 closed PRs linked in the description. But they were all ready (minus conflicts), if someone wants to land them.

I can do that. ✋

**Comment by guidezpl** [comment]
Thanks for offering! The only issue is, IIRC, that this batch more-or-less all had uses in the Google codebase that required removal or migration while landing the PR

**Comment by rydmike** [comment]
## Deprecation of `ThemeData.scaffoldBackgroundColor`

I noticed that the mention of adding a `ScaffoldThemeData` with a `background` color and `ThemeData.scaffoldTheme` in relation to the deprecation of `ThemeData.scaffoldBackgroundColor` was removed in this edit:

![Screenshot 2024-10-25 at 18 00 02](https://github.com/user-attachments/assets/ce9a1555-6774-4568-ae54-38556989a4e1)

I would like to point out that not having a migration path for providing a custom color for the themed background color of the `Scaffold`, will severely break pretty much every app, well OK every 2nd app at least.

Deprecating the property is of course already breaking, but what is worse is that just removing it without providing a new themeable property for it, results in that there is no migration path. Since, if you just remove `scaffoldBackgroundColor`, it will be impossible to theme it like you can now. It will just get a default `ColorScheme` mapping (probably `surface`), but that does not help all with all the custom color assignments that exist today to `ThemeData.scaffoldBackgroundColor`.

Properties like e.g. `ThemeData.dialogBackgroundColor` do not have this problem, since the dialog background can still be themed to whatever desired color, in the dialog component theme, so deprecation e.g. `ThemeData.dialogBackgroundColor` is of course breaking for many too, but it has a clear and simple migration path. The `ThemeData.scaffoldBackgroundColor` color needs this too.

## Proposal

Either 

1. Do not deprecate `ThemeData.scaffoldBackgroundColor` 

Or

2. Deprecate it and also add a component theme for it, like originally mentioned.

Option 2 of course opens up opportunities for adding a few more themeable properties to existing `Scaffold` properties. Some of would be helpful to have there, like e.g. `extendBody` and `extendBodyBehindAppBar` to mention a few. Of course, to add them, the `Scaffold` bool properties will need to be made nullable and fallback via prop value to theme value and to defaults, but it would not break any current behavior.

**Comment by huycozy** [comment]
@QuncCccccc Since all remaining items in `Theme Normalization` have been solved, can we close this issue now?

**Comment by guidezpl** [comment]
> [@QuncCccccc[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/quncheng@google.com)](https://github.com/QuncCccccc) Since all remaining items in `Theme Normalization` have been solved, can we close this issue now?

There are still colors to deprecate on `ThemeData` ;)
