### ISSUE TITLE
Move postsubmit build scheduling from LUCI to cocoon

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#92300]
This will allow to remove the current 45 minutes propagation time.

## Migration
- [X] flutter/cocoon
- [X] flutter/packages
- [x] flutter/plugins
- [X] flutter/engine ci.yaml roller
- [X] flutter/engine bringup targets
- [x] flutter/engine - https://github.com/flutter/engine/pull/32018
- [x] flutter/flutter bringup targets: https://github.com/flutter/flutter/pull/107483
- [x] flutter/flutter - host only target: https://github.com/flutter/flutter/pull/107673
- [x] flutter/flutter - linux/android: https://github.com/flutter/flutter/pull/107852
- [x] flutter/flutter - windows/android+ mac/android: https://github.com/flutter/flutter/pull/107737
- [x] flutter/fluter - mac/ios - https://github.com/flutter/flutter/pull/107944
- [x] schedule commit targets in batch requests - https://github.com/flutter/cocoon/pull/1999
- [x] Schedule failed builds with higher priority - https://github.com/flutter/flutter/issues/108183
- [x] Batch schedule samsung & mac host only tasks - https://github.com/flutter/flutter/issues/108317
- [x] deprecate `/api/refresh-chromebot-status` - https://github.com/flutter/cocoon/pull/1998, https://github.com/flutter/cocoon/pull/2006

## Features
- [x] Rerunning Cocoon scheduled builds - https://github.com/flutter/cocoon/pull/1610
- [x] Auto-retries for Cocoon scheduled builds - https://github.com/flutter/cocoon/pull/1657
- [x] Batch on device builds - https://github.com/flutter/flutter/issues/100793

**Comment by CaseyHillers** [comment]
This is blocked on the scheduler supporting postsubmit triggers (tracked in https://github.com/flutter/flutter/issues/81795). Once that is complete, there will be a migration plan to move tests from LUCI to Cocoon.

**Comment by keyonghan** [comment]
Blocker https://github.com/flutter/flutter/issues/107599 before migrating non-bringup targets.

**Comment by keyonghan** [comment]
Now everything is in cocoon.
