### ISSUE TITLE
Host only tests with shards - flakes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97036]
Flake reduction has been mainly focused on devicelab tests, while the shard tests (ones contain many unit/integration tests) are not being tracked actively. This bug tracks different flakes on different shard tests. Data is based Q4 2021 flakes happened from 10/01/2021 to 01/13/2022

**GOAL**: proactively fix/skip all flaky tests to achieve zero flake on these tests

**build_tests**

- [x] Linux build_tests_1_2: [1 flake](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20build_tests_1_2/3229/overview), fixed in https://github.com/flutter/flutter/issues/96550
- [ ] Windows build_tests
  - [ ] Windows build_tests_1_3 & build_tests_2_3: [3 flakes on android_aot_release_android-arm64 failure](https://github.com/flutter/flutter/issues/97160)
  - [ ] Windows build_tests_2_3: 2 flakes on `build apk --release -v`, https://github.com/flutter/flutter/issues/103230

**tool_tests**

- [ ] tool_tests_commands: 1 flake on `packages_test ` TimeoutException, https://github.com/flutter/flutter/issues/97831

**framework_tests**

- [x] Mac framework_tests_libraries: 1 flake on `date_picker_test`, https://github.com/flutter/flutter/issues/97161
- [ ] Linux framework_tests_misc: 1 flake on `cupertino_action_sheet `, https://github.com/flutter/flutter/issues/100641
- [x] Linux framework_tests_libraries: 1 flake on `bottom_navigation_bar_test`, https://github.com/flutter/flutter/issues/97162
- [x] Linux framework_tests_widgets: 2 flakes: [1 dismissible_test flake](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_widgets/2925/overview), [1 aspect_ratio_test](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_widgets/2891/overview), fixed in https://github.com/flutter/flutter/issues/94729
- [ ] Windows framework_tests_widgets: 4 flakes, https://github.com/flutter/flutter/issues/97163
- [x] Windows framework_tests_libraries: 
  - [x] 1 flake on date_picker_test, https://github.com/flutter/flutter/issues/97161
  - [x] 2 flakes on platform_view_test, https://github.com/flutter/flutter/issues/100249
- [ ] Windows framework_tests_misc: 1 flake on `live_widget_controller_test flake`, https://github.com/flutter/flutter/issues/97165

**tool_integration_tests**

- [ ] Windows tool_integration_tests_1_6:
  - [x] 1 flakes on android_plugin_example_app_build_test, https://github.com/flutter/flutter/issues/98085
  - [ ] 3 flakes on android_plugin_ndkversion_mismatch_test, https://github.com/flutter/flutter/issues/105813, https://github.com/flutter/flutter/issues/103230
- [ ] Windows tool_integration_tests_2_6 flakes on deferred_components_test, https://github.com/flutter/flutter/issues/101609
- [ ] Windows tool_integration_tests_3_6: 
  - [ ] 1 flakes on `expression_evaluation_test`, https://github.com/flutter/flutter/issues/103215
  - [ ] 1 flakes on flutter_build_null_unsafe_test, https://github.com/flutter/flutter/issues/98140
  - [x] 1 flake on flutter_build_with_compilation_error_test, https://github.com/flutter/flutter/issues/101950
- [x] Windows tool_integration_tests_1_5: 7 flakes on timeout, fixed https://github.com/flutter/flutter/issues/95584
- [ ] Windows tool_integration_tests_2_5: 3 flakes: 1 timeout, 2 test flakes https://github.com/flutter/flutter/issues/97231
- [x] Windows tool_integration_tests_3_5: 1 flake on 1 timeout, fixed https://github.com/flutter/flutter/issues/95584
- [x] Windows tool_integration_tests_4_5: 2 flakes, https://github.com/flutter/flutter/issues/97232
- [x] Windows tool_integration_tests_5_5: 3 flakes on test, https://github.com/flutter/flutter/issues/97234
- [x] Mac tool_integration_tests_3_4: 1 flake, https://github.com/flutter/flutter/issues/97238
- [ ] Linux tool_integration_tests_1_4: 
  - [x] 1 flake on observatory_port_test timeout, https://github.com/flutter/flutter/issues/97240
  - [ ] 1 flake on gradle_non_android_plugin_test, https://github.com/flutter/flutter/issues/99767
- [x] Linux tool_integration_tests_3_4: 2 flakes: 2 test flakes, https://github.com/flutter/flutter/issues/94030
- [x] Linux tool_integration_tests_4_4: 
  - [x] 10 assertion flakes, https://github.com/flutter/flutter/issues/92042, 
  - [x] 4 flakes on multiple unit tests, https://github.com/flutter/flutter/issues/100245
  - [x] 1 flake on `cache_test`, https://github.com/flutter/flutter/issues/98141

**web_tool_tests**

- [x] Linux web_tool_tests
  - [ ] 2 flakes on `Unexpected character`, https://github.com/flutter/flutter/issues/94886
  - [x] 4 flakes on `Failed to create server socket`, https://github.com/flutter/flutter/issues/97332

**web_tests**

- [x] Linux web_tests flakes on `Connection refused+timeout`, https://github.com/flutter/flutter/issues/97324
- [x] Linux web_tests_4 
  - [ ] 1 flake on `list_wheel_scroll_view_test`, https://github.com/flutter/flutter/issues/103217
  - [x] flakes on `Segmentation fault`, https://github.com/flutter/flutter/issues/99004
- [ ] Linux web_tests_6 
  - [ ] 1 flake on `runtime/vm/object.cc`. https://github.com/flutter/flutter/issues/97326
  - [ ] 1 flake on `dialog_test`, https://github.com/flutter/flutter/issues/99942

**web_long_running_tests**

- [ ] Linux web_long_running_tests_1_5
  - [ ] 1 flake due to `malformed response from the FlutterDriver extension`, https://github.com/flutter/flutter/issues/102385
  - [ ] 1 flake on `version info not in JSON`, https://github.com/flutter/flutter/issues/97307, https://github.com/flutter/flutter/issues/102660
  - [x] 10 flakes on `The getter 'uri' was called on null`, https://github.com/flutter/flutter/issues/94031, https://github.com/flutter/flutter/issues/92042
  - [ ] 1 flake on `timeout`, https://github.com/flutter/flutter/issues/97312
  - [ ] 1 flake on `Chrome failed to start`, https://github.com/flutter/flutter/issues/97314
  - [ ] 1 flake on `image_loading_integration`, https://github.com/flutter/flutter/issues/97315
  - [ ] 1 flake on `Unable to start WebDriver Session`, https://github.com/flutter/flutter/issues/97316
- [ ] Linux web_long_running_tests_2_5
  - [x] 1 flake on `timeout`, https://github.com/flutter/flutter/issues/97317
  - [ ] 1 flake on `Unexpected character`, https://github.com/flutter/flutter/issues/97318
  - [ ] 1 flake on `version info not in JSON`, https://github.com/flutter/flutter/issues/97307
  - [x] 1 flake on `Failed to create server socket`, https://github.com/flutter/flutter/issues/97319
  - [ ] 1 flake on `Unable to start WebDriver Session`, https://github.com/flutter/flutter/issues/97316
- [ ] Linux web_long_running_tests_3_5
  - [x] 1 flake on `timeout`, https://github.com/flutter/flutter/issues/97320
  - [ ] 1 flake on `Unable to start WebDriver Session`, https://github.com/flutter/flutter/issues/97316
- [ ] Linux web_long_running_tests_4_5
  - [x] 1 flake on `Failed to create server socket`, https://github.com/flutter/flutter/issues/97319
  - [ ] 1 flake on `Unable to start WebDriver Session`, https://github.com/flutter/flutter/issues/97316
- [ ] Linux web_long_running_tests_5_5
  - [x] 1 flake on `type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`, https://github.com/flutter/flutter/issues/97322
  - [x] 1 flake on `Failed to create server socket`, https://github.com/flutter/flutter/issues/97319
  - [ ] 1 flake on `Unable to start WebDriver Session`, https://github.com/flutter/flutter/issues/97316
